{
  "hash": "c562778f989165f3d011ae1515f28bec",
  "result": {
    "engine": "jupyter",
    "markdown": "# Causal Mediation Analysis\n\n\n::: {.cell execution_count=2}\n``` {.julia .cell-code}\nusing CairoMakie\nCairoMakie.activate!(type = \"png\")\nusing GraphMakie\nusing Graphs\nusing GLM\nusing DataFrames\nusing StatsModels\nusing DataFramesMeta\nusing Random\nusing Distributions\nusing StatsFuns\nusing Statistics\nusing Lavaan\nusing Crumble\nusing Printf\n```\n:::\n\n\nMediation asks how a treatment works, not only whether it works. The graph\nbelow is the setting: $w$ is the treatment, $m$ a mediator that $w$ affects and\nthat in turn affects the outcome $y$, and $c$ a set of covariates confounding\nboth the $w \\to y$ and the $m \\to y$ relationships. The effect of $w$ on $y$\nsplits into a path through $m$ and a path around it.\n\n::: {.cell cache='true' message='false' execution_count=3}\n\n::: {.cell-output .cell-output-display execution_count=3}\n![](mediation_files/figure-pdf/dag4-output-1.png){#dag4}\n:::\n:::\n\n\n## Classical Mediation\n\nTraditionally mediation model can be represented in the following equations:\n\n$$ Y = a W + b M + \\epsilon_1 $$ {#eq-mediation-1} $$ M = c W + \\epsilon_2 $$ {#eq-mediation-2}\n\nThat is, we'd like to study the effect of $W$ on $Y$, and we see the effect can be a direct effect, and an indirect effect, through $M$.\n\nBaron and Kenny's (http://davidakenny.net/cm/mediate.htm) method is done in four steps. Modern approach tends to use SEM (structural equation modeling) to model these two equations directly.\n\nWe simulate $n = 10{,}000$ observations from exactly this structure:\n$X \\sim N(0,1)$, $M = 0.5X + \\varepsilon_2$, and $Y = 0.7M + 0.3X +\n\\varepsilon_1$, with both errors standard normal. So the true direct effect is\n$a = 0.3$, the mediator coefficient is $b = 0.7$, the treatment-to-mediator\ncoefficient is $c = 0.5$, the indirect effect is $bc = 0.35$, and the total\neffect is $0.3 + 0.35 = 0.65$. There is no confounding of any kind, which is\nwhat makes this the easy case.\n\n::: {.cell cache='true' message='false' execution_count=4}\n``` {.julia .cell-code}\nusing Random\nusing DataFrames\nusing StatsModels\nusing Lavaan\n\nRandom.seed!(1234)\nn = 10000\nX = randn(n)\nM = 0.5 .* X .+ randn(n)\nY = 0.7 .* M .+ 0.3 .* X .+ randn(n)\nData = DataFrame(X = X, M = M, Y = Y)\n\nmodel = \"\"\"\n   Y ~ a*X + b*M\n   M ~ c*X\n   # direct effect (a)\n   # indirect effect (b*c)\n   bc := b*c\n   # total effect\n   total := a + (b*c)\n\"\"\"\n```\n\n::: {#med1 .cell-output .cell-output-display execution_count=4}\n```\n\"   Y ~ a*X + b*M\\n   M ~ c*X\\n   # direct effect (a)\\n   # indirect effect (b*c)\\n   bc := b*c\\n   # total effect\\n   total := a + (b*c)\\n\"\n```\n:::\n:::\n\n\n::: {.cell cache='true' message='false' execution_count=5}\n``` {.julia .cell-code}\nfit = sem(model, Data)\nprintln(fit)\nparameterEstimates(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlavaan 0.1.0-dev fit object\n  Estimator:   ML\n  Converged:   Yes\n  χ²(0) = 0.000  [p = NaN]\n  Call summary() for full output.\n\n```\n:::\n\n::: {#med2 .cell-output .cell-output-display execution_count=5}\n```{=tex}\n\\begin{tabular}{r|cccccccccc}\n\t& lhs & op & rhs & est & se & z & pvalue & ci\\_lower & ci\\_upper & \\\\\n\t\\hline\n\t& String & String & String & Float64 & Float64 & Float64 & Float64 & Float64 & Float64 & \\\\\n\t\\hline\n\t1 & Y & \\textasciitilde{} & X & 0.295669 & 0.0111736 & 26.4614 & 0.0 & 0.273769 & 0.317569 & $\\dots$ \\\\\n\t2 & Y & \\textasciitilde{} & M & 0.70038 & 0.0099825 & 70.1608 & 0.0 & 0.680814 & 0.719946 & $\\dots$ \\\\\n\t3 & M & \\textasciitilde{} & X & 0.512129 & 0.00995286 & 51.4554 & 0.0 & 0.492621 & 0.531637 & $\\dots$ \\\\\n\t4 & bc & := & b*c & 0.358685 & 0.00864452 & 41.4927 & 0.0 & 0.341742 & 0.375628 & $\\dots$ \\\\\n\t5 & total & := & a + (b*c) & 0.654354 & 0.0121369 & 53.9143 & 0.0 & 0.630565 & 0.678142 & $\\dots$ \\\\\n\t6 & M & \\textasciitilde{}\\textasciitilde{} & M & 1.00917 & 0.0142719 & 70.7107 & 0.0 & 0.981199 & 1.03715 & $\\dots$ \\\\\n\t7 & Y & \\textasciitilde{}\\textasciitilde{} & Y & 1.00564 & 0.014222 & 70.7107 & 0.0 & 0.977769 & 1.03352 & $\\dots$ \\\\\n\t8 & X & \\textasciitilde{}\\textasciitilde{} & X & 1.01875 & NaN & NaN & NaN & NaN & NaN & $\\dots$ \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\nThe estimates are $a = 0.296$, $b = 0.700$ and $c = 0.512$, against true values\nof 0.3, 0.7 and 0.5. The derived quantities are $bc = 0.359$ against a true 0.35\nand a total of 0.654 against 0.65. Everything is recovered, and the model test\nstatistic is 0 on 0 degrees of freedom because the model is saturated --- it has\nas many parameters as moments, so it cannot fail to fit and the fit statistic\ncarries no information.\n\n### Problems with Classical Mediation\n\n-   Lack of causal claim. We have to assume that there is no unmeasured confounder between $M$ and $Y$. This is a strong assumption.\n-   Assumption of homogeneous effect.\n\n## Causal Mediation\n\n### CDE\n\nSuppose we can set $W$ and $M$ at will to any $(w, m)$, then we have the potential outcome $Y(w,m)$.\n\nControlled direct effect (CDE) is defined as $$ CDE(m) = E[Y(1,m)-Y(0,m)] $$ {#eq-mediation-3} That is, setting $M$ to $m$, what is the effect of $W$ on $Y$?\n\n### Assumptions\n\n-   Conditional treatment randomization. Suppose we observe confounders X, which can be a joint set of confounders for the W to Y pathway, or the M to Y pathway.\n\n$$  Y(w,m) \\perp W|X  $$ {#eq-mediation-4}\n\nThis is the usual conditional independence (unconfoundedness, ignorability, etc.) assumption. This is saying the assignment of treatment, given covariates $X$, has nothing to do with potential outcomes.\n\n-   Conditional mediator randomization.\n\n$$  Y(w,m) \\perp M|X, W=w  $$ {#eq-mediation-5}\n\nThis is to say, within each strata of X, given treatment status, the assignment of mediator gives no information about potential outcome. This randomization is usually not implemented during many experiments (random trials). This is the assumption that makes a lot of mediation hard to make a causal claim.\n\n-   Positivity (overlap). There are two positivity assumptions:\n\n$$  P(W=w | X=x) > 0  $$ {#eq-mediation-6} for all $x$. This is the usual positivity assumption.\n\n$$  P(M=m | X=x, W=w) > 0   $$ {#eq-mediation-7} for all $x$, $w$, and $m$. This is the mediator positivity.\n\n### Estimation\n\nCDE can be estimated using G-computation method, or IPW, or the doubly-robust methods, one of them is AIPW (augmented IPW).\n\n### G-computation\n\nG-computation is to model the outcome equation:  $$\n\\begin{aligned}\nCDE_G(m) &= \\sum_x [ E[Y \\mid W=1, M=m, X=x] \\\\\n&\\quad - E[Y \\mid W=0, M=m, X=x]]\\, P(X=x)\n\\end{aligned}\n$$ {#eq-mediation-8}\n\n\n### IPW\n\nIPW is to model the treatment assignment equation and the mediator assignment equation. The joint denominator factorizes *sequentially* -- treatment given covariates, then mediator given treatment and covariates -- which is the structure the estimator below relies on:\n\n$$ \\small\nE[Y(w,m)] = E\\!\\left[{\\frac{I(W=w)\\,I(M=m)}{g_W(w|X)\\,g_M(m|w,X)}}\\, Y\\right]\n$$ {#eq-mediation-9}\n\nTherefore,\n\n$$ \\small\nCDE_{ipw}(m) = E\\left[\\frac{I(W=1,M=m)}{g_M(m|1,X)\\,g_W(1|X)}\\, Y - \\frac{I(W=0,M=m)}{g_M(m|0,X)\\,g_W(0|X)}\\, Y\\right]\n$$ {#eq-mediation-10}\n\nwhere $g_M$ is the probability of the mediator and $g_W$ the probability of treatment. **This indicator-based form is for a discrete (here binary) mediator.** For a continuous mediator the indicator $I(M=m)$ and the probability $g_M$ must be replaced by a conditional density (or a kernel/stochastic-intervention formulation); the estimator above does not apply as written.\n\n### AIPW\n\n$$ CDE_{AIPW} = CDE_G(m) + B(\\bar Q, g_M, g_W) $$ {#eq-mediation-11} where $\\bar Q$ is the mean outcome function.\n\n $$\n\\begin{aligned}\nB(\\bar Q, g_M, g_W) &= \\frac{1}{n} \\sum_{i=1}^{n} {\\frac{I(M_i=m, W_i=1)}{g_M(m|1, X_i) g_W(1|X_i)}[Y_i-\\bar Q(m,1,X_i)]} \\\\\n&\\quad - \\frac{1}{n} \\sum_{i=1}^{n} {\\frac{I(M_i=m, W_i=0)}{g_M(m|0, X_i) g_W(0|X_i)}[Y_i-\\bar Q(m,0,X_i)]}\n\\end{aligned}\n$$ {#eq-mediation-12}\n\n\n### Example: G-computation\n\nThe three estimators below run on one simulated data set of $n = 5000$. There\nare two independent standard normal covariates, $W_1$ confounding the\ntreatment-outcome relationship and $W_2$ confounding the mediator-outcome\nrelationship. Treatment is $A \\sim \\text{Bernoulli}(\\Lambda(-1 + W_1/2))$, the\nmediator is $M \\sim \\text{Bernoulli}(\\Lambda(-2 + A/2 + W_2/3))$, and the\noutcome is\n$Y \\sim \\text{Bernoulli}(\\Lambda(-1 + A - M/2 + W_1/3 + W_2/3))$. All three are\nbinary.\n\nThe target is $CDE(0)$, the effect of treatment with the mediator held at 0 for\neveryone. Since the DGP is fully specified we can integrate it out:\n$CDE(0) = E_W[\\Lambda(W_1/3 + W_2/3) - \\Lambda(-1 + W_1/3 + W_2/3)] = 0.222$.\nFor comparison, $CDE(1) = 0.191$ --- the effect is smaller when the mediator is\nheld at 1, because the logistic link is flatter away from its centre.\n\n::: {#med3 .cell cache='true' message='false' execution_count=6}\n``` {.julia .cell-code}\nusing GLM\nusing Distributions\nusing StatsFuns\nusing Statistics\n\nRandom.seed!(1234)\nn = 5000\n# confounder of A/Y\nW1 = randn(n)\n# confounder of M/Y\nW2 = randn(n)\n# treatment\nA = rand.(Bernoulli.(logistic.(-1 .+ W1 ./ 2)))\n# binary mediator\nM = rand.(Bernoulli.(logistic.(-2 .+ A ./ 2 .+ W2 ./ 3)))\n# binary outcome\nY = rand.(Bernoulli.(logistic.(-1 .+ A .- M ./ 2 .+ W1 ./ 3 .+ W2 ./ 3)))\nfull_data = DataFrame(W1 = W1, W2 = W2, A = A, M = M, Y = Y)\n\n# fit outcome regression\nor_fit = glm(@formula(Y ~ A + M + W1 + W2), full_data, Binomial(), LogitLink())\n\n# new data setting A and M\ndata_A1_M0 = copy(full_data)\ndata_A0_M0 = copy(full_data)\ndata_A1_M0.A .= 1; data_A1_M0.M .= 0\ndata_A0_M0.A .= 0; data_A0_M0.M .= 0\n\n# predict on new data\nQbar_A1_M0 = predict(or_fit, data_A1_M0)\nQbar_A0_M0 = predict(or_fit, data_A0_M0)\n\n# gcomp estimate of CDE(0)\ncde_gcomp = mean(Qbar_A1_M0 .- Qbar_A0_M0)\n@printf \"CDE(0) G-computation = %.4g\\n\" cde_gcomp\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCDE(0) G-computation = 0.2113\n```\n:::\n:::\n\n\nG-computation gives 0.2113.\n\n### Example: IPW\n\nThe same target through the treatment and mediator models instead of the\noutcome model.\n\n::: {#med4 .cell cache='true' message='false' execution_count=7}\n``` {.julia .cell-code}\n# model for P(A = 1 | W)\nps_fit1 = glm(@formula(A ~ W1 + W2), full_data, Binomial(), LogitLink())\nP_A1_W = predict(ps_fit1)\nP_A0_W = 1 .- P_A1_W\n\n# model for P(M = 0 | A, W)\nps_fit2 = glm(@formula(M ~ A + W1 + W2), full_data, Binomial(), LogitLink())\n\n# P(M = 0 | A = 1, W)\ndata_A1 = copy(full_data); data_A1.A .= 1\nP_M0_A1_W = 1 .- predict(ps_fit2, data_A1)\n\n# P(M = 0 | A = 0, W)\ndata_A0 = copy(full_data); data_A0.A .= 0\nP_M0_A0_W = 1 .- predict(ps_fit2, data_A0)\n\n# ipw estimate of CDE(0)\ncde_ipw = mean( (A .== 1) ./ P_A1_W .* (M .== 0) ./ P_M0_A1_W .* Y ) -\n          mean( (A .== 0) ./ P_A0_W .* (M .== 0) ./ P_M0_A0_W .* Y )\n@printf \"CDE(0) IPW = %.4g\\n\" cde_ipw\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCDE(0) IPW = 0.226\n```\n:::\n:::\n\n\nIPW gives 0.2260.\n\n### Example: AIPW\n\nCombining both, so that either the outcome model or the two treatment models\nmay be wrong.\n\n::: {#med5 .cell cache='true' message='false' execution_count=8}\n``` {.julia .cell-code}\n# aipw estimate of E[Y(1,0)]\naiptw_EY_A1_M0 = mean(Qbar_A1_M0) +\nmean( (A .== 1) ./ P_A1_W .* (M .== 0) ./ P_M0_A1_W .* (Y .- Qbar_A1_M0) )\n\n# aipw estimate of E[Y(0,0)]\naiptw_EY_A0_M0 = mean(Qbar_A0_M0) +\nmean( (A .== 0) ./ P_A0_W .* (M .== 0) ./ P_M0_A0_W .* (Y .- Qbar_A0_M0) )\n\n# aipw estimate of CDE(0)\ncde_aipw = aiptw_EY_A1_M0 - aiptw_EY_A0_M0\n@printf \"CDE(0) AIPW = %.4g\\n\" cde_aipw\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCDE(0) AIPW = 0.2245\n```\n:::\n:::\n\n\nAIPW gives 0.2245.\n\nThe three estimates are 0.2113, 0.2260 and 0.2245 against a true $CDE(0)$ of\n0.222. Every model here is correctly specified, and over 400 replications of this\ndesign the g-computation estimator averages 0.2216 with a sampling standard\ndeviation of 0.0154, so this seed's 0.2113 is 0.7 standard deviations low. The\nthree estimators share the same data and the same fitted nuisance models, so their\nagreement with each other is a check on implementation, not on sampling error.\n\n## NIE and NDE: Natural Direct and Indirect Effects\n\nCDE is to study the effect of treatment, given the level of mediator. Instead, Natural Effect is to set mediator to its natural value with the value of treatment, that is, $M=M(w)$.\n\n\n$$\n\\begin{aligned}\nATE &= NIE + NDE \\\\\n&= (E[Y(1,M(1))] - E[Y(1,M(0))]) \\\\\n&\\quad + (E[Y(1, M(0))] - E[Y(0,M(0))])\n\\end{aligned}\n$$ {#eq-mediation-13}\n\n\nThe advantage of NDE and NIE comparing to CDE is that it's more \"natural\"; that is, you don't set the level of mediator deterministically. And it can decompose the ATE into direct and indirect effects.\n\nHowever, there is an additional assumption needed to identify NDE and NIE.\n\n### Additional Assumption\n\n$$ Y(w, m) \\perp M(w^*) | X$$ {#eq-mediation-14}\n\nThis is the \"cross-world\" condition: the outcome under $(w,m)$ is independent of $M$ under $w^*$. These two situations cannot happen in the same world; you cannot set $W$ to both $w$ and $w^*$. No experiment can implement it.\n\nThis cross-world independence is *additional to*, not a replacement\nfor, the usual identifying assumptions. The standard mediation formula\nfor natural effects also requires:\n\n- treatment ignorability (no unmeasured treatment-outcome confounding) given $X$;\n- mediator ignorability (no unmeasured mediator-outcome confounding) given $W$ and $X$;\n- positivity for both the treatment and the mediator; and\n- **no treatment-induced confounding** of the mediator-outcome\n  relationship -- there must be no variable affected by $W$ that\n  confounds $M$ and $Y$. (When such a confounder exists, natural\n  effects are not identified by this formula and interventional\n  direct/indirect effects are used instead.)\n\nThe cross-world condition by itself is not sufficient.\n\n### Estimation\n\nWe use the same simulated data. The outcome model now adds $A \\times M$ and\n$M \\times W_1$ interactions and the mediator model adds $A \\times W_1$ and\n$W_1 \\times W_2$ — both are richer than the DGP requires, which costs a little\nprecision and no consistency. We then average $E[Y \\mid A=a, M, W]$ over the\ndistribution of $M$ under $A = a'$, for each of the four $(a, a')$ combinations.\n\nThe truths again follow from the DGP by integration:\n$E[Y(1,M(1))] = 0.478$, $E[Y(1,M(0))] = 0.486$ and $E[Y(0,M(0))] = 0.267$, so\nthe true $NDE = 0.218$, $NIE = -0.008$ and $ATE = 0.211$. The indirect effect\nis slightly negative because treatment raises the chance of the mediator (from\n0.124 to 0.188) while the mediator lowers the outcome — the $-M/2$ term. So\nthis treatment helps directly and hurts a little through its mediator.\n\n::: {#med6 .cell cache='true' message='false' execution_count=9}\n``` {.julia .cell-code}\n# fit outcome regression (include interaction because we can)\nor_fit = glm(@formula(Y ~ A + M + W1 + W2 + A&M + M&W1), full_data, Binomial(), LogitLink())\n\n# need E(Y | A = 0/1, M = 0/1, W1 = W1i, W2 = W2i)\nfunction get_EY_a_m_Wi(full_data, or_fit, a, m)\n    data_Aa_Mm_Wi = copy(full_data)\n    data_Aa_Mm_Wi.A .= a\n    data_Aa_Mm_Wi.M .= m\n    predict(or_fit, data_Aa_Mm_Wi)\nend\n\nEY_A0_M0_Wi = get_EY_a_m_Wi(full_data, or_fit, 0, 0)\nEY_A0_M1_Wi = get_EY_a_m_Wi(full_data, or_fit, 0, 1)\nEY_A1_M0_Wi = get_EY_a_m_Wi(full_data, or_fit, 1, 0)\nEY_A1_M1_Wi = get_EY_a_m_Wi(full_data, or_fit, 1, 1)\n\n# include interactions -- why not? (NOTE: A*W1 expands to A + W1 + A&W1, so\n# the MAIN effects are included. Writing only A&W1 would omit the main effect\n# of A and force the estimated NIE to be essentially zero by construction.)\nmed_fit = glm(@formula(M ~ A*W1 + W1*W2), full_data, Binomial(), LogitLink())\n\n# estimates of P(M = m | A = a, W = W_i)\nfunction get_Pm_a_Wi(full_data, med_fit, a, m)\n    data_Aa_Wi = copy(full_data)\n    data_Aa_Wi.A .= a\n    p = predict(med_fit, data_Aa_Wi)\n    if m == 1\n        return p\n    else\n        return 1 .- p\n    end\nend\n\nPM0_A0_Wi = get_Pm_a_Wi(full_data, med_fit, 0, 0)\nPM1_A0_Wi = get_Pm_a_Wi(full_data, med_fit, 0, 1)\nPM0_A1_Wi = get_Pm_a_Wi(full_data, med_fit, 1, 0)\nPM1_A1_Wi = get_Pm_a_Wi(full_data, med_fit, 1, 1)\n\n# E(E(Y | A = 1, M, W) | A = 1, W)\nEY1M1_Wi = EY_A1_M1_Wi .* PM1_A1_Wi .+ EY_A1_M0_Wi .* PM0_A1_Wi\n# E(E(Y | A = 0, M, W) | A = 1, W)\nEY0M1_Wi = EY_A0_M1_Wi .* PM1_A1_Wi .+ EY_A0_M0_Wi .* PM0_A1_Wi\n# E(E(Y | A = 1, M, W) | A = 0, W)\nEY1M0_Wi = EY_A1_M1_Wi .* PM1_A0_Wi .+ EY_A1_M0_Wi .* PM0_A0_Wi\n# E(E(Y | A = 0, M, W) | A = 0, W)\nEY0M0_Wi = EY_A0_M1_Wi .* PM1_A0_Wi .+ EY_A0_M0_Wi .* PM0_A0_Wi\n\n# estimate of E[Y(1, M(1))]\nE_Y1M1 = mean(EY1M1_Wi)\n# estimate of E[Y(0, M(1))]\nE_Y0M1 = mean(EY0M1_Wi)\n# estimate of E[Y(1, M(0))]\nE_Y1M0 = mean(EY1M0_Wi)\n# estimate of E[Y(0, M(0))]\nE_Y0M0 = mean(EY0M0_Wi)\n\n# NDE = E[Y(1,M(0))] - E[Y(0,M(0))], NIE = E[Y(1,M(1))] - E[Y(1,M(0))]\n@printf \"NDE = %.4g\\n\" (E_Y1M0 - E_Y0M0)\n@printf \"NIE = %.4g\\n\" (E_Y1M1 - E_Y1M0)\n@printf \"ATE = %.4g\\n\" (E_Y1M1 - E_Y0M0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNDE = 0.2093\nNIE = -0.01266\nATE = 0.1966\n```\n:::\n:::\n\n\nThe estimates are $NDE = 0.209$, $NIE = -0.013$ and $ATE = 0.197$, against\ntruths of 0.218, $-0.008$ and 0.211. The decomposition holds exactly by\nconstruction, $0.2093 + (-0.0127) = 0.1966$, and the sign of the indirect effect is\nrecovered. The direct and total effects sit about 0.01 below their truths, as the\ng-computation estimate of $CDE(0)$ did, for the same reason: it is one draw of the\ndata, and every quantity in this section is computed from it.\n\nNote how much smaller the indirect effect is than the direct one, $-0.013$\nagainst 0.209. Reporting only the total effect of 0.197 would hide that the\nmediator works against the treatment.\n\n## IIE and IDE: Interventional Direct and Indirect Effects\n\nPeople are not happy with the cross-world assumption in general. Interventional direct and indirect effects avoid it. The device is a random draw: let $M^*_w$ denote a draw from the distribution of $M(w)$ given $X=x$, rather than the unit's own $M(w)$. The standard definitions [@vansteelandt-daniel-2017; @diaz-hejazi-rudolph-vanderlaan-2021] use such a draw in every term:\n\n\n$$\n\\begin{aligned}\nIDE &= E[Y(1,M^*_0)] - E[Y(0,M^*_0)] \\\\\nIIE &= E[Y(1,M^*_1)] - E[Y(1,M^*_0)]\n\\end{aligned}\n$$ {#eq-mediation-15}\n\n\nThe direct effect holds the mediator draw fixed at its untreated distribution; the indirect effect moves only that distribution. The two add up to\n\n$$\nIDE + IIE = E[Y(1,M^*_1)] - E[Y(0,M^*_0)],\n$$ {#eq-mediation-16}\n\nthe *overall interventional effect*. It need not equal the $ATE$: replacing the unit's own $M(w)$ by a random draw breaks the within-unit dependence between $M(w)$ and $Y(w,\\cdot)$, and that dependence matters exactly when a treatment-induced confounder $Z$ sits between the treatment and the mediator --- the situation in the example below. The payoff is identification without the cross-world assumption, even in the presence of such a $Z$. These interventional effects are the estimands `Crumble.jl` estimates with `effect = \"RI\"`.\n\n### Example\n\nThis example uses the `medoutcon` vignette's own DGP, which is built to contain\nexactly the treatment-induced confounder that defeats natural effects. We draw\n$n = 1000$ observations. Three binary baseline covariates:\n$W_1 \\sim \\text{Bernoulli}(0.6)$, $W_2 \\sim \\text{Bernoulli}(0.3)$, and\n$W_3 \\sim \\text{Bernoulli}(\\min(0.2 + (W_1+W_2)/3,\\, 1))$. Treatment is\n$A \\sim \\text{Bernoulli}(\\Lambda(\\sum_j W_j - 2))$.\n\nThen the key variable: $Z \\sim \\text{Bernoulli}(\\Lambda(-\\log 2 + (W_1+W_2+W_3)/3 - A + 0.2))$\nis a mediator-outcome confounder that depends on $A$. The mediator is\n$M \\sim \\text{Bernoulli}(\\Lambda(\\log 3 (W_1 + W_2) + 2A - 2Z))$ and the outcome is\n$Y \\sim \\text{Bernoulli}(\\Lambda(1/(\\sum_j W_j - Z + A + M)))$.\n\nBecause $Z$ is affected by $A$ and confounds $M$ and $Y$, natural direct and\nindirect effects are not identified here by the formula of the previous\nsection. Interventional effects are, which is the reason for this example.\nEvery variable is binary, so the truth follows by summing over the DGP:\n$IDE = -0.074$ and $IIE = -0.025$. Their sum, the overall interventional effect,\nis $-0.099$, while the $ATE$ is $-0.083$. That is the gap @eq-mediation-16 warns\nabout: with $Z$ present, the two interventional effects do not add up to the\ntotal effect.\n\n::: {.cell cache='true' message='false' execution_count=10}\n``` {.julia .cell-code}\nusing DataFrames\nusing StatsModels\nusing Random\nusing StatsFuns\nusing Distributions\nusing Crumble\n\nRandom.seed!(1584)\n\n# produces a simple data set based on a causal model with mediation\nfunction make_example_data(n_obs = 1000)\n    # baseline covariates\n    w_1 = rand.(Bernoulli(0.6), n_obs)\n    w_2 = rand.(Bernoulli(0.3), n_obs)\n    w_3_prob = min.(0.2 .+ (w_1 .+ w_2) ./ 3, 1.0)\n    w_3 = rand.(Bernoulli.(w_3_prob))\n\n    # exposure\n    a_prob = logistic.(w_1 .+ w_2 .+ w_3 .- 2)\n    a = rand.(Bernoulli.(a_prob))\n\n    # mediator-outcome confounder affected by treatment\n    z_prob = logistic.(-log(2) .- a .+ (w_1 .+ w_2 .+ w_3) ./ 3 .+ 0.2)\n    z = rand.(Bernoulli.(z_prob))\n\n    # mediator -- could be multivariate\n    m_prob = logistic.(log(3) .* (w_1 .+ w_2) .+ 2 .* a .- 2 .* z)\n    m = rand.(Bernoulli.(m_prob))\n\n    # outcome\n    y_prob = logistic.(1 ./ (w_1 .+ w_2 .+ w_3 .- z .+ a .+ m))\n    y = rand.(Bernoulli.(y_prob))\n\n    # construct output\n    dat = DataFrame(W_1 = w_1, W_2 = w_2, W_3 = w_3, A = a, Z = z, M = m, Y = y)\n    return dat\nend\n```\n\n::: {#med7 .cell-output .cell-output-display execution_count=10}\n```\nmake_example_data (generic function with 2 methods)\n```\n:::\n:::\n\n\n::: {.cell cache='true' message='false' execution_count=11}\n``` {.julia .cell-code}\n# set seed and simulate example data\nexample_data = make_example_data()\nw_names = [\"W_1\", \"W_2\", \"W_3\"]\nm_names = [\"M\"]\n\n# quick look at the data\nfirst(example_data, 6)\n```\n\n::: {#med8 .cell-output .cell-output-display execution_count=11}\n```{=tex}\n\\begin{tabular}{r|ccccccc}\n\t& W\\_1 & W\\_2 & W\\_3 & A & Z & M & Y\\\\\n\t\\hline\n\t& Bool & Bool & Bool & Bool & Bool & Bool & Bool\\\\\n\t\\hline\n\t1 & 0 & 1 & 0 & 0 & 0 & 1 & 1 \\\\\n\t2 & 0 & 0 & 0 & 0 & 0 & 1 & 1 \\\\\n\t3 & 0 & 0 & 0 & 0 & 0 & 1 & 1 \\\\\n\t4 & 0 & 0 & 0 & 0 & 0 & 1 & 1 \\\\\n\t5 & 1 & 0 & 0 & 0 & 0 & 0 & 1 \\\\\n\t6 & 1 & 1 & 1 & 1 & 1 & 1 & 0 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n::: {.cell cache='true' message='false' execution_count=12}\n``` {.julia .cell-code}\n# one-step estimates of the interventional direct and indirect effects\n# (effect = \"RI\"); the Riesz representers are bounded at 100, see below\nresult = crumble(example_data, [\"A\"];\n                 outcome   = \"Y\",\n                 mediators = m_names,\n                 moc       = [\"Z\"],       # mediator-outcome confounder affected by A\n                 covar     = w_names,\n                 effect    = \"RI\",\n                 learners  = [\"glm\"],\n                 control   = crumble_control(alpha_cap = 100.0))\nCrumble.tidy(result)\n```\n\n::: {#med9 .cell-output .cell-output-display execution_count=12}\n```{=tex}\n\\begin{tabular}{r|cccccc}\n\t& estimand & estimate & std\\_error & conf\\_low & conf\\_high & p\\_value\\\\\n\t\\hline\n\t& String & Float64 & Float64 & Float64 & Float64 & Float64\\\\\n\t\\hline\n\t1 & ride & 0.0165558 & 0.124993 & -0.22843 & 0.261541 & 0.894625 \\\\\n\t2 & riie & -9.7107e-6 & 0.0967316 & -0.189604 & 0.189584 & 0.99992 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\nThe one-step estimator gives an interventional direct effect of $0.017$ with a\n95% interval of $[-0.228, 0.262]$, against a true $-0.074$, and an indirect effect\nof $0.000$ with an interval of $[-0.190, 0.190]$, against a true $-0.025$. Both\nintervals include zero and both truths.\n\n`Crumble.jl` fits the Riesz representers --- the weights in the one-step\ncorrection --- with a neural network, and this design is hard on them. The true\nweight for the direct-effect functional reaches 45 in a covariate cell that holds\nabout two observations per cross-fitting fold. When a fold misses that cell, the\nRiesz loss has no minimiser there and an unbounded fit can drift into the\nthousands. The call above bounds the weights at 100, well above the true maximum.\n\nThe flexible weights cost precision. The interval here is more than twice as wide\nas the one from `medoutcon` in the [R companion\nchapter](https://xiangao.github.io/causal_econometrics_guide/mediation.html), which\nalso compares the one-step estimator with TMLE; `Crumble.jl` implements only the\none-step estimator.\n\n",
    "supporting": [
      "mediation_files/figure-pdf"
    ],
    "filters": []
  }
}