{
  "hash": "578f5865a42eed796f09175d859ce5cf",
  "result": {
    "engine": "jupyter",
    "markdown": "# Heterogeneous Treatment Effects with Machine Learning\n\n\n::: {.cell execution_count=2}\n``` {.julia .cell-code}\nusing DataFrames\nusing Distributions\nusing Random\nusing Statistics\nusing LinearAlgebra\nusing Printf\nusing MLJ\nusing MLJDecisionTreeInterface\nusing GLM\nusing CairoMakie\nCairoMakie.activate!(type = \"png\")\n```\n:::\n\n\nThe [estimands chapter](causal-estimands.qmd) defined the conditional\naverage treatment effect\n\n$$\n\\text{CATE}(x) = \\mathbb{E}[Y(1) - Y(0) \\mid X = x]\n$$ {#eq-heterogeneous-effects-1}\n\nas the effect of treatment for units with covariates $X=x$. In simulation\nwe can compute CATE from known potential outcomes. In real data we observe\nonly one potential outcome per unit, so CATE has to be estimated from\n$(X,D,Y)$.\n\nHere I focus on meta-learners: recipes that turn a regression method\ninto a CATE estimator. I implement S-, T-, X-, R-, and DR-learners using\n`MLJ` and `DecisionTree.jl` random forests.\n\nJulia does not currently have an equivalent of R's\n`grf::causal_forest` with honest sample splitting and CATE confidence\nintervals. For that workflow, use the R companion chapter.\n\n## The data-generating process\n\nI use the same CATE function as the estimands chapter,\n$\\tau(x)=1+2x_1$ (the rest of the DGP differs: five covariates and\nconfounding through the observed $X_2$).\n\n::: {#dgp .cell cache='true' execution_count=3}\n``` {.julia .cell-code}\nRandom.seed!(42)\nn = 5000\np = 5\n\nX    = rand(n, p)\n# Treatment depends on the OBSERVED covariate X2 (a backdoor confounder we\n# adjust for), so unconfoundedness given X holds and the estimators below are\n# consistent for the true CATE/ATE.\nps   = @. 1 / (1 + exp(-(-0.3 + 1.5 * X[:, 2])))\nD    = Float64.(rand(n) .< ps)\ntau  = @. 1 + 2 * X[:, 1]\nY0   = @. 0.5 * X[:, 2] + randn()\nY1   = Y0 .+ tau\nY    = ifelse.(D .== 1, Y1, Y0)\n\n@printf(\"n = %d, true ATE = %.3f\\n\", n, mean(tau))\n@printf(\"True CATE at X1 = 0.2: %.2f\\n\", 1 + 2 * 0.2)\n@printf(\"True CATE at X1 = 0.8: %.2f\\n\", 1 + 2 * 0.8)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nn = 5000, true ATE = 2.009\nTrue CATE at X1 = 0.2: 1.40\nTrue CATE at X1 = 0.8: 2.60\n```\n:::\n:::\n\n\nTreatment is related to the observed covariate $X_2$, which also affects the\noutcome — a backdoor confounder. Because $X_2$ is observed and in the\nconditioning set, unconfoundedness holds and the estimators below are\nconsistent for the true CATE/ATE.\n\n## A wrapper for fitting random forests\n\nTo keep the code short, define a helper that fits a random forest and\nreturns predictions.\n\n::: {#helper .cell cache='true' execution_count=4}\n``` {.julia .cell-code}\nconst RFR = @load RandomForestRegressor pkg=DecisionTree verbosity=0\n\n\"\"\"\n    rf_fit_predict(Xtrain, ytrain, Xpredict; n_trees=500, weights=nothing)\nFit a random forest on (Xtrain, ytrain) and return predictions at Xpredict.\nDecisionTree's `RandomForestRegressor` does not accept per-sample weights, so\nwhen `weights` are supplied we approximate a weighted fit by resampling the\ntraining rows with probability proportional to the weights (weighted bootstrap).\n\"\"\"\nfunction rf_fit_predict(Xtrain, ytrain, Xpredict; n_trees::Int=500,\n                        weights=nothing)\n    if weights !== nothing\n        w = Float64.(weights)\n        m = size(Xtrain, 1)\n        cdf = cumsum(w) ./ sum(w)            # weighted-bootstrap CDF\n        idx = [searchsortedfirst(cdf, rand()) for _ in 1:m]\n        Xtrain = Xtrain[idx, :]\n        ytrain = ytrain[idx]\n    end\n    learner = RFR(n_trees=n_trees, max_depth=-1)\n    Xtrain_t = MLJ.table(Xtrain)\n    Xpred_t  = MLJ.table(Xpredict)\n    mach = machine(learner, Xtrain_t, Float64.(ytrain))\n    fit!(mach, verbosity=0)\n    return MLJ.predict(mach, Xpred_t)\nend\n\n\"\"\"\n    rf_oof(Xtrain, ytrain, Xpredict, folds; n_trees=500, weights=nothing, rows=...)\n\nOut-of-fold version of `rf_fit_predict`. For each fold `k`, fit on the rows *not*\nin `k` and predict only the fold-`k` rows of `Xpredict`. Restrict the training\nrows further with `rows` (used below to fit an arm-specific model while still\npredicting for everybody).\n\nEvery CATE estimate in the meta-learner comparison below goes through this\nfunction rather than `rf_fit_predict`, and the reason matters. A random forest asked to predict at the\nsame rows it was trained on partly reproduces its own training targets, so an\nin-sample CATE is contaminated by the noise in whatever pseudo-outcome it was fit\nto. That inflates apparent accuracy for learners whose target is close to `Y`\nand destroys it for learners whose target is a high-variance pseudo-outcome --\nwhich is exactly the DR- and R-learners. It also makes any downstream *ranking*\non the estimate invalid; see the GATES section for what that does.\n\"\"\"\nfunction rf_oof(Xtrain, ytrain, Xpredict, folds; n_trees::Int=500,\n                weights=nothing, rows=trues(length(folds)))\n    out = zeros(size(Xpredict, 1))\n    for k in unique(folds)\n        train = (folds .!= k) .& rows\n        test  = folds .== k\n        w = weights === nothing ? nothing : Float64.(weights)[train]\n        out[test] = rf_fit_predict(Xtrain[train, :], ytrain[train],\n                                   Xpredict[test, :]; n_trees=n_trees, weights=w)\n    end\n    return out\nend\n\n# One fold assignment, shared by every learner below so that the comparison\n# across learners is like-for-like.\nRandom.seed!(7)\nfolds = rand(1:5, n)\nnothing\n```\n:::\n\n\n## S-learner (\"single\")\n\nFit one regression of $Y$ on $(D, X)$, then predict the difference between\n$D = 1$ and $D = 0$ for each $x$:\n\n::: {#s-learner .cell cache='true' execution_count=5}\n``` {.julia .cell-code}\nX_with_D = hcat(D, X)\nX1_test  = hcat(ones(n), X)\nX0_test  = hcat(zeros(n), X)\n\nmu1_S = rf_oof(X_with_D, Y, X1_test, folds)\nmu0_S = rf_oof(X_with_D, Y, X0_test, folds)\ntau_S = mu1_S .- mu0_S\n\n@printf(\"S-learner CATE correlation with truth: %.3f\\n\", cor(tau_S, tau))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nS-learner CATE correlation with truth: 0.884\n```\n:::\n:::\n\n\nThe S-learner is simple. Its weakness is that the model may treat $D$ as a\nminor predictor and shrink treatment effects toward zero.\n\n## T-learner (\"two\")\n\nFit two separate regressions, one on treated units and one on controls:\n\n::: {#t-learner .cell cache='true' execution_count=6}\n``` {.julia .cell-code}\nidx_T = D .== 1\nidx_C = D .== 0\n\nmu1_T = rf_oof(X, Y, X, folds; rows = idx_T)   # treated-arm model, predicted for all\nmu0_T = rf_oof(X, Y, X, folds; rows = idx_C)   # control-arm model, predicted for all\ntau_T = mu1_T .- mu0_T\n\n@printf(\"T-learner CATE correlation with truth: %.3f\\n\", cor(tau_T, tau))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nT-learner CATE correlation with truth: 0.882\n```\n:::\n:::\n\n\nThe T-learner gives treatment and control separate outcome models. It can\nwork well, but it can extrapolate badly when treated and control covariate\ndistributions do not overlap.\n\n## X-learner [@kunzel-2019-metalearners]\n\nThe X-learner starts from the T-learner. It imputes missing potential\noutcomes, creates pseudo-treatment effects, smooths them over $X$, and then\ncombines the two arms with propensity-score weights.\n\n::: {#x-learner .cell cache='true' execution_count=7}\n``` {.julia .cell-code}\n# Step 1: pseudo-outcomes, stored full-length so the arm models can be fit\n# out-of-fold with `rows` (entries outside each arm are never used for training)\nD1_pseudo = zeros(n); D1_pseudo[idx_T] = Y[idx_T] .- mu0_T[idx_T]   # observed - imputed Y(0)\nD0_pseudo = zeros(n); D0_pseudo[idx_C] = mu1_T[idx_C] .- Y[idx_C]   # imputed Y(1) - observed\n\n# Step 2: regress pseudo-outcomes on X in each arm\ntau_X1 = rf_oof(X, D1_pseudo, X, folds; rows = idx_T)\ntau_X0 = rf_oof(X, D0_pseudo, X, folds; rows = idx_C)\n\n# Step 3: weight by propensity score\ne_hat = clamp.(rf_oof(X, D, X, folds), 0.02, 0.98)\n\ntau_X = e_hat .* tau_X0 .+ (1 .- e_hat) .* tau_X1\n@printf(\"X-learner CATE correlation with truth: %.3f\\n\", cor(tau_X, tau))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nX-learner CATE correlation with truth: 0.928\n```\n:::\n:::\n\n\nThe X-learner is useful when one treatment arm is much smaller than the\nother.\n\n## R-learner [@nie-wager-2021]\n\nThe R-learner partials out the main effects of $X$ from both $Y$ and $D$:\n\n$$\n\\tilde Y_i = \\frac{Y_i - \\hat m(X_i)}{D_i - \\hat e(X_i)}, \\qquad\n\\text{weight}_i = (D_i - \\hat e(X_i))^2,\n$$ {#eq-heterogeneous-effects-2}\n\nwhere $\\hat m(x) = \\mathbb{E}[Y \\mid X = x]$ and $\\hat e(x) = \\mathbb{E}[D \\mid X = x]$\nare cross-fitted nuisance estimates.\n\n::: {#r-learner .cell cache='true' execution_count=8}\n``` {.julia .cell-code}\n# Nuisances cross-fitted on the shared folds defined in the helper chunk\nm_hat    = rf_oof(X, Y, X, folds)\ne_hat_cv = clamp.(rf_oof(X, D, X, folds), 0.02, 0.98)\n\npseudo_R   = (Y .- m_hat) ./ (D .- e_hat_cv)\nweights_R  = (D .- e_hat_cv) .^ 2\n\n# The R-learner is a *weighted* regression of pseudo_R on X with weights\n# (D - e_hat)^2. DecisionTree's RF does not accept per-sample weights, so we\n# pass them through the weighted-bootstrap path of `rf_fit_predict` (reached here\n# via `rf_oof`, which forwards `weights`). This downweights\n# observations with D close to e_hat, whose pseudo_R blows up (division by a\n# near-zero denominator) and would otherwise dominate the split criterion.\ntau_R = rf_oof(X, pseudo_R, X, folds; weights = weights_R)\n@printf(\"R-learner CATE correlation with truth: %.3f\\n\", cor(tau_R, tau))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR-learner CATE correlation with truth: 0.714\n```\n:::\n:::\n\n\nThe R-learner is often stable when overlap is reasonable because nuisance\nmodel errors have only second-order effects on the target.\n\n## DR-learner [@kennedy-2020-optimal-dr]\n\nThe DR-learner uses an AIPW-style pseudo-outcome and then regresses it on\n$X$:\n\n$$\n\\tilde Y_i^{DR} = \\hat\\mu_1(X_i) - \\hat\\mu_0(X_i) +\n\\frac{D_i (Y_i - \\hat\\mu_1(X_i))}{\\hat e(X_i)} -\n\\frac{(1 - D_i) (Y_i - \\hat\\mu_0(X_i))}{1 - \\hat e(X_i)}.\n$$ {#eq-heterogeneous-effects-3}\n\n::: {#dr-learner .cell cache='true' execution_count=9}\n``` {.julia .cell-code}\nmu1_cf = rf_oof(X, Y, X, folds; rows = D .== 1)\nmu0_cf = rf_oof(X, Y, X, folds; rows = D .== 0)\ne_cf   = clamp.(rf_oof(X, D, X, folds), 0.02, 0.98)\n\npseudo_DR = @. (mu1_cf - mu0_cf) +\n               D * (Y - mu1_cf) / e_cf -\n               (1 - D) * (Y - mu0_cf) / (1 - e_cf)\n\ntau_DR = rf_oof(X, pseudo_DR, X, folds)\n@printf(\"DR-learner CATE correlation with truth: %.3f\\n\", cor(tau_DR, tau))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDR-learner CATE correlation with truth: 0.769\n```\n:::\n:::\n\n\n## Comparing all five estimators\n\n::: {.cell cache='true' execution_count=10}\n``` {.julia .cell-code}\nfig = Figure(size = (1000, 700))\nlabs = [\"S-learner\", \"T-learner\", \"X-learner\", \"R-learner\", \"DR-learner\"]\npreds = [tau_S, tau_T, tau_X, tau_R, tau_DR]\n\nfor (i, (lab, pred)) in enumerate(zip(labs, preds))\n    row, col = divrem(i - 1, 3) .+ (1, 1)\n    ax = Axis(fig[row, col],\n              xlabel = \"X1\", ylabel = \"Estimated CATE\",\n              title = lab)\n    scatter!(ax, X[:, 1], pred, color = (:steelblue, 0.2), markersize = 4)\n    lines!(ax, 0:0.01:1, x -> 1 + 2x, color = :firebrick, linestyle = :dash,\n           linewidth = 2)\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n![Estimated CATE vs true τ(x) = 1 + 2 X₁ for each meta-learner. Red dashed line = ground truth.](heterogeneous-effects_files/figure-pdf/compare-plot-output-1.png){#compare-plot fig-pos='H'}\n:::\n:::\n\n\n## Best Linear Projection (BLP)\n\nEven if CATE is nonlinear, we often want a regression-style summary: which\ncovariates are associated with larger effects? The best linear projection is\nthe OLS regression of pseudo-outcomes on covariates:\n\n$$\n(\\beta_0^*, \\beta^*) = \\arg\\min_{\\beta_0, \\beta} \\mathbb{E}\\left[(\\tau(X) - \\beta_0 - X'\\beta)^2\\right],\n\\qquad \\text{BLP}(X) = \\beta_0^* + X'\\beta^*.\n$$ {#eq-heterogeneous-effects-4}\n\nThe $\\arg\\min$ returns the coefficient vector $(\\beta_0^*, \\beta^*)$;\nthe best linear projection itself is the fitted function\n$\\beta_0^* + X'\\beta^*$.\n\nA doubly-robust BLP uses the DR-learner pseudo-outcomes:\n\n::: {.cell cache='true' execution_count=11}\n``` {.julia .cell-code}\nblp_df = DataFrame(hcat(pseudo_DR, X), [:tau_pseudo, :X1, :X2, :X3, :X4, :X5])\nblp_fit = lm(@formula(tau_pseudo ~ X1 + X2 + X3 + X4 + X5), blp_df)\n\n# `display`, not `println`. StatsBase defines only\n# show(io, ::MIME\"text/plain\", ::CoefTable), so println() falls through to the\n# generic struct show and prints the raw constructor -- `CoefTable(Any[[...]])`\n# -- instead of the formatted table.\ndisplay(coeftable(blp_fit))\n```\n\n::: {#blp .cell-output .cell-output-display .cell-output-markdown}\n|             |      Coef. | Std. Error |     t | Pr(>|t|) | Lower 95% | Upper 95% |\n|:------------|-----------:|-----------:|------:|:---------|:----------|----------:|\n| (Intercept) |  1.03165   |   0.135462 |  7.62 |   <1e-13 |  0.76609  |  1.29722 |\n| X1          |  2.05583   |   0.116642 | 17.63 |   <1e-66 |  1.82716  |  2.28449 |\n| X2          | -0.0285376 |   0.117208 | -0.24 |   0.8076 | -0.258318 |  0.201242 |\n| X3          | -0.0205871 |   0.118377 | -0.17 |   0.8619 | -0.252657 |  0.211483 |\n| X4          | -0.0204671 |   0.118625 | -0.17 |   0.8630 | -0.253025 |  0.212091 |\n| X5          |  0.0117126 |   0.118624 |  0.10 |   0.9214 | -0.220842 |  0.244268 |\n:::\n:::\n\n\nHere the coefficient on $X_1$ should be close to 2, and the coefficients on\nthe other variables should be close to 0.\n\n## GATES: sorted group ATEs\n\nGATES (group average treatment effects) is a simple way to report\nheterogeneity [@chernozhukov-2018-generic-ml]. Sort observations by\npredicted CATE, split them into bins, and estimate the ATE in each bin.\n(The same paper's CLAN — classification analysis — is the natural\ncompanion: compare average *covariates* between the most- and\nleast-affected bins; here that would show high $X_1$ in the top quintile.)\n\n::: {#clan .cell cache='true' execution_count=12}\n``` {.julia .cell-code}\nnq = 5\n\n# The ranking score MUST be out-of-fold, which `tau_DR` now is (it comes from\n# `rf_oof`). This is not a technicality. When this chapter ranked on an in-sample\n# forest prediction -- fit on (X, pseudo_DR) and predicted back at the same X --\n# the bins sorted on pseudo_DR's own noise and then averaged that same noise, so\n# the top bin collected positive noise and the bottom bin negative noise. The\n# table ran from -1.22 to 5.28, entirely outside the true CATE range of [1, 3],\n# with tight confidence intervals around impossible values.\ntau_rank = tau_DR   # already out-of-fold, from rf_oof above\n\nquintile_edges = quantile(tau_rank, range(0, 1, length = nq + 1))\nquintiles      = searchsortedfirst.(Ref(quintile_edges), tau_rank) .- 1\nquintiles      = clamp.(quintiles, 1, nq)\n\n# AIPW-style ATE within each quintile using the DR pseudo-outcomes\nfunction quintile_ate(tau_pseudo, idx)\n    n_q = sum(idx)\n    est = mean(tau_pseudo[idx])\n    sd  = std(tau_pseudo[idx]) / sqrt(n_q)\n    return (est = est, se = sd)\nend\n\nclan_df = DataFrame(quintile = 1:nq,\n                    ATE = [quintile_ate(pseudo_DR, quintiles .== q).est for q in 1:nq],\n                    SE  = [quintile_ate(pseudo_DR, quintiles .== q).se  for q in 1:nq],\n                    # This is a simulation, so report the true within-bin average of\n                    # tau alongside the estimate. It makes the table self-checking:\n                    # every entry must lie in [1, 3] here, and Truth is the column to\n                    # compare ATE against.\n                    Truth = [mean(tau[quintiles .== q]) for q in 1:nq])\nclan_df.lo = clan_df.ATE .- 1.96 .* clan_df.SE\nclan_df.hi = clan_df.ATE .+ 1.96 .* clan_df.SE\n\n@printf(\"%-9s %8s %7s %8s %8s %8s\\n\", \"Quintile\", \"ATE\", \"SE\", \"95% LB\", \"95% UB\", \"Truth\")\nfor row in eachrow(clan_df)\n    @printf(\"%-9d %8.3f %7.3f %8.3f %8.3f %8.3f\\n\",\n            row.quintile, row.ATE, row.SE, row.lo, row.hi, row.Truth)\nend\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nQuintile       ATE      SE   95% LB   95% UB    Truth\n1            1.350   0.075    1.204    1.497    1.393\n2            1.602   0.081    1.443    1.760    1.620\n3            2.220   0.081    2.061    2.379    2.041\n4            2.417   0.074    2.273    2.561    2.388\n5            2.612   0.075    2.464    2.759    2.604\n```\n:::\n:::\n\n\nQuintile 5 has a larger ATE than quintile 1, and because the ranking score is\nout-of-fold the magnitudes are trustworthy too: compare the `ATE` column against\n`Truth`, the actual within-bin average of $\\tau(x) = 1 + 2X_1$. Both halves of the\nprocedure --- forming the groups and estimating the group means --- now use\npredictions from models that did not see the observation being scored, since\n`pseudo_DR` is built from cross-fitted nuisances and `tau_DR` comes from `rf_oof`.\n\nDo not expect the intervals to have exact nominal coverage even so, and the table\nshows why it is useful to print `Truth`: the reported standard errors treat the bin\nmembership as fixed, when in fact the *boundaries* were estimated from the same data,\nand they take no account of the uncertainty in `tau_DR` itself. One quintile here has\na truth just outside its interval, which is about what that omission would predict.\nThe estimates are close enough to be read as a heterogeneity profile; the intervals\nare indicative rather than exact. For inference you would want the groups formed on a\ngenuinely held-out split, or `grf`'s `rank_average_treatment_effect`.\n\nThis is worth insisting on because the failure is silent. Ranking on an\nin-sample score leaves the group means unbiased *on average* --- they still\naverage to the ATE --- while making the spread meaningless, so nothing in the\noutput looks wrong except the numbers themselves. A useful habit is to sanity-check\ngroup ATEs against the range the estimand can possibly take: here every quintile\nmean must lie in $[1, 3]$, and a table with a negative bottom bin is refuted\nbefore you read its standard errors.\n\n## Variable importance — which covariate drives heterogeneity?\n\nA simple diagnostic is to regress the DR pseudo-outcome on each covariate\nseparately and compare $R^2$. It answers a different question from the BLP, and\nthe two are easy to run together and confuse.\n\nThe BLP is a *joint* projection with inference attached. Its target,\n@eq-heterogeneous-effects-4, is defined without reference to any fitted object:\nit is the best linear approximation to $\\tau(x)$ using all covariates at once, it\ncomes in the units of the outcome, it has a sign, and `coeftable` gives it a\nstandard error we can test against zero. The importance measure below is\n*marginal* and descriptive: one univariate $R^2$ per covariate, with no units, no\nsign, and no standard error.\n\nThe difference that matters in practice is joint versus marginal. A covariate\nthat is merely correlated with the true effect modifier picks up a high\nunivariate $R^2$, because on its own it does predict the pseudo-outcome, while\nits BLP coefficient is near zero once the real modifier is in the regression.\nThe projection splits shared variation between correlated covariates; the\nmarginal measure gives each of them full credit for it. Here the five covariates\nare drawn independently, so the two agree.\n\nBoth share one blind spot worth naming, since it is not obvious: this importance\nmeasure is itself a *linear* fit, so a covariate that modifies the effect\nnon-monotonically — large effects at both ends of its range, small in the middle\n— scores near zero on both the BLP and the $R^2$. A tree-based importance of the\nkind `grf` reports would flag it, because trees can split on it. Neither\ndiagnostic here can.\n\n::: {#var-importance .cell cache='true' execution_count=13}\n``` {.julia .cell-code}\nfunction single_var_r2(target, x)\n    df_one = DataFrame(t = target, x = x)\n    fit = lm(@formula(t ~ x), df_one)\n    1 - sum(abs2.(residuals(fit))) / sum(abs2.(target .- mean(target)))\nend\n\nvi = [single_var_r2(pseudo_DR, X[:, j]) for j in 1:p]\nvi_df = DataFrame(variable = [\"X$j\" for j in 1:p], R2 = vi)\nsort!(vi_df, :R2, rev = true)\nprintln(vi_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n5×2 DataFrame\n Row │ variable  R2         \n     │ String    Float64    \n─────┼──────────────────────\n   1 │ X1        0.0585715\n   2 │ X4        2.32397e-5\n   3 │ X5        1.20668e-5\n   4 │ X2        2.02436e-6\n   5 │ X3        5.36056e-7\n```\n:::\n:::\n\n\n$X_1$ should be the most important variable in this simulation.\n\n## Policy learning: who should we treat?\n\nA CATE estimate is not yet a policy. If treatment has a cost, the policy\nquestion is who should be treated. Define a treatment cost $c$ in outcome\nunits:\n\n$$\n\\pi^*(x) = \\mathbb{1}\\{\\tau(x) > c\\}.\n$$ {#eq-heterogeneous-effects-5}\n\nFor interpretability, we can restrict the policy to a single threshold rule.\n\n::: {#policy .cell cache='true' execution_count=14}\n``` {.julia .cell-code}\n# cost = 2 makes the problem non-degenerate: tau(x) = 1 + 2 x1 is in [1, 3],\n# so the optimal rule is \"treat iff x1 > 0.5\" (about half the population).\n# A cost below 1 would make treat-everyone optimal and there would be\n# nothing for a policy to learn.\ncost = 2.0\n\n# Welfare of a rule = average gain over treating nobody, evaluated with the\n# DR scores: mean over units of treat(x) * (pseudo_DR - cost)\nwelfare(treat) = mean(treat .* (pseudo_DR .- cost))\n\nwelfare_all  = welfare(trues(n))            # treat everyone\ntreat_est    = tau_DR .> cost               # rule from the ESTIMATED CATE\ntreat_true   = tau .> cost                  # oracle rule (simulation only)\n\n# Simple threshold-rule family on X1\nthreshes = 0:0.05:1\nwelfares = [welfare(X[:, 1] .> t) for t in threshes]\nbest_t   = threshes[argmax(welfares)]\n\n@printf(\"Treatment rates: estimated rule %.2f, oracle rule %.2f\\n\",\n        mean(treat_est), mean(treat_true))\n@printf(\"Welfare (treat everyone):                    %.3f\\n\", welfare_all)\n@printf(\"Welfare (oracle rule τ(x) > %.0f):            %.3f\\n\", cost, welfare(treat_true))\n@printf(\"Welfare (best X1-threshold rule, X1 > %.2f): %.3f\\n\",\n        best_t, maximum(welfares))\n@printf(\"Welfare (τ̂-rule, SAME scores, biased):       %.3f\\n\", welfare(treat_est))\n@printf(\"Welfare (τ̂-rule, evaluated on true τ):       %.3f\\n\",\n        mean(treat_est .* (tau .- cost)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTreatment rates: estimated rule 0.53, oracle rule 0.51\nWelfare (treat everyone):                    0.040\nWelfare (oracle rule τ(x) > 2):            0.300\nWelfare (best X1-threshold rule, X1 > 0.45): 0.301\nWelfare (τ̂-rule, SAME scores, biased):       0.261\nWelfare (τ̂-rule, evaluated on true τ):       0.215\n```\n:::\n:::\n\n\nThe threshold rule gives up flexibility, but it is easy to explain — and it\nrecovers the oracle threshold of $0.5$ almost exactly.\n\nOne number above deserves a warning. The $\\hat\\tau$-rule \"evaluated\" with the\nsame DR scores that selected it appears to beat even the oracle rule — which\nis impossible in expectation. Selecting units whose noisy score is high and\nthen averaging those same scores is optimistic by construction. In a\nsimulation we can evaluate the rule against the true $\\tau(x)$ instead (the\nlast line): the honest value is positive — better than treating everyone —\nbut well below the oracle, because the noisy CATE estimates misclassify many\nunits near the threshold. Both lessons matter: never evaluate a rule on the\nscores that chose it (in real data, estimate the rule and evaluate its\nwelfare on separate folds), and do not expect an estimated rule to attain\noracle welfare. Here the simple $X_1$-threshold rule, which searches a small\none-dimensional family, gets essentially the oracle value — restricting the\npolicy class is a form of regularisation.\n\nFor more on policy trees with IPW and AIPW losses (using\nR's `policytree` package), see the\n[companion blog chapter on `policytree`](https://xiangao.github.io/blog_book/policytree.html).\nFor a cross-software comparison of CATE estimators (including Stata 19's\nnew `cate` command), see the\n[Stata CATE blog chapter](https://xiangao.github.io/blog_book/stata-cate.html).\n\n## Causal forests with panel data\n\nWith panel data, unit effects can be correlated with treatment and\ncovariates. A cross-sectional meta-learner can then be biased. The fixed\neffect adjustment is to demean by unit before applying the learner.\n\n::: {#panel-dgp .cell cache='true' execution_count=15}\n``` {.julia .cell-code}\nRandom.seed!(2024)\nn_firms = 200\nn_t     = 5\nN       = n_firms * n_t\n\nfirm_id  = repeat(1:n_firms, inner = n_t)\nunit_fe  = randn(n_firms) .* 1.5\nV1_firm  = randn(n_firms) .* 1.0\nV1_panel = V1_firm[firm_id] .+ 0.3 .* randn(N)\n# The unit effect drives BOTH treatment and the outcome (classic\n# fixed-effect confounding); unit_fe is unobserved to the learner.\nW_panel  = Float64.(rand(N) .<\n           @. 1 / (1 + exp(-(0.3 * V1_firm[firm_id] + 0.5 * unit_fe[firm_id]))))\ntau_panel = @. 0.5 + 1.0 * V1_panel\nY_panel  = unit_fe[firm_id] .+ V1_panel .+ tau_panel .* W_panel .+ randn(N)\n\ndf_panel = DataFrame(firm = firm_id, V1 = V1_panel, W = W_panel, Y = Y_panel)\n# Y(1) - Y(0) = tau_panel exactly, so the true ATE is mean(tau_panel).\ntrue_panel_ate = mean(tau_panel)\n@printf(\"True panel ATE: %.3f\\n\", true_panel_ate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTrue panel ATE: 0.655\n```\n:::\n:::\n\n\nA naive T-learner ignores the firm fixed effects. Because `unit_fe` raises\nboth the treatment probability and the outcome, and is not in the learner's\ncovariates, the naive estimate is badly biased upward:\n\n::: {#panel-naive .cell cache='true' execution_count=16}\n``` {.julia .cell-code}\nX_panel_naive = reshape(df_panel.V1, N, 1)\nidx_T_p = df_panel.W .== 1\nidx_C_p = df_panel.W .== 0\n\n# Note these panel fits are in-sample, unlike the meta-learners above. Splitting\n# out-of-fold here would have to split by *firm* rather than by row, since two\n# observations of the same firm are not independent. The comparison this section\n# makes -- naive against within-transformed -- is driven by fixed-effect\n# confounding, which is far larger than any in-sample optimism, so the point\n# survives; do not read these two numbers as clean CATE accuracy figures.\nmu1_naive = rf_fit_predict(X_panel_naive[idx_T_p, :], df_panel.Y[idx_T_p],\n                            X_panel_naive)\nmu0_naive = rf_fit_predict(X_panel_naive[idx_C_p, :], df_panel.Y[idx_C_p],\n                            X_panel_naive)\ntau_naive = mu1_naive .- mu0_naive\n\n@printf(\"Naive panel T-learner ATE: %.3f  (true = %.3f)\\n\",\n        mean(tau_naive), true_panel_ate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNaive panel T-learner ATE: 2.014  (true = 0.655)\n```\n:::\n:::\n\n\nThe within transformation removes firm-level variation and leaves the\nwithin-firm variation:\n\n::: {#panel-within .cell cache='true' execution_count=17}\n``` {.julia .cell-code}\n# Within transformation: subtract firm means\ndf_dm = combine(groupby(df_panel, :firm),\n                :Y  => (y -> y .- mean(y)) => :Y_dm,\n                :W  => (w -> w .- mean(w)) => :W_dm,\n                :V1 => (v -> v .- mean(v)) => :V1_dm)\n\nX_dm = reshape(df_dm.V1_dm, N, 1)\nidx_T_dm = df_dm.W_dm .> 0\nidx_C_dm = df_dm.W_dm .<= 0\n\nmu1_dm = rf_fit_predict(X_dm[idx_T_dm, :], df_dm.Y_dm[idx_T_dm], X_dm)\nmu0_dm = rf_fit_predict(X_dm[idx_C_dm, :], df_dm.Y_dm[idx_C_dm], X_dm)\ntau_dm = mu1_dm .- mu0_dm\n\n# The two demeaned groups differ in W_dm by less than a full 0 -> 1 switch\n# (treated-above-average vs below-average within firm), so the raw contrast\n# is attenuated; rescale by the W_dm gap, as in a Wald estimator.\nw_gap = mean(df_dm.W_dm[idx_T_dm]) - mean(df_dm.W_dm[idx_C_dm])\n@printf(\"Within-transform T-learner ATE: %.3f  (true = %.3f)\\n\",\n        mean(tau_dm) / w_gap, true_panel_ate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWithin-transform T-learner ATE: 0.689  (true = 0.655)\n```\n:::\n:::\n\n\nThe within transformation removes the fixed effects, and the rescaled\ncontrast lands near the truth in this DGP. The cost is variance, because\nidentification now comes from within-firm variation.\n\nA caveat on what this estimator targets. Splitting on $W_{dm} > 0$ vs\n$W_{dm} \\le 0$ and dividing the T-learner contrast by the average\n$W_{dm}$ gap is *not* a general fixed-effect CATE estimator. It is a\nheuristic within-firm contrast whose target depends on the distribution\nof demeaned treatment values and on the grouping rule, and the rescaling\nis a Wald-style approximation rather than an identified within estimand.\nIt works here because the treatment effect is linear in $V_1$ and the\nDGP is benign. Properly identified heterogeneous panel effects require a\nproper orthogonal score or a dedicated panel causal-forest / DML\nconstruction; treat this section as intuition, not a turnkey method.\n\nSo how much does ignoring the panel cost? On this DGP the naive T-learner returns\n2.014 against a true panel ATE of 0.655 — about three times the truth — while the\nwithin transform recovers 0.689. The magnitude is specific to this design, since\nit scales with how strongly the unit effect drives both treatment and outcome,\nbut the direction is not: a unit effect that raises both leaves the naive\nestimate biased upward. Read those two numbers as the size of the confounding\nbeing removed, not as clean CATE accuracy figures, for the estimand reasons given\njust above.\n\nFor R's `grf::causal_forest`, pass `clusters = firm_id` so the honest sample\nsplit keeps each firm's observations together. Julia does not currently have\nan equivalent; see the\n[companion blog chapter on causal forests in panel data](https://xiangao.github.io/blog_book/causal-forest-panel.html)\nand the [R companion to this chapter](https://xiangao.github.io/causal_econometrics_guide/heterogeneous-effects.html)\nfor the GRF-based workflow.\n\n## Summary\n\n- Meta-learners turn regression tools into CATE estimators.\n- In Julia they can be built with `MLJ` random forests, but there is no full\n  `grf` equivalent yet.\n- BLP and GATES summarize heterogeneity in regression-style output.\n- Policy learning turns CATE estimates into treatment rules.\n- In applied work, compare at least two CATE estimators and report simple\n  heterogeneity summaries, not only a CATE scatterplot.\n\n",
    "supporting": [
      "heterogeneous-effects_files/figure-pdf"
    ],
    "filters": []
  }
}