{
  "hash": "cfefbbbfdd034887231fc6389acca57c",
  "result": {
    "engine": "jupyter",
    "markdown": "# Nonparametric Causal Methods\n\n\n::: {#bac558b6 .cell execution_count=2}\n``` {.julia .cell-code}\nusing DataFrames\nusing Distributions\nusing Random\nusing Statistics\nusing MLJ\nusing EvoTrees\nusing MLJLinearModels\nusing DecisionTree\nusing CausalEstimate\nimport CausalEstimate: estimate, confint, pvalue\nusing Printf\n```\n:::\n\n\n> **Related reading**: For an R-based TMLE simulation that compares\n> super-learner libraries and stress-tests model misspecification, see\n> the [companion blog chapter on TMLE](https://xiangao.github.io/blog_book/tmle.html)\n> in *Topics on Econometrics and Causal Inference*.\n\n## Why Do We Need Nonparametric Methods?\n\n-   Parametric models are often mis-specified\n-   Nonparametric models are more flexible; less assumptions\n-   What kind of nonparametrics are good?\n\nConsiderations:\n\n-   Plug-in (g-computation) estimators are easy.\n-   The problem is not the decomposition into $E[Y(0)]$ and $E[Y(1)]$ itself: with correctly specified models and regularity, a plug-in estimator can be efficient. The problem appears once the nuisance models are flexible and regularised. Then the error in the nuisance estimate enters the plug-in target *linearly*, and the plug-in has no term that cancels it. An influence-function estimator adds exactly such a term, and the error that survives is a product of two nuisance errors rather than one. @sec-plug-in-bias does the algebra.\n-   So they can be consistent, but the convergence rate inherits the (often slow) nuisance rate, which is especially bad in high dimensions.\n-   Ideally we remove that first-order sensitivity using an orthogonal influence function, and get $\\sqrt n$ efficiency.\n-   Influence-function-based (one-step/AIPW/TMLE) estimators are shown to be efficient and orthogonal to first-order nuisance error.\n\n## Influence Function Based Estimators\n\nEstimators based on efficient influence function are often $\\sqrt n$ consistent, meaning they converge to the truth as fast as $\\sqrt n$ rate. This means the bias not only goes to 0 with $n$ goes to infinity, but also as fast as $1/ \\sqrt n$ goes to 0. Why does this matter? Because we have limited sample size, when we are based on asymptotics, the faster the bias goes to 0 the smaller sample size we need.\n\nIf we have an estimator such that $$ \\sqrt n (\\hat \\psi - \\psi) = \\sqrt n P_n(\\phi) + o_P(1) \\rightarrow N(0, var(\\phi))$$ {#eq-nonparametric-1}\n\nThen this estimator is $\\sqrt n$ consistent and asymptotically normal; and $\\phi$ is the influence function. The efficient influence function is the one with variance at the lower bound (similar to parametric case for Cramer-Rao lower bound).\n\nUnfortunately there is no universal formula for efficient influence function for every problem. We need to derive it for each problem. For example, ATE has an IF based estimator, but ATT needs a different formula; and LATE has a different formula too, etc. Deriving them is hard!\n\nFor the treated potential-outcome mean, $\\psi_1 = E\\{E(Y \\mid X, A=1)\\}$, the efficient influence function is $$\\phi_1 (Z; P) = \\frac{A}{\\pi (X)} \\{ Y - \\mu_1 (X) \\} + \\mu_1(X) - \\psi_1$$ {#eq-nonparametric-2} where $\\pi (X) = P(A=1 | X)$ is the propensity score model and $\\mu_1 (X) = E(Y |X, A=1)$ is the treated outcome model. The ATE influence function is the difference between the treated and untreated components, $\\phi_1-\\phi_0$.\n\nFor example, an IF-based bias-corrected estimator for the treated-arm mean $$\\hat \\psi_1 = P_n \\left[ \\frac{A}{\\hat \\pi (X)} \\{ Y - \\hat \\mu_1 (X) \\} + \\hat \\mu_1(X) \\right]$$ {#eq-nonparametric-3} where $P_n$ means sample mean. This is the familiar AIPW estimator. It is known to be doubly robust.\n\nSince we know the influence function, we can calculate its variance. This variance is the same as variance of $\\hat \\psi$ since they differ by a constant $\\psi$. We can use any estimators to estimate the nuisance parameters, then get $\\hat \\psi$. Then the sample variance is the variance of the influence function; and the sample mean is the ATE.\n\nIn this estimator, both $\\hat \\mu$ and $\\hat \\pi$ can be done using any estimator, such as machine learning. One caveat: with adaptive learners (random forests, boosting), the nuisance fits should be *cross-fit* — predicted for each observation from a model trained without it — otherwise own-observation overfitting can bias the estimate. The manual AIPW below reuses full-sample fits to keep the code short; the `CausalEstimate.jl` calls use `crossfit=5`.\n\n### Why the Plug-In Is Off {#sec-plug-in-bias}\n\nThe bullets above claimed that the plug-in inherits the nuisance error at first\norder and that the augmentation term removes it. That is algebra, not a\nsimulation finding, so it is worth doing before we run anything.\n\nTake $\\psi_1 = E[\\mu_1(X)]$ with $\\mu_1(x) = E(Y \\mid X = x, A = 1)$. The plug-in\nestimator is $\\hat\\psi_1^{\\,\\text{pi}} = P_n[\\hat\\mu_1(X)]$. Split its error into\na sampling part and a nuisance part:\n\n$$\n\\hat\\psi_1^{\\,\\text{pi}} - \\psi_1\n= \\underbrace{(P_n - P)[\\mu_1]}_{O_P(n^{-1/2})}\n\\; + \\; \\underbrace{P[\\hat\\mu_1 - \\mu_1]}_{\\text{nuisance error, linear}}\n\\; + \\; \\underbrace{(P_n - P)[\\hat\\mu_1 - \\mu_1]}_{\\text{smaller still}} .\n$$ {#eq-nonparametric-plugin}\n\nThe middle term is $E[\\hat\\mu_1(X) - \\mu_1(X)]$, and it is linear in the nuisance\nerror. If $\\hat\\mu_1$ converges at rate $n^{-\\alpha}$, that term is of order\n$n^{-\\alpha}$, and a regularised learner in even a moderate number of dimensions\ngives $\\alpha < 1/2$. The nuisance error then dominates the sampling error, the\nestimator is not $\\sqrt n$ consistent, and nothing in the plug-in cancels it.\n\nNow do the same for the AIPW estimator of @eq-nonparametric-3. Evaluate it under\nthe population distribution, holding the estimated nuisances fixed. Because\n$E[A\\{Y - \\hat\\mu_1(X)\\} \\mid X] = \\pi(X)\\{\\mu_1(X) - \\hat\\mu_1(X)\\}$,\n\n$$\nP\\Bigl[\\frac{A}{\\hat\\pi(X)}\\bigl\\{Y - \\hat\\mu_1(X)\\bigr\\} + \\hat\\mu_1(X)\\Bigr]\n= \\psi_1 + E\\Bigl[\\frac{\\pi(X) - \\hat\\pi(X)}{\\hat\\pi(X)}\\,\n                  \\bigl\\{\\mu_1(X) - \\hat\\mu_1(X)\\bigr\\}\\Bigr].\n$$ {#eq-nonparametric-drift}\n\nThe bias is a *product* of the two nuisance errors, and that is the entire\ndifference between the two estimators. The term linear in $\\hat\\mu_1 - \\mu_1$ has\ncancelled: the $\\hat\\mu_1$ that the outcome model carries in is subtracted back\nout by the $\\hat\\mu_1$ sitting inside the augmentation, and what survives is\nmultiplied by the propensity-score error. By Cauchy-Schwarz the bias is bounded\nby $\\lVert \\pi - \\hat\\pi \\rVert \\, \\lVert \\mu_1 - \\hat\\mu_1 \\rVert$ up to the\noverlap constant, so rates of $o(n^{-1/4})$ on each nuisance suffice to make it\n$o(n^{-1/2})$ --- slower than $\\sqrt n$ on each piece, fast enough for $\\sqrt n$\non the target.\n\nTwo familiar facts fall out of @eq-nonparametric-drift directly. Double\nrobustness is immediate: if either factor is zero the whole bias is zero, which\nis why one correct model is enough. And the $n^{-1/4}$ requirement is the reason\ncross-fitting matters, since reusing the same observations to fit and to evaluate\n$\\hat\\mu_1$ makes the product term behave worse than the rate calculation\nassumes.\n\n### Simulation Setup\n\n::: {#6fa429c5 .cell cache='true' message='false' execution_count=3}\n``` {.julia .cell-code}\nRandom.seed!(1)\nn = 1000\nw1 = rand(Binomial(1, 0.5), n)\nw2 = rand(Binomial(1, 0.5), n)\nw3 = round.(rand(Uniform(0, 4), n), digits=3)\nw4 = round.(rand(Uniform(0, 5), n), digits=3)\n\nlogistic(x) = 1.0 ./ (1.0 .+ exp.(-x))   # inverse logit (sigmoid), not the logit\n\nprob_A = logistic.(-0.4 .+ 0.2.*w2 .+ 0.15.*w3 .+ 0.2.*w4 .+ 0.15.*w2.*w4)\nA = rand.(Binomial.(1, prob_A))\n\nprob_Y1 = logistic.(-1.0 .+ 1.0 .- 0.1.*w1 .+ 0.3.*w2 .+ 0.25.*w3 .+ 0.2.*w4 .+ 0.15.*w2.*w4)\nprob_Y0 = logistic.(-1.0 .+ 0.0 .- 0.1.*w1 .+ 0.3.*w2 .+ 0.25.*w3 .+ 0.2.*w4 .+ 0.15.*w2.*w4)\n\nY_1 = rand.(Binomial.(1, prob_Y1))\nY_0 = rand.(Binomial.(1, prob_Y0))\nY = Y_1 .* A .+ Y_0 .* (1 .- A)\n\nW = DataFrame(w1=w1, w2=w2, w3=w3, w4=w4)\ndf = DataFrame(w1=w1, w2=w2, w3=w3, w4=w4, A=A, Y=Y, Y_1=Y_1, Y_0=Y_0)\n\nTrue_Psi = mean(df.Y_1 .- df.Y_0)\n@printf \"True ATE = %.4g\\n\" True_Psi\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTrue ATE = 0.184\n```\n:::\n:::\n\n\nThe line above reports `mean(Y.1 - Y.0)` for this particular draw. That is a\nlegitimate quantity --- the *sample* average treatment effect --- but it is not a\nfixed benchmark, and it is easy to mistake for one. The potential outcomes are\nbinary, so at $n = 1000$ this realized average has a sampling standard deviation\nof about 0.020: two runs of the same DGP under different seeds can differ by 0.04\nwithout anything being wrong. (The R and Julia editions of this chapter print\n0.21 and 0.184 for exactly this reason.) Estimator standard errors in this\nchapter are around 0.03, so a noisy target of that size would swamp the\ncomparison we are trying to make.\n\nThe *population* ATE is a definite number, and since the DGP is fully specified\nwe can integrate it out rather than simulate it:\n\n::: {#2e688429 .cell cache='true' message='false' execution_count=4}\n``` {.julia .cell-code}\n# w1, w2 ~ Bernoulli(0.5); w3 ~ U(0,4); w4 ~ U(0,5). Average the true individual\n# effect over that covariate distribution on a trapezoid grid.\nfunction population_ate()\n    g3 = range(0, 4; length = 1601)\n    g4 = range(0, 5; length = 1601)\n    trap(g) = (w = fill(step(g), length(g)); w[1] /= 2; w[end] /= 2; w)\n    w3w, w4w = trap(g3), trap(g4)\n    total = 0.0\n    for w1 in (0, 1), w2 in (0, 1)\n        acc = 0.0\n        for (j, u4) in enumerate(g4), (i, u3) in enumerate(g3)\n            lin0 = -1 - 0.1w1 + 0.3w2 + 0.25u3 + 0.2u4 + 0.15w2 * u4\n            acc += w3w[i] * w4w[j] * (logistic(lin0 + 1) - logistic(lin0))\n        end\n        total += acc / (4 * 5)\n    end\n    total / 4\nend\n\npop_ate = population_ate()\n@printf \"Realized-sample ATE (this draw): %.4f\\n\" True_Psi\n@printf \"Exact population ATE:           %.4f\\n\" pop_ate\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRealized-sample ATE (this draw): 0.1840\nExact population ATE:           0.2028\n```\n:::\n:::\n\n\nCompare the estimators below against 0.2028, not against the realized draw.\n\n::: {#9321597c .cell cache='true' message='false' execution_count=5}\n``` {.julia .cell-code}\n# Load MLJ models to form our equivalent of SuperLearner\nLogisticClassifier = @load LogisticClassifier pkg=MLJLinearModels verbosity=0\nEvoTreeClassifier = @load EvoTreeClassifier pkg=EvoTrees verbosity=0\nRandomForestClassifier = @load RandomForestClassifier pkg=DecisionTree verbosity=0\n\n# Define a Stack (SuperLearner)\nstack = Stack(\n    metalearner = LogisticClassifier(),\n    resampling = CV(nfolds=5),\n    evo = EvoTreeClassifier(max_depth=4, nrounds=100),\n    rf = RandomForestClassifier(n_trees=100, max_depth=5),\n    glm = LogisticClassifier()\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\nProbabilisticStack(\n  metalearner = LogisticClassifier(\n        lambda = 2.220446049250313e-16, \n        gamma = 0.0, \n        penalty = :l2, \n        fit_intercept = true, \n        penalize_intercept = false, \n        scale_penalty_with_samples = true, \n        solver = nothing), \n  resampling = CV(\n        nfolds = 5, \n        shuffle = false, \n        rng = TaskLocalRNG()), \n  measures = nothing, \n  cache = true, \n  acceleration = CPU1{Nothing}(nothing), \n  evo = EvoTreeClassifier(\n        loss = :mlogloss, \n        metric = :mlogloss, \n        nrounds = 100, \n        bagging_size = 1, \n        early_stopping_rounds = 9223372036854775807, \n        L2 = 1.0, \n        lambda = 0.0, \n        gamma = 0.0, \n        eta = 0.1, \n        max_depth = 4, \n        min_weight = 1.0, \n        rowsample = 1.0, \n        colsample = 1.0, \n        nbins = 64, \n        tree_type = :binary, \n        seed = 123, \n        device = :cpu), \n  rf = RandomForestClassifier(\n        max_depth = 5, \n        min_samples_leaf = 1, \n        min_samples_split = 2, \n        min_purity_increase = 0.0, \n        n_subfeatures = -1, \n        n_trees = 100, \n        sampling_fraction = 0.7, \n        feature_importance = :impurity, \n        rng = TaskLocalRNG()), \n  glm = LogisticClassifier(\n        lambda = 2.220446049250313e-16, \n        gamma = 0.0, \n        penalty = :l2, \n        fit_intercept = true, \n        penalize_intercept = false, \n        scale_penalty_with_samples = true, \n        solver = nothing))\n```\n:::\n:::\n\n\n### Plug-in Estimator from Outcome Regression\n\n::: {#30572ebb .cell cache='true' message='false' execution_count=6}\n``` {.julia .cell-code}\nRandom.seed!(1)\nX_mu = select(df, :w1, :w2, :w3, :w4, :A)\nmach_mu = machine(stack, X_mu, categorical(df.Y))\nMLJ.fit!(mach_mu, verbosity=0)\n\n# predict the PO Y^1\nX_mu1 = copy(X_mu); X_mu1.A .= 1\nX_mu0 = copy(X_mu); X_mu0.A .= 0\n\n# Predict probability of Y=1 (assuming 1 is the positive class)\nmu1hat = pdf.(MLJ.predict(mach_mu, X_mu1), 1)\nmu0hat = pdf.(MLJ.predict(mach_mu, X_mu0), 1)\n\nplug_in_ate = mean(mu1hat .- mu0hat)\n@printf \"ATE (plug-in) = %.4g\\n\" plug_in_ate\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nATE (plug-in) = 0.1759\n```\n:::\n:::\n\n\n### AIPW ATE\n\n::: {#0bdfa85e .cell cache='true' message='false' execution_count=7}\n``` {.julia .cell-code}\nRandom.seed!(123)\nX_pi = select(df, :w1, :w2, :w3, :w4)\nmach_pi = machine(stack, X_pi, categorical(df.A))\nMLJ.fit!(mach_pi, verbosity=0)\n\npi1hat = pdf.(MLJ.predict(mach_pi, X_pi), 1)\n\n# Bound propensity scores to avoid extreme weights\npi1hat = max.(min.(pi1hat, 0.999), 0.001)\npi0hat = 1.0 .- pi1hat\n\n# Current prediction on observed data\nmu1hat_obs = mu1hat\nmu0hat_obs = mu0hat\n\nIF_1 = ((df.A ./ pi1hat) .* (df.Y .- mu1hat_obs) .+ mu1hat_obs)\nIF_0 = (((1 .- df.A) ./ pi0hat) .* (df.Y .- mu0hat_obs) .+ mu0hat_obs)\nIF = IF_1 .- IF_0\n\naipw_1 = mean(IF_1); aipw_0 = mean(IF_0)\naipw_manual = aipw_1 - aipw_0\n\nci_lb = mean(IF) - quantile(Normal(), 0.975) * std(IF) / sqrt(length(IF))\nci_ub = mean(IF) + quantile(Normal(), 0.975) * std(IF) / sqrt(length(IF))\nres_manual_aipw = [aipw_manual, ci_lb, ci_ub]\n@printf \"ATE (AIPW)   = %.4g\\n\" aipw_manual\n@printf \"95%% CI       = [%.4g, %.4g]\\n\" ci_lb ci_ub\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nATE (AIPW)   = 0.1918\n95% CI       = [0.1311, 0.2525]\n```\n:::\n:::\n\n\n### AIPW ATE Using CausalEstimate.jl\n\n::: {#d30f7994 .cell cache='true' message='false' execution_count=8}\n``` {.julia .cell-code}\nusing CausalEstimate\n\nr(x) = round(x, sigdigits=4)\n\npsi_ate = ATE(outcome=:Y, treatment=:A, confounders=[:w1, :w2, :w3, :w4])\naipw_result = estimate(psi_ate, AIPW(crossfit=5), df)\n\n(\n    ATE    = r(estimate(aipw_result)),\n    CI     = r.(confint(aipw_result)),\n    pvalue = r(pvalue(aipw_result)),\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```\n(ATE = 0.2072, CI = (0.1206, 0.2939), pvalue = 2.776e-6)\n```\n:::\n:::\n\n\n### Regression-imputation ATT (manual)\n\nNote that the manual estimator below is evaluated on the **treated subset** `df1`,\nwhere `(1 .- df1.A)` is identically zero. The augmentation term\n`((1-A)/π₀)(Y-μ₀)` therefore vanishes and the estimator collapses to the\nregression-imputation ATT, `mean(Y_treated − μ̂₀(X_treated))`. That is consistent\nif the control outcome model is correct, but it is **not** the doubly-robust /\naugmented ATT, and the influence-function SE understates uncertainty because it\nignores estimation of `μ₀` and `π`. The proper ATT efficient influence function\n(Hahn 1998) is `(1/p)[A(Y−μ₀) − (1−A)·π/(1−π)·(Y−μ₀)]` evaluated over the **full**\nsample; the `CausalEstimate.jl` call in the next subsection computes the\ncross-fit, doubly-robust version.\n\n::: {#32dc1557 .cell cache='true' message='false' execution_count=9}\n``` {.julia .cell-code}\nRandom.seed!(1)\ndf2 = copy(df)\ndf2.pi0hat = pi0hat\ndf2.pi1hat = pi1hat\n\ndf0 = filter(row -> row.A == 0, df2)\ndf1 = filter(row -> row.A == 1, df2)\n\n# Fit outcome model only on controls\nX_mu0 = select(df0, :w1, :w2, :w3, :w4)\nmach_mu0 = machine(stack, X_mu0, categorical(df0.Y))\nMLJ.fit!(mach_mu0, verbosity=0)\n\n# Predict counterfactual for treated\nX_mu1 = select(df1, :w1, :w2, :w3, :w4)\nmu0hat_treated = pdf.(MLJ.predict(mach_mu0, X_mu1), 1)\n\nIF_0_att = (((1 .- df1.A) ./ df1.pi0hat) .* (df1.Y .- mu0hat_treated) .+ mu0hat_treated)\nIF_att = df1.Y .- IF_0_att\n\naipw_manual_att = mean(IF_att)\nci_lb_att = mean(IF_att) - quantile(Normal(), 0.975) * std(IF_att) / sqrt(length(IF_att))\nci_ub_att = mean(IF_att) + quantile(Normal(), 0.975) * std(IF_att) / sqrt(length(IF_att))\nres_manual_aipw_att = [aipw_manual_att, ci_lb_att, ci_ub_att]\nres_manual_aipw_att\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\n3-element Vector{Float64}:\n 0.20145553037952954\n 0.1700985774823039\n 0.2328124832767552\n```\n:::\n:::\n\n\n### AIPW ATT Using CausalEstimate.jl\n\n::: {#aa0f8d8e .cell cache='true' message='false' execution_count=10}\n``` {.julia .cell-code}\npsi_att = ATT(outcome=:Y, treatment=:A, confounders=[:w1, :w2, :w3, :w4])\natt_result = estimate(psi_att, AIPW(crossfit=5), df)\n\n(\n    ATT    = r(estimate(att_result)),\n    CI     = r.(confint(att_result)),\n    pvalue = r(pvalue(att_result)),\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```\n(ATT = 0.189, CI = (0.06404, 0.3139), pvalue = 0.00303)\n```\n:::\n:::\n\n\n## TMLE\n\nTMLE is a variant of IF based estimator. It is also a doubly robust estimator. See Mark van der Laan and his coauthors for the recent development of TMLE.\n\nWe should expect AIPW and TMLE to give similar answers.\n\n::: {#d7d5fc2e .cell cache='true' message='false' execution_count=11}\n``` {.julia .cell-code}\nRandom.seed!(42)\ntmle_result = estimate(psi_ate, TMLE(crossfit=5), df)\n\n(\n    TMLE   = r(estimate(tmle_result)),\n    CI     = r.(confint(tmle_result)),\n    pvalue = r(pvalue(tmle_result)),\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```\n(TMLE = 0.1775, CI = (0.08638, 0.2687), pvalue = 0.0001349)\n```\n:::\n:::\n\n\n::: {#774e6402 .cell execution_count=12}\n``` {.julia .cell-code}\n@printf \"Population ATE (exact):    %.4f\\n\" pop_ate\n@printf \"Realized-sample ATE:       %.4f\\n\" True_Psi\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPopulation ATE (exact):    0.2028\nRealized-sample ATE:       0.1840\n```\n:::\n:::\n\n\n## DoubleML\n\nDoubleML (Double/Debiased Machine Learning) was proposed by Chernozhukov et al. (2018). An R package `DoubleML` implements the framework; as of this writing there is no native Julia package, but the algorithm is straightforward to implement directly. The double machine learning framework consists of three key ingredients: Neyman orthogonality, high-quality machine learning estimation, and sample splitting.\n\nThey consider a partially linear model:\n\n$$ y_i = \\theta d_i + g_0(x_i) + \\eta_i $$ {#eq-nonparametric-4}\n\n$$ d_i = m_0(x_i) + v_i $$ {#eq-nonparametric-5}\n\nThis model is quite general, except it does not allow interaction of $d$ and $x$; therefore no heterogeneous treatment effect across $x$. But \"DoubleML\" implements more than partially linear model, it actually allows for heterogeneous treatment effects, in models such as interactive regression model.\n\nThe basic idea of doubleML is to use any machine learning algorithm to estimate outcome equation ($l_0(X) = E(Y | X)$) and treatment equation ($m_0(X) = E(D | X)$). Then get the residuals, namely $\\hat W=Y-\\hat l_0(X)$ and $\\hat V = D - \\hat m_0(X)$.\n\nThen regress $\\hat W$ on $\\hat V$. Based on FWL theorem, you get $\\hat \\theta$.\n\nAn important component here is to specify a Neyman-orthogonal score function. The *partialling-out* form, which is what the residual-on-residual regression below implements, is\n\n$$\\psi (W; \\theta, \\eta) = \\big(Y - l(X) - \\theta\\,(D-m(X))\\big)\\,(D-m(X)),$$ {#eq-nonparametric-6}\n\nwith $l(X)=E[Y\\mid X]$ and $m(X)=E[D\\mid X]$. The estimator $\\hat \\theta$ solves the equation that the sample mean of this score function is 0.\n\nThe estimator's variance is the sandwich $J^{-1}\\,E[\\psi^2]\\,J^{-1}$ with Jacobian $J = E[\\partial\\psi/\\partial\\theta] = -E[(D-m(X))^2]$ — this is what the code computes by dividing the score variance by $\\big(\\tfrac1n\\sum \\hat V_i^2\\big)^2$.\n\n::: {#c00df398 .cell cache='true' message='false' execution_count=13}\n``` {.julia .cell-code}\nusing MLJ\nusing Random\n\n# We implement DoubleML PLR (Partially Linear Regression) manually with cross-fitting\nRandom.seed!(123)\nnsplits = 5\nn_samples = nrow(df)\ns = shuffle(1:n_samples)\nfolds = [s[1 + floor(Int, (k-1)*n_samples/nsplits) : floor(Int, k*n_samples/nsplits)] for k in 1:nsplits]\n\n# Base learner (Random Forest for regression)\nRandomForestRegressor = @load RandomForestRegressor pkg=DecisionTree verbosity=0\nlearner = RandomForestRegressor(n_trees=500, max_depth=5)\n\nW_res = zeros(n_samples)\nV_res = zeros(n_samples)\n\nfor fold in 1:nsplits\n    test_idx = folds[fold]\n    train_idx = setdiff(1:n_samples, test_idx)\n    \n    # Fit outcome model l_0(X) = E(Y | X)\n    mach_l = machine(learner, W[train_idx, :], df.Y[train_idx])\n    MLJ.fit!(mach_l, verbosity=0)\n    y_pred = MLJ.predict(mach_l, W[test_idx, :])\n    W_res[test_idx] = df.Y[test_idx] .- y_pred\n    \n    # Fit treatment model m_0(X) = E(D | X)\n    mach_m = machine(learner, W[train_idx, :], df.A[train_idx])\n    MLJ.fit!(mach_m, verbosity=0)\n    a_pred = MLJ.predict(mach_m, W[test_idx, :])\n    V_res[test_idx] = df.A[test_idx] .- a_pred\nend\n```\n:::\n\n\n::: {#e30db817 .cell cache='true' message='false' execution_count=14}\n``` {.julia .cell-code}\n# FWL theorem: regress residual W_res on residual V_res\ntheta_hat = sum(W_res .* V_res) / sum(V_res .^ 2)\n\n# Variance of score function (Neyman-orthogonal score)\npsi = (W_res .- theta_hat .* V_res) .* V_res\nvar_theta = var(psi) / (mean(V_res .^ 2)^2)\nse_theta = sqrt(var_theta / n_samples)\n\nci_lb = theta_hat - 1.96 * se_theta\nci_ub = theta_hat + 1.96 * se_theta\n@printf \"DML PLR Estimate = %.4g (SE = %.4g)\\n\" theta_hat se_theta\n@printf \"95%% CI           = [%.4g, %.4g]\\n\" ci_lb ci_ub\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDML PLR Estimate = 0.192 (SE = 0.03206)\n95% CI           = [0.1292, 0.2549]\n```\n:::\n:::\n\n\n",
    "supporting": [
      "nonparametric_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}