{
  "hash": "9f426e36768dcb1eb9d9ce7affe7f7f4",
  "result": {
    "engine": "jupyter",
    "markdown": "# Difference-in-Differences\n\n\n::: {.cell execution_count=2}\n``` {.julia .cell-code}\nusing DataFrames\nusing DataFramesMeta\nusing Panelest\nusing Vcov\nusing StatsModels\nimport StatsAPI: coeftable\nusing ReadStatTables\nusing CSV\nusing SynthDiD\nusing CairoMakie\nCairoMakie.activate!(type = \"png\")\nusing Statistics\nusing Printf\nusing RegressionTables\nusing Random\nusing Distributions\n```\n:::\n\n\nWhen unconfoundedness fails, we need weaker assumptions. The parallel trends assumption leads to the difference-in-differences estimator.\n\n> **Related reading**: For a side-by-side comparison of DiD, synthetic DiD,\n> synthetic control, and TASC on a *single* panel — the Proposition 99\n> California smoking data, where the four estimators do not agree — see the\n> [Same data, different estimators](https://xiangao.github.io/blog_book/tasc-time-aware-synthetic-control.html)\n> chapter in *Topics on Econometrics and Causal Inference*.\n\n## $T=2$ Panel Data\n\nSuppose we have two periods, $t = (1,2)$. Some units are treated just prior to period 2. For each individual $i$, there are four potential outcomes:\n\n$$ [Y_{i1}(0), Y_{i1}(1), Y_{i2}(0), Y_{i2}(1)] $$ {#eq-did-1}\n\nLet $D$ denote the treated group. The ATT in period 2 is\n\n$$ \\tau_{2,att} = E(Y_2(1) - Y_2(0) | D=1) $$ {#eq-did-2}\n\nThe first term is observed. The second is the counterfactual.\n\n## Parallel Trends Assumption\n\n$$ E[Y_2(0) -Y_1(0) | D=1] = E[Y_2(0) - Y_1(0) | D =0] $$ {#eq-did-3}\n\nor\n\n$$ E[\\Delta Y(0) | D=1] = E[\\Delta Y(0) | D =0] $$ {#eq-did-4}\n\nIn words, the change in untreated potential outcomes between periods 1 and 2 is the same for treated and control groups.\n\n## No Anticipation Assumption\n\n$$ E[Y_1(1) - Y_1(0) | D=1] = 0 $$ {#eq-did-5}\n\nThis is to say, in period 1, there is no treatment effect for the treated group.\n\n## DiD is Identified with PT and NA\n\nWith Parallel Trends, we notice $$\\small  E[Y_2(0) | D=1 ]= E[Y_1(0) | D=1] + E[Y_2(0) - Y_1(0) | D=0] $$ {#eq-did-6}\n\nThen, with No Anticipation, $$\n\\begin{aligned}\nE[Y_2(0) | D=1 ] &= E[Y_1(1) | D=1] + E[Y_2(0) - Y_1(0) | D=0]\\\\\n&= E[Y_1 | D=1] + E[Y_2-Y_1 | D=0]\n\\end{aligned}\n$$ {#eq-did-7} \n\n$$\\small  \\tau_{2,att} = E[Y_2 - Y_1 | D=1] - E[Y_2-Y_1 | D=0] $$ {#eq-did-8}\n\nParallel trends and no anticipation are the two assumptions we name, but they are not the whole set the derivation uses. It also maintains consistency and a well-defined treatment, so that $Y = DY(1) + (1-D)Y(0)$ and the treatment has no hidden versions with different effects. It maintains no interference for the stated estimand: one unit's outcome does not move with another unit's treatment. @sec-spatial-interference returns to this and shows what the estimand becomes when it fails. It maintains overlap, so both groups are observed in both periods and, once covariates enter, comparable units exist in each. And it maintains stable composition, so the same population is sampled in both periods. Differential attrition or entry breaks the comparison even when trends are parallel.\n\n## Advantages and Disadvantages of DiD\n\nAdvantages:\n\n-   No need to assume unconfoundedness. PT and NA take its place, alongside the maintained conditions listed above. Or say we don't need treatment itself to be independent of potential outcomes, but we do need it to be independent to the change in potential outcome at least for untreated state. This is importantly weaker in a lot of situations. There can be selection bias. If the selection bias does not change over time, then DiD can handle it.\n\nDisadvantages:\n\n-   PT and NA might be violated.\n-   PT is not scale free, in the sense that even if outcome can have PT, but then non-linear transformation of outcome won't have PT (for example log of Y).\n\n## Traditional DiD\n\nIn practice, DiD in many period setting is usually done with\n\n$$ Y_{it} = \\alpha_i + \\phi_t + W_{it} \\beta + \\epsilon_{it} $$ {#eq-did-9}\n\nhere $W_{it} =(1[t=2] \\cdot D_i)$, which is the interaction of post-treatment indicator and treatment group indicator.\n\nThis is usually called Two Way Fixed Effect (TWFE). There are multiple ways to implement the same model in practice.\n\nTWFE can be done by \"Pooled OLS\". That is, using OLS on time dummies and firm (individual) dummies. Wooldridge (2021) shows it's equivalent to use treatment dummies, instead of individual dummies. He also shows that this model can be equivalently implemented with fixed effect model and random effect model.\n\n## TWFE with Staggered Treatment Timing\n\nThe problem comes in when there is different timing of treatment. People used to still use\n\n$$ Y_{it} = \\alpha_i + \\phi_t + W_{it} \\beta + \\epsilon_{it} $$ {#eq-did-10}\n\nwhere $W_{it}$ now is a dummy when an individual $i$ gets treated at time $t$.\n\nHowever, what is $\\beta$ here?\n\n## Goodman-Bacon Decomposition\n\nGoodman-Bacon (2021) showed that $\\beta$ in the TWFE is a weighted average of many different treatment effects, between treated cohorts, and control units, both can be different at different time points. The weights are a function of the size of the subsample, relative size of treatment and control units, and the timing of treatment in the sub sample. The decomposition weights themselves are non-negative and sum to one; the problem is that the units treated earlier are used as controls later. When those \"forbidden\" 2x2 comparisons are expressed in terms of the underlying cohort-time ATTs, some ATTs receive negative weight (de Chaisemartin and D'Haultfœuille 2020). Therefore there is no meaningful interpretation of $\\beta$: it does not need to be a convex combination of treatment effects.\n\n![Bacon decomposition](images/bacon1.png)\n\n![Bacon decomposition](images/bacon2.png)\n\n## Wooldridge's ETWFE\n\nThere are a lot of ways to deal with staggered DiD situation. Wooldridge (2021) is basically saying: This is not a problem of TWFE, it's a mis-use of TWFE. The reason we get non-sensible result of $\\beta$ is that we know there is heterogeneous treatment effect, in the sense the treatment effect differs across cohort, but we force them to be the same. If we relax it, it can work. As he shows, this works when we specify cohort effects accordingly.\n\n$$ y_{it} = \\alpha_i + \\phi_t + \\sum_{g=g_0}^G \\sum_{t=g}^T \\lambda_{g,t} \\times 1(g,t) + \\epsilon_{i,t} $$ {#eq-did-11}\n\nHere $g$ is a cohort indicator, a cohort is determined by the time of getting treatment. ETWFE is allowing each cohort to have different effect at each different time point after being treated. The baseline group is the never treated group. If there is no never treated group, it can easily be changed to comparing to the last treated group.\n\nWhen the treatment comes in amounts, such as a dose or a count, the same regression extends to it. The chapter [DiD with Continuous Treatment](did-continuous.qmd) covers that case.\n\n## Example 1: US Teen Employment\n\nWe'll use the mpdta dataset on US teen employment from the did package. \"Treatment\" in this dataset refers to an increase in the minimum wage rate. Our goal is to estimate the effect of this minimum wage treatment (treat) on the log of teen employment (lemp). Notice that the panel ID is at the county level (countyreal), but treatment was staggered across cohorts (first_treat) so that a group of counties were treated at the same time. In addition to these staggered treatment effects, we also observe log population (lpop) as a potential control variable.\n\n::: {.cell cache='true' execution_count=3}\n``` {.julia .cell-code}\n# mpdta from the did R package (Callaway & Sant'Anna 2021)\nmpdta = CSV.read(\"data/mpdta.csv\", DataFrame)\nrename!(mpdta, \"first.treat\" => \"first_treat\")\nfirst(mpdta, 6)\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=tex}\n\\begin{tabular}{r|cccccc}\n\t& year & countyreal & lpop & lemp & first\\_treat & treat\\\\\n\t\\hline\n\t& Int64 & Int64 & Float64 & Float64 & Int64 & Int64\\\\\n\t\\hline\n\t1 & 2003 & 8001 & 5.89676 & 8.46147 & 2007 & 1 \\\\\n\t2 & 2004 & 8001 & 5.89676 & 8.33687 & 2007 & 1 \\\\\n\t3 & 2005 & 8001 & 5.89676 & 8.34022 & 2007 & 1 \\\\\n\t4 & 2006 & 8001 & 5.89676 & 8.37816 & 2007 & 1 \\\\\n\t5 & 2007 & 8001 & 5.89676 & 8.48735 & 2007 & 1 \\\\\n\t6 & 2003 & 8019 & 2.23238 & 4.99721 & 2007 & 1 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\nThe three tables below give the panel shape: observations per year, the\never-treated indicator, and the treatment cohorts.\n\n::: {.cell cache='true' execution_count=4}\n``` {.julia .cell-code}\ndisplay(combine(groupby(mpdta, :year), nrow))\ndisplay(combine(groupby(mpdta, :treat), nrow))\ndisplay(combine(groupby(mpdta, :first_treat), nrow))\n```\n\n::: {.cell-output .cell-output-display}\n```{=tex}\n\\begin{tabular}{r|cc}\n\t& year & nrow\\\\\n\t\\hline\n\t& Int64 & Int64\\\\\n\t\\hline\n\t1 & 2003 & 500 \\\\\n\t2 & 2004 & 500 \\\\\n\t3 & 2005 & 500 \\\\\n\t4 & 2006 & 500 \\\\\n\t5 & 2007 & 500 \\\\\n\\end{tabular}\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=tex}\n\\begin{tabular}{r|cc}\n\t& treat & nrow\\\\\n\t\\hline\n\t& Int64 & Int64\\\\\n\t\\hline\n\t1 & 0 & 1545 \\\\\n\t2 & 1 & 955 \\\\\n\\end{tabular}\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=tex}\n\\begin{tabular}{r|cc}\n\t& first\\_treat & nrow\\\\\n\t\\hline\n\t& Int64 & Int64\\\\\n\t\\hline\n\t1 & 0 & 1545 \\\\\n\t2 & 2004 & 100 \\\\\n\t3 & 2006 & 200 \\\\\n\t4 & 2007 & 655 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\nThe panel is balanced: 500 counties observed in each of 2003 through 2007,\n2,500 observations. 955 observations belong to ever-treated counties and 1,545\nto never-treated ones. The cohorts are 2004 (100 observations, so 20 counties),\n2006 (200, or 40 counties) and 2007 (655, or 131 counties), with 309 counties\nnever treated. Treatment timing is staggered, which is exactly the case where\nplain TWFE misbehaves.\n\nWe fit ETWFE with log population as a control, clustering on county.\n\n::: {.cell cache='true' execution_count=5}\n``` {.julia .cell-code}\nmod = etwfe(mpdta, @formula(lemp ~ lpop);   # outcome ~ controls\n            tvar = :year,                   # time variable\n            gvar = :first_treat,            # group variable\n            vcov = Vcov.cluster(:countyreal));  # clustered by county\n```\n:::\n\n\n::: {.cell cache='true' execution_count=6}\n``` {.julia .cell-code}\nshow_regression_html(mod.model)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<table style=\"border-collapse: collapse; font-family: monospace; font-size: 13px; margin: 0.5em 0;\"><thead><tr><th style=\"text-align: left; padding: 4px 10px 4px 0; border-bottom: 1px solid black;\"></th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Estimate</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Std. Error</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">t value</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Pr(>|t|)</th></tr></thead><tbody><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2004_t2004</td><td style=\"text-align: right; padding: 3px 8px;\">-0.021</td><td style=\"text-align: right; padding: 3px 8px;\">0.022</td><td style=\"text-align: right; padding: 3px 8px;\">-0.978</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.328</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2004_t2004_x_lpop</td><td style=\"text-align: right; padding: 3px 8px;\">0.005</td><td style=\"text-align: right; padding: 3px 8px;\">0.018</td><td style=\"text-align: right; padding: 3px 8px;\">0.263</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.792</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2004_t2005</td><td style=\"text-align: right; padding: 3px 8px;\">-0.082</td><td style=\"text-align: right; padding: 3px 8px;\">0.027</td><td style=\"text-align: right; padding: 3px 8px;\">-2.991</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.003 **</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2004_t2005_x_lpop</td><td style=\"text-align: right; padding: 3px 8px;\">0.025</td><td style=\"text-align: right; padding: 3px 8px;\">0.018</td><td style=\"text-align: right; padding: 3px 8px;\">1.403</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.161</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2004_t2006</td><td style=\"text-align: right; padding: 3px 8px;\">-0.138</td><td style=\"text-align: right; padding: 3px 8px;\">0.031</td><td style=\"text-align: right; padding: 3px 8px;\">-4.478</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">7.534e-06 ***</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2004_t2006_x_lpop</td><td style=\"text-align: right; padding: 3px 8px;\">0.051</td><td style=\"text-align: right; padding: 3px 8px;\">0.021</td><td style=\"text-align: right; padding: 3px 8px;\">2.408</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.016 *</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2004_t2007</td><td style=\"text-align: right; padding: 3px 8px;\">-0.110</td><td style=\"text-align: right; padding: 3px 8px;\">0.032</td><td style=\"text-align: right; padding: 3px 8px;\">-3.390</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">6.997e-04 ***</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2004_t2007_x_lpop</td><td style=\"text-align: right; padding: 3px 8px;\">0.011</td><td style=\"text-align: right; padding: 3px 8px;\">0.027</td><td style=\"text-align: right; padding: 3px 8px;\">0.423</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.672</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2006_t2006</td><td style=\"text-align: right; padding: 3px 8px;\">0.003</td><td style=\"text-align: right; padding: 3px 8px;\">0.019</td><td style=\"text-align: right; padding: 3px 8px;\">0.134</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.893</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2006_t2006_x_lpop</td><td style=\"text-align: right; padding: 3px 8px;\">0.039</td><td style=\"text-align: right; padding: 3px 8px;\">0.016</td><td style=\"text-align: right; padding: 3px 8px;\">2.364</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.018 *</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2006_t2007</td><td style=\"text-align: right; padding: 3px 8px;\">-0.045</td><td style=\"text-align: right; padding: 3px 8px;\">0.022</td><td style=\"text-align: right; padding: 3px 8px;\">-2.051</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.040 *</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2006_t2007_x_lpop</td><td style=\"text-align: right; padding: 3px 8px;\">0.038</td><td style=\"text-align: right; padding: 3px 8px;\">0.022</td><td style=\"text-align: right; padding: 3px 8px;\">1.694</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.090 .</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2007_t2007</td><td style=\"text-align: right; padding: 3px 8px;\">-0.046</td><td style=\"text-align: right; padding: 3px 8px;\">0.018</td><td style=\"text-align: right; padding: 3px 8px;\">-2.557</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.011 *</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2007_t2007_x_lpop</td><td style=\"text-align: right; padding: 3px 8px;\">-0.020</td><td style=\"text-align: right; padding: 3px 8px;\">0.016</td><td style=\"text-align: right; padding: 3px 8px;\">-1.225</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.221</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_x_lpop</td><td style=\"text-align: right; padding: 3px 8px;\">1.065</td><td style=\"text-align: right; padding: 3px 8px;\">0.022</td><td style=\"text-align: right; padding: 3px 8px;\">48.821</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_x_lpop_g2004</td><td style=\"text-align: right; padding: 3px 8px;\">0.051</td><td style=\"text-align: right; padding: 3px 8px;\">0.038</td><td style=\"text-align: right; padding: 3px 8px;\">1.350</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.177</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_x_lpop_g2006</td><td style=\"text-align: right; padding: 3px 8px;\">-0.041</td><td style=\"text-align: right; padding: 3px 8px;\">0.047</td><td style=\"text-align: right; padding: 3px 8px;\">-0.867</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.386</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_x_lpop_g2007</td><td style=\"text-align: right; padding: 3px 8px;\">0.056</td><td style=\"text-align: right; padding: 3px 8px;\">0.039</td><td style=\"text-align: right; padding: 3px 8px;\">1.416</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.157</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_x_lpop_t2004</td><td style=\"text-align: right; padding: 3px 8px;\">0.011</td><td style=\"text-align: right; padding: 3px 8px;\">0.008</td><td style=\"text-align: right; padding: 3px 8px;\">1.458</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.145</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_x_lpop_t2005</td><td style=\"text-align: right; padding: 3px 8px;\">0.021</td><td style=\"text-align: right; padding: 3px 8px;\">0.008</td><td style=\"text-align: right; padding: 3px 8px;\">2.558</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.011 *</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_x_lpop_t2006</td><td style=\"text-align: right; padding: 3px 8px;\">0.011</td><td style=\"text-align: right; padding: 3px 8px;\">0.011</td><td style=\"text-align: right; padding: 3px 8px;\">0.974</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.330</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_x_lpop_t2007</td><td style=\"text-align: right; padding: 3px 8px;\">0.021</td><td style=\"text-align: right; padding: 3px 8px;\">0.012</td><td style=\"text-align: right; padding: 3px 8px;\">1.772</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.076 .</td></tr><tr><td style=\"text-align: left; padding: 6px 0 0 0; border-top: 1px solid black;\" colspan=\"5\">---<br/>Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</td></tr></tbody></table>\n```\n:::\n:::\n\n\nThe raw model has one coefficient per cohort-year cell plus the control\ninteractions, 22 in all. That is not something to read directly. `emfx()` aggregates the cells into the ATT.\n\n::: {.cell cache='true' execution_count=7}\n``` {.julia .cell-code}\nemfx(mod)\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=tex}\n\\begin{tabular}{r|ccccc}\n\t& type & estimate & std\\_error & conf\\_low & conf\\_high\\\\\n\t\\hline\n\t& String & Float64 & Float64 & Float64 & Float64\\\\\n\t\\hline\n\t1 & ATT & -0.050627 & 0.0124973 & -0.0751212 & -0.0261329 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\nThe ATT is $-0.0506$ with a standard error of 0.0125 and a 95% interval of\n$[-0.0751, -0.0261]$. Raising the minimum wage lowered teen employment by about\n5% on average across treated county-years.\n\nThe same cells can be aggregated by time since treatment instead.\n\n::: {.cell cache='true' execution_count=8}\n``` {.julia .cell-code}\nmod_es = emfx(mod, type = \"event\")\nmod_es\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=tex}\n\\begin{tabular}{r|ccccc}\n\t& event & estimate & std\\_error & conf\\_low & conf\\_high\\\\\n\t\\hline\n\t& Int64 & Float64 & Float64 & Float64 & Float64\\\\\n\t\\hline\n\t1 & 0 & -0.0332122 & 0.013366 & -0.059409 & -0.00701545 \\\\\n\t2 & 1 & -0.0573456 & 0.0171496 & -0.0909583 & -0.023733 \\\\\n\t3 & 2 & -0.13787 & 0.0307884 & -0.198214 & -0.0775264 \\\\\n\t4 & 3 & -0.109539 & 0.0323153 & -0.172876 & -0.0462028 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\nThe effect grows with exposure: $-0.033$ in the treatment year, $-0.057$ after\none year, $-0.138$ after two, $-0.110$ after three. All four are significant.\nThe standard errors widen with event time, from 0.013 to 0.032, because the\nlater horizons rest on fewer cohorts: event time 0 uses all three cohorts (191\ncounties), event time 1 uses the 2004 and 2006 cohorts (60 counties), and event\ntimes 2 and 3 rest on the 2004 cohort alone (20 counties).\n\nAdding `post_only = FALSE` keeps the pre-treatment periods in the plot.\n\n::: {.cell cache='true' execution_count=9}\n``` {.julia .cell-code}\nmod_es2 = emfx(mod, type = \"event\", post_only = false)\n\nfig = Figure()\nax = Axis(fig[1, 1],\n    xlabel = \"Years post treatment\",\n    ylabel = \"Effect on log teen employment\",\n    xticks = -4:3,\n    title = \"Note: Zero pre-treatment effects for illustrative purposes only.\")\nhlines!(ax, 0, color = :black)\nvlines!(ax, -1, color = :black, linestyle = :dash)\nok = .!isnan.(mod_es2.std_error)\nrangebars!(ax, mod_es2.event[ok], mod_es2.conf_low[ok], mod_es2.conf_high[ok], color = :darkcyan)\nscatter!(ax, mod_es2.event, mod_es2.estimate, color = :darkcyan)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n![](did_files/figure-pdf/cell-10-output-1.png){fig-pos='H'}\n:::\n:::\n\n\nRead the pre-treatment points with care, and note the caption on the figure.\nWith `etwfe`'s default comparison group the pre-treatment estimates are forced\nto zero by construction, so their sitting on the line is arithmetic, not\nevidence for parallel trends. The Poisson example below uses\n`cgroup = \"never\"`, which frees them and makes the pre-period a real check.\n\n## Example 2: Staggered DiD\n\nTo see whether ETWFE recovers what it should, we switch to simulated data where\nthe answer is recorded in the file.\n\n`data/did_staggered_6.dta` is Wooldridge's simulated staggered panel: 500 units\nobserved annually from 2001 to 2006, 3,000 observations. Units are treated in\n2004 (119 units), 2005 (83) or 2006 (36), and 262 are never treated. The\noutcome is `y`, `x` is a covariate, `d4`, `d5` and `d6` are cohort dummies, and\n`f04`, `f05`, `f06` are year dummies. What makes the file useful is `te4`,\n`te5` and `te6`: the true unit-level treatment effect each unit would\nexperience under each cohort's treatment date. The effects are heterogeneous\nacross units and grow with time since treatment, which is precisely the\nconfiguration that breaks plain TWFE.\n\n::: {.cell cache='true' execution_count=10}\n``` {.julia .cell-code}\n# now we do staggered did.\ndid_data = DataFrame(readstat(\"data/did_staggered_6.dta\"))\ndid_data.first_treat = [r.d4 == 1 ? 2004 : r.d5 == 1 ? 2005 : r.d6 == 1 ? 2006 : 0\n                        for r in eachrow(did_data)]\n\nfirst(select(did_data, :id, :year, :y, :x, :d4, :d5, :d6, :te4, :te5, :te6, :first_treat), 6)\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```{=tex}\n\\begin{tabular}{r|ccccccccccc}\n\t& id & year & y & x & d4 & d5 & d6 & te4 & te5 & te6 & first\\_treat\\\\\n\t\\hline\n\t& Int16 & Int16 & Float32 & Float32 & Int8 & Int8 & Int8 & Float32 & Float32 & Float32 & Int64\\\\\n\t\\hline\n\t1 & 1 & 2001 & 18.3596 & 0.899984 & 0 & 0 & 0 & 0.0 & 0.0 & 0.0 & 0 \\\\\n\t2 & 1 & 2002 & 18.1016 & 0.899984 & 0 & 0 & 0 & 0.0 & 0.0 & 0.0 & 0 \\\\\n\t3 & 1 & 2003 & 18.5956 & 0.899984 & 0 & 0 & 0 & 0.0 & 0.0 & 0.0 & 0 \\\\\n\t4 & 1 & 2004 & 16.5003 & 0.899984 & 0 & 0 & 0 & 1.43223 & 0.0 & 0.0 & 0 \\\\\n\t5 & 1 & 2005 & 19.9573 & 0.899984 & 0 & 0 & 0 & 2.57319 & 2.24723 & 0.0 & 0 \\\\\n\t6 & 1 & 2006 & 19.8659 & 0.899984 & 0 & 0 & 0 & 5.06752 & 4.23316 & 0.785892 & 0 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n::: {.cell cache='true' execution_count=11}\n``` {.julia .cell-code}\ncombine(groupby(did_data, :first_treat), nrow)\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=tex}\n\\begin{tabular}{r|cc}\n\t& first\\_treat & nrow\\\\\n\t\\hline\n\t& Int64 & Int64\\\\\n\t\\hline\n\t1 & 0 & 1572 \\\\\n\t2 & 2004 & 714 \\\\\n\t3 & 2005 & 498 \\\\\n\t4 & 2006 & 216 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\nThe counts are observations, six per unit: 1,572 never-treated, 714 in the 2004\ncohort, 498 in 2005, 216 in 2006.\n\nBecause the true effects are in the data, we can compute the target before\nestimating it. Grouping the true effects by cohort and year gives the true ATT\nin each cohort-year cell.\n\n::: {.cell cache='true' execution_count=12}\n``` {.julia .cell-code}\ncohort_cell(d, f, lab) = ifelse.((d .== 1) .& (f .== 1), lab, missing)\ndid_data.treated_cohort1 = coalesce.(cohort_cell(did_data.d4, did_data.f04, \"d4f04\"),\n                                     cohort_cell(did_data.d4, did_data.f05, \"d4f05\"),\n                                     cohort_cell(did_data.d4, did_data.f06, \"d4f06\"))\ndid_data.treated_cohort2 = coalesce.(cohort_cell(did_data.d5, did_data.f05, \"d5f05\"),\n                                     cohort_cell(did_data.d5, did_data.f06, \"d5f06\"))\ndid_data.treated_cohort3 = cohort_cell(did_data.d6, did_data.f06, \"d6f06\")\n\ncombine(groupby(dropmissing(did_data, :treated_cohort1), :treated_cohort1), :te4 => mean => :mean4)\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```{=tex}\n\\begin{tabular}{r|cc}\n\t& treated\\_cohort1 & mean4\\\\\n\t\\hline\n\t& String & Float32\\\\\n\t\\hline\n\t1 & d4f04 & 3.75709 \\\\\n\t2 & d4f05 & 4.01757 \\\\\n\t3 & d4f06 & 4.57895 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n::: {.cell cache='true' execution_count=13}\n``` {.julia .cell-code}\ndisplay(combine(groupby(dropmissing(did_data, :treated_cohort2), :treated_cohort2), :te5 => mean => :mean5))\ndisplay(combine(groupby(dropmissing(did_data, :treated_cohort3), :treated_cohort3), :te6 => mean => :mean6))\n```\n\n::: {.cell-output .cell-output-display}\n```{=tex}\n\\begin{tabular}{r|cc}\n\t& treated\\_cohort2 & mean5\\\\\n\t\\hline\n\t& String & Float32\\\\\n\t\\hline\n\t1 & d5f05 & 2.73754 \\\\\n\t2 & d5f06 & 3.51606 \\\\\n\\end{tabular}\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=tex}\n\\begin{tabular}{r|cc}\n\t& treated\\_cohort3 & mean6\\\\\n\t\\hline\n\t& String & Float32\\\\\n\t\\hline\n\t1 & d6f06 & 1.84886 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\nSo the true cohort-year ATTs are: the 2004 cohort gains 3.76, 4.02 and 4.58 in\n2004, 2005 and 2006; the 2005 cohort gains 2.74 and 3.52 in 2005 and 2006; the\n2006 cohort gains 1.85 in 2006. Effects grow with time since treatment\nand shrink across later cohorts --- heterogeneity in both directions.\n\nAveraging those cells over the 559 treated observations gives a true overall\nATT of **3.677**. That is the number ETWFE has to reproduce.\n\n::: {.cell cache='true' execution_count=14}\n``` {.julia .cell-code}\n# this replicates Jeff's results with pooled ols or xtreg, with covariate x.\nmod = etwfe(did_data, @formula(y ~ x);   # outcome ~ controls\n            tvar = :year,                # time variable\n            gvar = :first_treat,         # group variable\n            vcov = Vcov.cluster(:id))\n\nshow_regression_html(mod.model)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<table style=\"border-collapse: collapse; font-family: monospace; font-size: 13px; margin: 0.5em 0;\"><thead><tr><th style=\"text-align: left; padding: 4px 10px 4px 0; border-bottom: 1px solid black;\"></th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Estimate</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Std. Error</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">t value</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Pr(>|t|)</th></tr></thead><tbody><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2004_t2004</td><td style=\"text-align: right; padding: 3px 8px;\">3.510</td><td style=\"text-align: right; padding: 3px 8px;\">0.303</td><td style=\"text-align: right; padding: 3px 8px;\">11.579</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2004_t2004_x_x</td><td style=\"text-align: right; padding: 3px 8px;\">-0.373</td><td style=\"text-align: right; padding: 3px 8px;\">1.046</td><td style=\"text-align: right; padding: 3px 8px;\">-0.357</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.721</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2004_t2005</td><td style=\"text-align: right; padding: 3px 8px;\">4.240</td><td style=\"text-align: right; padding: 3px 8px;\">0.329</td><td style=\"text-align: right; padding: 3px 8px;\">12.886</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2004_t2005_x_x</td><td style=\"text-align: right; padding: 3px 8px;\">0.532</td><td style=\"text-align: right; padding: 3px 8px;\">1.045</td><td style=\"text-align: right; padding: 3px 8px;\">0.509</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.611</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2004_t2006</td><td style=\"text-align: right; padding: 3px 8px;\">4.210</td><td style=\"text-align: right; padding: 3px 8px;\">0.331</td><td style=\"text-align: right; padding: 3px 8px;\">12.732</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2004_t2006_x_x</td><td style=\"text-align: right; padding: 3px 8px;\">2.588</td><td style=\"text-align: right; padding: 3px 8px;\">1.064</td><td style=\"text-align: right; padding: 3px 8px;\">2.431</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.015 *</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2005_t2005</td><td style=\"text-align: right; padding: 3px 8px;\">3.008</td><td style=\"text-align: right; padding: 3px 8px;\">0.341</td><td style=\"text-align: right; padding: 3px 8px;\">8.822</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2005_t2005_x_x</td><td style=\"text-align: right; padding: 3px 8px;\">0.959</td><td style=\"text-align: right; padding: 3px 8px;\">0.633</td><td style=\"text-align: right; padding: 3px 8px;\">1.515</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.130</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2005_t2006</td><td style=\"text-align: right; padding: 3px 8px;\">3.702</td><td style=\"text-align: right; padding: 3px 8px;\">0.368</td><td style=\"text-align: right; padding: 3px 8px;\">10.057</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2005_t2006_x_x</td><td style=\"text-align: right; padding: 3px 8px;\">0.157</td><td style=\"text-align: right; padding: 3px 8px;\">0.862</td><td style=\"text-align: right; padding: 3px 8px;\">0.182</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.856</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2006_t2006</td><td style=\"text-align: right; padding: 3px 8px;\">2.017</td><td style=\"text-align: right; padding: 3px 8px;\">0.571</td><td style=\"text-align: right; padding: 3px 8px;\">3.533</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">4.109e-04 ***</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_D_g2006_t2006_x_x</td><td style=\"text-align: right; padding: 3px 8px;\">0.724</td><td style=\"text-align: right; padding: 3px 8px;\">1.171</td><td style=\"text-align: right; padding: 3px 8px;\">0.618</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.537</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_x_x</td><td style=\"text-align: right; padding: 3px 8px;\">0.241</td><td style=\"text-align: right; padding: 3px 8px;\">0.453</td><td style=\"text-align: right; padding: 3px 8px;\">0.532</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.595</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_x_x_g2004</td><td style=\"text-align: right; padding: 3px 8px;\">-1.191</td><td style=\"text-align: right; padding: 3px 8px;\">0.934</td><td style=\"text-align: right; padding: 3px 8px;\">-1.275</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.202</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_x_x_g2005</td><td style=\"text-align: right; padding: 3px 8px;\">0.551</td><td style=\"text-align: right; padding: 3px 8px;\">0.607</td><td style=\"text-align: right; padding: 3px 8px;\">0.908</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.364</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_x_x_g2006</td><td style=\"text-align: right; padding: 3px 8px;\">0.994</td><td style=\"text-align: right; padding: 3px 8px;\">0.828</td><td style=\"text-align: right; padding: 3px 8px;\">1.202</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.229</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_x_x_t2002</td><td style=\"text-align: right; padding: 3px 8px;\">0.396</td><td style=\"text-align: right; padding: 3px 8px;\">0.328</td><td style=\"text-align: right; padding: 3px 8px;\">1.209</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.227</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_x_x_t2003</td><td style=\"text-align: right; padding: 3px 8px;\">0.976</td><td style=\"text-align: right; padding: 3px 8px;\">0.319</td><td style=\"text-align: right; padding: 3px 8px;\">3.054</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.002 **</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_x_x_t2004</td><td style=\"text-align: right; padding: 3px 8px;\">0.331</td><td style=\"text-align: right; padding: 3px 8px;\">0.351</td><td style=\"text-align: right; padding: 3px 8px;\">0.942</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.346</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_x_x_t2005</td><td style=\"text-align: right; padding: 3px 8px;\">0.239</td><td style=\"text-align: right; padding: 3px 8px;\">0.398</td><td style=\"text-align: right; padding: 3px 8px;\">0.600</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.549</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">_x_x_t2006</td><td style=\"text-align: right; padding: 3px 8px;\">0.360</td><td style=\"text-align: right; padding: 3px 8px;\">0.422</td><td style=\"text-align: right; padding: 3px 8px;\">0.855</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">0.393</td></tr><tr><td style=\"text-align: left; padding: 6px 0 0 0; border-top: 1px solid black;\" colspan=\"5\">---<br/>Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</td></tr></tbody></table>\n```\n:::\n:::\n\n\n::: {.cell cache='true' execution_count=15}\n``` {.julia .cell-code}\nemfx(mod)\n```\n\n::: {.cell-output .cell-output-display execution_count=15}\n```{=tex}\n\\begin{tabular}{r|ccccc}\n\t& type & estimate & std\\_error & conf\\_low & conf\\_high\\\\\n\t\\hline\n\t& String & Float64 & Float64 & Float64 & Float64\\\\\n\t\\hline\n\t1 & ATT & 3.67208 & 0.172081 & 3.33481 & 4.00936 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\nETWFE gives 3.67 with a standard error of 0.172 and a 95% interval of\n$[3.33, 4.01]$, against a true 3.677. It recovers the ATT to three decimals.\n\nThe same holds for the disaggregations. By time since treatment:\n\n::: {.cell cache='true' execution_count=16}\n``` {.julia .cell-code}\nmod_es = emfx(mod, type = \"event\")\nmod_es\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```{=tex}\n\\begin{tabular}{r|ccccc}\n\t& event & estimate & std\\_error & conf\\_low & conf\\_high\\\\\n\t\\hline\n\t& Int64 & Float64 & Float64 & Float64 & Float64\\\\\n\t\\hline\n\t1 & 0 & 3.10909 & 0.212614 & 2.69237 & 3.5258 \\\\\n\t2 & 1 & 4.01879 & 0.248267 & 3.5322 & 4.50539 \\\\\n\t3 & 2 & 4.20954 & 0.330621 & 3.56154 & 4.85755 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\nEstimated 3.11, 4.02 and 4.21 at event times 0, 1 and 2, against true values of\n3.11, 3.81 and 4.58. Every interval covers its truth, and the estimates\nreproduce the growth in the effect with exposure.\n\nAnd by calendar year:\n\n::: {.cell cache='true' execution_count=17}\n``` {.julia .cell-code}\nmod_es2 = emfx(mod, type = \"calendar\")\nmod_es2\n```\n\n::: {.cell-output .cell-output-display execution_count=17}\n```{=tex}\n\\begin{tabular}{r|ccccc}\n\t& calendar & estimate & std\\_error & conf\\_low & conf\\_high\\\\\n\t\\hline\n\t& Int64 & Float64 & Float64 & Float64 & Float64\\\\\n\t\\hline\n\t1 & 2004 & 3.5099 & 0.303131 & 2.91578 & 4.10403 \\\\\n\t2 & 2005 & 3.73388 & 0.253321 & 3.23738 & 4.23038 \\\\\n\t3 & 2006 & 3.70073 & 0.249441 & 3.21183 & 4.18962 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\nEstimated 3.51, 3.73 and 3.70 in 2004, 2005 and 2006, against true values of\n3.76, 3.49 and 3.80. Again all three intervals cover.\n\nNote that the calendar profile is nearly flat while the event-time profile\nrises. There is no contradiction: later calendar years mix an older cohort with\nlarge accumulated effects and a newly treated cohort with small ones, and the\ntwo movements offset. This is why the aggregation has to be chosen to match the\nquestion being asked.\n\n## Nonlinear ETWFE: Count and Binary Outcomes\n\n> **Related reading**: The theory behind nonlinear ETWFE --- Wooldridge's\n> conditional parallel-trends assumption on the linear index, the incidental\n> parameters argument for cohort rather than unit intercepts, and the average\n> partial effects that follow --- is developed at length in\n> [Extended two-way fixed effects](https://xiangao.github.io/blog_book/extended-twfe.html)\n> in *Topics on Econometrics and Causal Inference*, with\n> [count data](https://xiangao.github.io/blog_book/count-data.html) and\n> [Poisson with exposure](https://xiangao.github.io/blog_book/poisson-exposure.html)\n> covering the count case in more detail.\n\nETWFE is not limited to linear (continuous) outcomes. When the dependent variable is a count or a binary indicator, linear TWFE can give nonsensical results — negative predicted probabilities, additive effects that ignore the bounded or non-negative nature of $Y$. `etwfe()` supports the Poisson family via the `family` argument, which fits the model with `fepois()`.\n\nThe key identifying assumption shifts slightly. Instead of parallel trends on $E[Y_{it}(\\infty)]$, we assume parallel trends on the **linear index** — that is, on $\\log E[Y_{it}(\\infty)]$ for Poisson, or on $\\text{logit}\\, E[Y_{it}(\\infty)]$ for logit. This is Wooldridge's (2023) Conditional Parallel Trends assumption stated on $G^{-1}(E[Y])$. When the true treatment effect is multiplicative (e.g., a policy raises counts by 50% regardless of baseline), this assumption is more natural than additive PT on $Y$ itself.\n\nOne implementation detail matters: the nonlinear ETWFE specification uses **cohort fixed effects** (one intercept per treatment cohort) plus year fixed effects — not individual unit fixed effects. `etwfe()` handles this automatically. In the linear case the two are numerically equivalent (Wooldridge 2021), but in nonlinear models unit fixed effects raise the incidental-parameters problem and make average partial effects uncomputable — the unit intercepts cannot be averaged out of the nonlinear link. Wooldridge (2023) instead uses cohort intercepts (a Mundlak device), which is what `etwfe` implements.\n\n### Simulated example: staggered count data\n\nWe simulate $N = 400$ units over $T = 6$ periods, 2,400 observations. Units are\nsplit into four groups of 100 by id: the first is treated from period 3, the\nsecond from period 4, the third from period 5, and the fourth never. Each unit\ndraws a fixed effect $\\alpha_i \\sim N(0, 0.3^2)$. The log mean is\n$\\log \\mu_{it} = 1 + 0.2t + \\alpha_i + 0.4 D_{it}$, and the outcome is\n$Y_{it} \\sim \\text{Poisson}(\\mu_{it})$.\n\nThe treatment effect is multiplicative and homogeneous on the log scale: every\ntreated unit's expected count rises by a factor of $\\exp(0.4)$, that is by\n$\\exp(0.4) - 1 = 0.492$, or 49%. Parallel trends holds on the log scale by\nconstruction, and fails on the level scale, since a constant proportional\neffect is a larger absolute effect for units with higher baselines.\n\nOn the count scale the ATT is not 0.492. It is\n$E[\\mu_{it}(0) \\mid \\text{treated}] \\times (\\exp(0.4)-1)$, and the mean\nuntreated count among treated observations is 7.518, so the true ATT is\n$7.518 \\times 0.4918 = 3.698$ counts.\n\nThe table below reports mean counts by cohort and treatment status.\n\n::: {.cell cache='true' execution_count=18}\n``` {.julia .cell-code}\nRandom.seed!(42)\nN = 400; Tmax = 6\n\nunit_fe_vals = randn(N) .* 0.3\n\ndf_count = DataFrame([(id = i, year = t) for i in 1:N for t in 1:Tmax])\ncohort_grp = ((df_count.id .- 1) .÷ 100) .+ 1\ndf_count.first_treat = [3, 4, 5, 0][cohort_grp]   # 0 = never treated\ndf_count.treated = (df_count.first_treat .> 0) .& (df_count.year .>= df_count.first_treat)\ndf_count.unit_fe = unit_fe_vals[df_count.id]\ndf_count.log_mu = 1 .+ 0.2 .* df_count.year .+ df_count.unit_fe .+ 0.4 .* df_count.treated\ndf_count.count = rand.(Poisson.(exp.(df_count.log_mu)))\n\n# true count-scale ATT: mean untreated mean among treated observations times exp(0.4) - 1\nmu0 = exp.(df_count.log_mu .- 0.4 .* df_count.treated)\n@printf(\"mean untreated count among treated = %.3f, true ATT = %.3f\\n\",\n        mean(mu0[df_count.treated]), mean(mu0[df_count.treated]) * (exp(0.4) - 1))\n\ncombine(groupby(df_count, [:first_treat, :treated]), :count => mean => :mean_count)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmean untreated count among treated = 7.518, true ATT = 3.698\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=18}\n```{=tex}\n\\begin{tabular}{r|ccc}\n\t& first\\_treat & treated & mean\\_count\\\\\n\t\\hline\n\t& Int64 & Bool & Float64\\\\\n\t\\hline\n\t1 & 0 & 0 & 5.75 \\\\\n\t2 & 3 & 0 & 3.75 \\\\\n\t3 & 3 & 1 & 10.59 \\\\\n\t4 & 4 & 0 & 4.31667 \\\\\n\t5 & 4 & 1 & 11.8167 \\\\\n\t6 & 5 & 0 & 4.5 \\\\\n\t7 & 5 & 1 & 12.12 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\nThe never-treated group averages 5.75 counts. Treated cohorts average 3.75,\n4.32 and 4.50 before treatment and 10.6, 11.8 and 12.1 after. The pre-treatment\nmeans look low only because they are drawn from earlier periods, and the time\ntrend adds 0.2 to the log mean each period. This is exactly the comparison that\na raw before-after difference would get wrong.\n\n### Poisson ETWFE\n\nPass `family = \"poisson\"` to `etwfe()`. Everything else — cohort dummies, `emfx()`, event study — works identically to the linear case. We use `cgroup = \"never\"` so that pre-treatment estimates are not mechanistically forced to zero.\n\n::: {.cell cache='true' execution_count=19}\n``` {.julia .cell-code}\nmod_pois = etwfe(df_count, @formula(count ~ 1);\n                 tvar   = :year,\n                 gvar   = :first_treat,\n                 family = \"poisson\",\n                 cgroup = \"never\",\n                 vcov   = Vcov.cluster(:id));\n```\n:::\n\n\n::: {.cell cache='true' execution_count=20}\n``` {.julia .cell-code}\nemfx(mod_pois)\n```\n\n::: {.cell-output .cell-output-display execution_count=20}\n```{=tex}\n\\begin{tabular}{r|ccccc}\n\t& type & estimate & std\\_error & conf\\_low & conf\\_high\\\\\n\t\\hline\n\t& String & Float64 & Float64 & Float64 & Float64\\\\\n\t\\hline\n\t1 & ATT & 3.62343 & 0.34363 & 2.94993 & 4.29693 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\nThe estimate is 3.62 counts with a standard error of 0.34 and a 95% interval of\n$[2.95, 4.30]$, against the true 3.698 derived above. The interval covers it.\n\n`emfx()` returns average marginal effects — the average difference $E[Y(1)] - E[Y(0)]$ in **count units** across treated observations. This is the ATT on the count scale. The underlying model imposes PT on the log scale, so each cohort-time treatment coefficient in the raw model can be exponentiated to get the incidence rate ratio for that cell (here they share a common value because the simulated effect is homogeneous).\n\n### Event study\n\nBecause we passed `cgroup = \"never\"`, the pre-treatment estimates are free\nparameters rather than zeros by construction, so the pre-period is an actual\ntest here. On the count scale the post-treatment effect should also grow with\nevent time even though the log-scale effect is constant, because the baseline\ncount grows with the time trend: the true values are 3.06, 3.74, 4.18 and 4.55\nat event times 0 through 3.\n\n::: {.cell cache='true' execution_count=21}\n``` {.julia .cell-code}\nmod_pois_es = emfx(mod_pois, type = \"event\", post_only = false)\ndisplay(mod_pois_es)\n\nfig_p = Figure()\nax_p  = Axis(fig_p[1, 1],\n    xlabel = \"Years post treatment\",\n    ylabel = \"ATT (count units)\",\n    xticks = -4:3,\n    title  = \"Nonlinear ETWFE event study (Poisson)\")\nhlines!(ax_p, 0, color = :black)\nvlines!(ax_p, -1, color = :black, linestyle = :dash)\nok = .!isnan.(mod_pois_es.std_error)\nrangebars!(ax_p, mod_pois_es.event[ok], mod_pois_es.conf_low[ok], mod_pois_es.conf_high[ok],\n           color = :darkcyan)\nscatter!(ax_p, mod_pois_es.event, mod_pois_es.estimate, color = :darkcyan)\nfig_p\n```\n\n::: {.cell-output .cell-output-display}\n```{=tex}\n\\begin{tabular}{r|ccccc}\n\t& event & estimate & std\\_error & conf\\_low & conf\\_high\\\\\n\t\\hline\n\t& Int64 & Float64 & Float64 & Float64 & Float64\\\\\n\t\\hline\n\t1 & -4 & 0.673962 & 0.284111 & 0.117115 & 1.23081 \\\\\n\t2 & -3 & -0.045772 & 0.235216 & -0.506785 & 0.415241 \\\\\n\t3 & -2 & 0.0470628 & 0.176909 & -0.299671 & 0.393797 \\\\\n\t4 & -1 & 0.0 & NaN & NaN & NaN \\\\\n\t5 & 0 & 3.09953 & 0.262425 & 2.58519 & 3.61387 \\\\\n\t6 & 1 & 3.74512 & 0.357564 & 3.04431 & 4.44593 \\\\\n\t7 & 2 & 3.84242 & 0.565125 & 2.7348 & 4.95004 \\\\\n\t8 & 3 & 4.39207 & 0.797697 & 2.82861 & 5.95552 \\\\\n\\end{tabular}\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=21}\n![](did_files/figure-pdf/cell-22-output-2.png){fig-pos='H'}\n:::\n:::\n\n\nThe pre-treatment estimates at event times $-3$ and $-2$ are close to zero. The one at $-4$ is 0.67 with a standard error of 0.28, and its interval excludes zero. It rests on a single cohort-period, the period-5 cohort in period 1. Parallel trends holds by construction in this simulation, so this is one rejection in three pre-period tests at the 5% level, which chance produces often enough. With real data it would call for a closer look. The post-treatment estimates are 3.10, 3.75, 3.84 and 4.39, each with an interval that covers its true value. They rise with event time, which is the count-scale consequence of a constant log-scale effect applied to a growing baseline, not evidence of a growing treatment effect.\n\n### Comparison: linear ETWFE on log(count + 1)\n\nA common alternative is to log-transform the count and run linear ETWFE. This is biased when zeros are present (the $+1$ shift distorts the linear index) and misinterprets the scale of the effect. For comparison:\n\n::: {.cell cache='true' execution_count=22}\n``` {.julia .cell-code}\ndf_count.log_count = log.(df_count.count .+ 1)\n\nmod_lin = etwfe(df_count, @formula(log_count ~ 1);\n                tvar = :year,\n                gvar = :first_treat,\n                vcov = Vcov.cluster(:id))\nemfx(mod_lin)\n```\n\n::: {.cell-output .cell-output-display execution_count=22}\n```{=tex}\n\\begin{tabular}{r|ccccc}\n\t& type & estimate & std\\_error & conf\\_low & conf\\_high\\\\\n\t\\hline\n\t& String & Float64 & Float64 & Float64 & Float64\\\\\n\t\\hline\n\t1 & ATT & 0.399088 & 0.0323772 & 0.33563 & 0.462546 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\nThe linear model returns 0.40 with a 95% interval of $[0.336, 0.463]$. That\nnumber is neither the count-scale ATT of 3.62 nor the log-scale parameter 0.4,\nthough it happens to sit near the latter because the counts here are large\nenough that $\\log(Y+1) \\approx \\log Y$. With many zeros the approximation\nbreaks and the estimate drifts.\n\nThe linear model estimates the ATT on the $\\log(Y+1)$ scale — not the same quantity as the Poisson ATT and harder to interpret. When treatment effects are multiplicative, Poisson ETWFE is the more appropriate model.\n\n## Spatial Interference {#sec-spatial-interference}\n\nEverything in this chapter so far assumes SUTVA: one unit's outcome does not depend on another unit's treatment. That is not always plausible. A treated municipality may affect deforestation in nearby untreated municipalities. A vaccinated household may reduce transmission to nearby households. A labor-market policy in one commuting zone may change flows to its neighbors. With this kind of spatial spillover, the usual DiD estimand no longer has the interpretation we want. Xu [-@xu2023] shows that ignoring interference can produce an estimand that is neither a direct effect nor a spillover effect.\n\nXu [-@xu2023; -@xu2026] develops a doubly robust DiD that keeps the identifying logic of conditional parallel trends but adds an exposure mapping $G_{it} = G(i, W_{-it})$ for unit $i$'s neighborhood treatment status. The estimand is the direct ATT at exposure level $g$,\n\n$$ \\tau_g(t, c) = \\frac{1}{|S_M|} \\sum_{i \\in S_M} \\mathbb{E}[y_{it}(c, g) - y_{it}(\\infty, g) \\mid z_i, C_i = c, G_{it} = g], $$ {#eq-did-12}\n\nwhere $C_i$ is unit $i$'s first treatment period (so $\\{C_i > t\\}$ is the not-yet-directly-treated comparison group), $S_M = \\{C_i = c\\} \\cup \\{C_i > t\\}$, and $g$ is a chosen exposure level. The DR plug-in averages three pieces over $S_M$: an IPW term from the treated cohort, an IPW term from the not-yet-treated, and a regression-imputation term, with three propensity models ($\\eta_{tc}$ for cohort, $\\eta_{tcg}$ and $\\eta_{t\\infty g}$ for exposure) and two outcome-change regressions. It is consistent if either all three propensities or both outcome models are correctly specified.\n\nThe companion package [`DidInterference.jl`](https://github.com/xiangao/DidInterference.jl) implements this. The 2x2 base case (Xu 2023):\n\n::: {.cell execution_count=23}\n``` {.julia .cell-code}\nusing DidInterference, DataFrames\n\n# Wide-format two-period data with a binary exposure G.\nres = did_int_2x2(panel;\n    yname      = :Y_post,\n    yname_pre  = :Y_pre,\n    treat      = :W,\n    exposure   = :G,\n    g          = 1,\n    covariates = [:z1, :z2],\n    trim       = 0.01)   # Xu (2026) uses 0.01 in the Brazil application\n\nprintln(res.estimate, \"  \", res.ci)\n```\n:::\n\n\nFor staggered adoption (Xu 2026), `did_int_staggered()` loops over `(cohort, time)` cells with $t \\geq c$, restricts to $S_M$ in each cell, fits the DR estimator, and aggregates across cells using joint-IF stacking (per-cell IFs share the never-treated comparison group, so independence-style SEs underestimate uncertainty noticeably). The R port [`didint`](https://github.com/xiangao/didint) has identical estimators; its `vignettes/brazil_amazon.Rmd` vignette replicates Section III of Xu (2026), the *Lista de Municípios Prioritários* policy on Amazon deforestation, using the public Assunção-McMillan-Murphy-Souza-Rodrigues replication archive on Zenodo.\n\n## Persistent Outcomes and Heterogeneous Dynamics\n\nStandard event-study TWFE regressions like\n\n$$ Y_{it} = \\alpha_i + \\gamma_t + \\sum_{j} D_{it}^j \\delta_j + X_{it}'\\beta + U_{it} $$ {#eq-did-13}\n\nleave the dynamics of $Y$ unmodelled. Three things get run together here and\nare worth separating.\n\nThe first is serial correlation in $U_{it}$. That is an inference problem rather\nthan an identification one: with exogenous treatment timing the event-time\ncoefficients remain consistent, but conventional standard errors are wrong,\nwhich is why DiD is routinely clustered by unit.\n\nThe second is dynamic selection. If units are treated *because* of their recent\noutcomes, then treatment timing is related to lagged $Y$ and the parallel-trends\nrestriction the specification relies on no longer holds. That is an\nidentification failure, and no amount of clustering repairs it.\n\nThe third is what motivates the rest of this section. When the outcome is\ngenuinely persistent — earnings, employment, consumption, anything with habits\nor adjustment costs — the *structural* process carries its own lag, and\n@eq-did-13 is a static equation fitted to dynamic data. The event-time dummies\nthen absorb the propagation of earlier shocks along with the treatment response,\nand the bias on those coefficients grows with the event-time horizon (Botosaru\nand Liu, 2025, Figure 1). Note where the bias comes from: not from persistence\nin the residual, which on its own does no such thing, but from fitting a static\nspecification to a dynamic process.\n\nBotosaru and Liu [-@botosaru-liu-2025] introduce a **dynamic panel\nwith correlated random coefficients** that handles both persistence\nand unit-level heterogeneity in dynamic responses:\n\n$$ Y_{it} = \\rho_Y Y_{i,t-1} + \\alpha_i + \\sum_j D_{it}^j \\delta_{ij} + X_{it}'\\beta + U_{it}, $$ {#eq-did-14}\n\nwith a parsimonious AR(1) structure on the event-time effects to keep\ndimensionality manageable:\n\n$$ \\delta_{ij} = \\rho_\\delta \\delta_{i,j-1} + \\varepsilon_{ij}, \\quad j \\geq 1. $$ {#eq-did-15}\n\nThe latent $\\lambda_i = (\\alpha_i, \\delta_{i0})$ is a unit-specific\ncorrelated random coefficient. A two-step semiparametric estimator: step 1\nis **quasi-maximum likelihood** for the common parameters\n$(\\rho_Y, \\rho_\\delta, \\sigma_U^2, \\sigma_\\varepsilon^2, \\beta)$ under\na Gaussian working assumption on $\\lambda_i$ (consistent under\nmisspecification of that working assumption); step 2 is\n**Tweedie / Gaussian-conjugate empirical Bayes** for the unit-level\nposterior trajectories $\\{\\delta_{i,j}\\}_{j=0}^J$, achieving asymptotic\nratio optimality.\n\nA companion paper [@botosaru-liu-2026] adds a **homogeneous-feedback\nextension**: covariates $X_{it}$ are allowed to adjust endogenously to\npast $Y$ and treatment (the canonical example: minimum-wage policy\naffects wages directly and also indirectly through firms re-optimising\ninput demand). Under the assumption that the covariate adjustment rule\ndoes not depend on $\\lambda_i$ given the observable history, the\nlikelihood factors into a structural piece (for $Y \\mid X$, history)\nand a feedback piece (for $X$ given history), each separately\nidentified. The factorisation yields a clean decomposition of dynamic\ntreatment effects into **direct** (through $\\delta_{i,j}$) and\n**indirect** (through covariate feedback) components.\n\nThe package [`TVHTE.jl`](https://github.com/xiangao/TVHTE.jl) implements\nboth papers:\n\n::: {.cell execution_count=24}\n``` {.julia .cell-code}\nusing TVHTE\n\n# Fit on a panel with staggered cohorts and a covariate\nfit = tvhte(panel_Y, baseline_Y; t0 = cohort, J = max_event_time, X = panel_X)\n\n# Feedback model + direct/indirect counterfactual decomposition\nfb = fit_feedback(panel_Y, baseline_Y, panel_X, baseline_X)\ncf = simulate_counterfactual(fit, fb, alt_cohort)\n```\n:::\n\n\nAn R port with the same API is at\n[`tvhte`](https://github.com/xiangao/tvhte); both packages have\ndeployed docs at <https://xiangao.github.io/TVHTE.jl/> and\n<https://xiangao.github.io/tvhte/>.\n\n## Synthetic Control and Synthetic DiD\n\nThe biggest problem with DiD is the PT assumption. Synthetic control and synthetic DiD replace it with weighted comparisons. The chapter [Synthetic Control, DiD, and TASC](synthetic-control-did-tasc.qmd) covers both, with the California Proposition 99 example.\n\n## Summary\n\nDiD replaces unconfoundedness with parallel trends and no anticipation. The untreated trend of the treated group is taken from the control group. With staggered timing, a single TWFE coefficient averages over comparisons that can use already-treated units as controls. ETWFE fixes this by giving each cohort its own effect in each period and then aggregating. A count outcome calls for the Poisson version, which assumes parallel trends on the log scale. Spillovers, persistent outcomes and a failure of parallel trends each need their own tools: interference-robust DiD, dynamic panels, and synthetic control or synthetic DiD, which the next chapter takes up.\n\nOn the minimum-wage data, ETWFE gives an ATT of $-0.0506$ (0.0125). On Wooldridge's simulated panel it returns 3.67 against a true 3.677. In the count simulation, Poisson ETWFE gives 3.62 (0.34) counts against a true 3.698, while linear ETWFE on $\\log(Y+1)$ returns 0.40, a number on a different scale.\n\n",
    "supporting": [
      "did_files/figure-pdf"
    ],
    "filters": []
  }
}