<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>19&nbsp; Recentered Formula Instruments – Causal Econometrics with Julia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./poisson-iv.html" rel="next">
<link href="./shift-share-iv.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6eb2a311e0ae5a9b436ea9f7e52955e6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
try {
  if (window.localStorage) {
    window.localStorage.setItem("quarto-reader-mode", "false");
  }
} catch (e) {}
</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./did.html">Designs</a></li><li class="breadcrumb-item"><a href="./recentered-instruments.html"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Recentered Formula Instruments</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Causal Econometrics with Julia</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://xiangao.github.io/" title="Xiang Ao home" class="quarto-navigation-tool px-1" aria-label="Xiang Ao home"><i class="bi bi-house-door-fill"></i></a>
    <a href="https://xiangao.github.io/books.html" title="Other books" class="quarto-navigation-tool px-1" aria-label="Other books"><i class="bi bi-book"></i></a>
    <a href="https://github.com/xiangao/causal_econometrics_julia/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Identification</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./identification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Identification &amp; Potential Outcomes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-estimands.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Five Estimands on One DGP</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./graphs-identification-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">DAGs, ADMGs, Identification, and Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./smoking-cessation-graphs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Applied Graph Workflow: Smoking Cessation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sensitivity-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sensitivity Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Estimation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Estimation: RA, IPW, AIPW and IPWRA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./matching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Matching Estimators</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nonparametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Nonparametric Causal Methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./heterogeneous-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Heterogeneous Treatment Effects with Machine Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./continuous-treatments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Continuous and Multivalued Treatments</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayesian-causal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Bayesian Causal Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./distributional-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Distributional Treatment Effects</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Designs</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./did.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Difference-in-Differences</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./did-continuous.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">DiD with Continuous Treatment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./synthetic-control-did-tasc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Synthetic Control, DiD, and TASC</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randomization-inference-sc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Randomization Inference for Synthetic Control</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./iv-rdd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">IV &amp; Regression Discontinuity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./shift-share-iv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Shift-Share Instrumental Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./recentered-instruments.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Recentered Formula Instruments</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./poisson-iv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">IV in Poisson with Fixed Effects</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Longitudinal Causal Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./g-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">G-Methods for Time-Varying Treatments</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Survival &amp; Time-to-Event</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival-causal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Survival Analysis with Causal Inference</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Mediation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Causal Mediation Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Causal Discovery</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-discovery.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Causal Discovery: Observed Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-discovery-latent.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Causal Discovery: Latent Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./graph-to-estimate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">From Graph to Estimate</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendix</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./package-ecosystem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Julia Packages Used in This Book</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./did.html">Designs</a></li><li class="breadcrumb-item"><a href="./recentered-instruments.html"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Recentered Formula Instruments</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Recentered Formula Instruments</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Many treatments are computed from a formula that combines a random shock with non-random exposure. Medicaid eligibility is a state’s rules applied to a person’s income. Import exposure is national industry shocks applied to a region’s industry mix. The Bartik instrument of the previous chapter is one such formula. This chapter covers the general version of Borusyak and Hull <span class="citation" data-cites="borusyak-hull-2023">(<a href="references.html#ref-borusyak-hull-2023" role="doc-biblioref">Borusyak and Hull 2023</a>)</span>, their result on which formula is best <span class="citation" data-cites="borusyak-hull-2026">(<a href="references.html#ref-borusyak-hull-2026" role="doc-biblioref">Borusyak and Hull 2026</a>)</span>, and what both mean for shift-share.</p>
<section id="formula-instruments" class="level2" data-number="19.1">
<h2 data-number="19.1" class="anchored" data-anchor-id="formula-instruments"><span class="header-section-number">19.1</span> Formula instruments</h2>
<p>Unit <span class="math inline">\(i\)</span> has outcome <span class="math inline">\(y_i\)</span> and treatment <span class="math inline">\(x_i\)</span>, with a constant effect <span class="math inline">\(\beta\)</span>:</p>
<p><span id="eq-ri-model"><span class="math display">\[
y_i = \beta x_i + \varepsilon_i .
\tag{19.1}\]</span></span></p>
<p>The treatment is <span class="math inline">\(x_i = h_i(g, w, u)\)</span>, where <span class="math inline">\(h_i\)</span> is a known function, <span class="math inline">\(g\)</span> collects the random shocks, <span class="math inline">\(w\)</span> collects predetermined variables such as income or industry shares, and <span class="math inline">\(u\)</span> collects anything else. The identifying assumption puts all the randomness on the shocks <span class="citation" data-cites="borusyak-hull-2026">(<a href="references.html#ref-borusyak-hull-2026" role="doc-biblioref">Borusyak and Hull 2026</a>, Assumption 1)</span>:</p>
<p><span id="eq-ri-exog"><span class="math display">\[
E[\varepsilon_i \mid g, w] = E[\varepsilon_i \mid w] .
\tag{19.2}\]</span></span></p>
<p>The error may depend on <span class="math inline">\(w\)</span> in any way. Poorer people may have worse outcomes, and regions with more manufacturing may have been declining anyway.</p>
<p>A formula instrument is <span class="math inline">\(z_i = f_i(g, w)\)</span> for a fixed function <span class="math inline">\(f_i\)</span>. Its expected value over the shock draws, holding <span class="math inline">\(w\)</span> fixed, is the expected instrument <span class="math inline">\(\mu_i = E[z_i \mid w]\)</span>. The recentered instrument <span class="math inline">\(\tilde z_i = z_i - \mu_i\)</span> is valid, because by iterated expectations and <a href="#eq-ri-exog" class="quarto-xref">Equation&nbsp;<span>19.2</span></a>,</p>
<p><span class="math display">\[
E[\tilde z_i \varepsilon_i]
= E\big[\tilde z_i\, E[\varepsilon_i \mid w]\big]
= E\big[E[\tilde z_i \mid w]\, E[\varepsilon_i \mid w]\big] = 0 .
\]</span></p>
<p>Without recentering the same steps give <span class="math inline">\(E[z_i \varepsilon_i] = E[\mu_i
E[\varepsilon_i \mid w]]\)</span>, which is not zero when the expected instrument is correlated with the predictable part of the error. Subtracting <span class="math inline">\(\mu_i\)</span> and controlling for <span class="math inline">\(\mu_i\)</span> are equivalent by Frisch–Waugh–Lovell. Computing <span class="math inline">\(\mu_i\)</span> requires the design: how the shocks could have been drawn. We redraw them from that design, or permute them if they are exchangeable, and average the formula over the draws.</p>
<p>Any recentered formula is valid, so we can pick the most precise. <span class="citation" data-cites="borusyak-hull-2026">Borusyak and Hull (<a href="references.html#ref-borusyak-hull-2026" role="doc-biblioref">2026</a>, Theorem 1)</span> show it starts from the best prediction of the treatment, recentered:</p>
<p><span id="eq-ri-optimal"><span class="math display">\[
\tilde z = E[x \mid g, w] - E[x \mid w] .
\tag{19.3}\]</span></span></p>
<p>The full optimal instrument adds two refinements, partly controlling for the predictable part of the error and GLS weighting, which need a model of the error. The authors drop them. Their algorithm predicts the treatment from its formula, recenters the prediction by redrawing the shocks, and uses the result as the instrument. When <span class="math inline">\(x_i\)</span> depends only on <span class="math inline">\((g, w)\)</span>, the prediction is <span class="math inline">\(x_i\)</span> itself.</p>
</section>
<section id="shift-share-as-a-formula-instrument" class="level2" data-number="19.2">
<h2 data-number="19.2" class="anchored" data-anchor-id="shift-share-as-a-formula-instrument"><span class="header-section-number">19.2</span> Shift-share as a formula instrument</h2>
<p>The Bartik instrument <span class="math inline">\(B_\ell = \sum_k s_{\ell k} g_k\)</span> of <a href="shift-share-iv.html#eq-shift-share-iv-1" class="quarto-xref">Equation&nbsp;<span>18.2</span></a> is the linear formula, shares times shocks. It differs from <a href="#eq-ri-optimal" class="quarto-xref">Equation&nbsp;<span>19.3</span></a> in two ways.</p>
<p>The first is recentering. Suppose the industry shocks are exchangeable within period <span class="math inline">\(t\)</span>, with mean <span class="math inline">\(\bar g_t\)</span>, and let <span class="math inline">\(S_\ell = \sum_k s_{\ell k}\)</span> be region <span class="math inline">\(\ell\)</span>’s sum of shares. Then</p>
<p><span id="eq-ri-ss-mu"><span class="math display">\[
\mu_\ell = S_\ell\, \bar g_t .
\tag{19.4}\]</span></span></p>
<p>If the shares sum to one, <span class="math inline">\(\mu_\ell = \bar g_t\)</span> is common to all regions and period effects absorb it, so Bartik is already recentered. If they are incomplete, as with manufacturing shares, heavily manufacturing regions get a large instrument in every draw, and Bartik is biased unless we control for <span class="math inline">\(S_\ell\)</span> interacted with period <span class="citation" data-cites="borusyak-hull-jaravel-2022">(<a href="references.html#ref-borusyak-hull-jaravel-2022" role="doc-biblioref">Borusyak, Hull, and Jaravel 2022</a>)</span>.</p>
<p>The second is the formula. Take two regions with half their employment in electronics, and an import shock to electronics. Region A’s plants compete with Chinese imports. Region B’s make military components and do not. Bartik gives both half the shock, but only A’s import competition rises, so the instrument varies where the treatment does not. The best predictor gives A half the shock and B nothing, then recenters each by its own expected value. Both instruments are valid, and the second has the stronger first stage. When the treatment really is shares times shocks, the best predictor is Bartik itself and the two differ only by recentering. The formula matters when the treatment has more structure than Bartik uses: eligibility rules, export exposure, transport networks, nonlinear indices.</p>
<div id="tbl-ri-compare" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ri-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;19.1: Shift-share and recentered formula instruments.
</figcaption>
<div aria-describedby="tbl-ri-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 30%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Shift-share (Bartik)</th>
<th>Recentered formula instrument</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Formula</td>
<td>Shares times shocks</td>
<td>Best prediction of the treatment</td>
</tr>
<tr class="even">
<td>Expected instrument</td>
<td>Usually not subtracted</td>
<td>Subtracted, or controlled for</td>
</tr>
<tr class="odd">
<td>Shock design</td>
<td>Implicit</td>
<td>Written down to compute <span class="math inline">\(\mu_\ell\)</span></td>
</tr>
<tr class="even">
<td>Inputs</td>
<td>Shares and shocks</td>
<td>Treatment formula and shock design</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The formula instrument needs more inputs: the treatment’s formula and an explicit shock design. With heterogeneous effects, different instruments weight units differently, so a gain in precision is a gain for a different weighted average <span class="citation" data-cites="borusyak-hull-2026">(<a href="references.html#ref-borusyak-hull-2026" role="doc-biblioref">Borusyak and Hull 2026</a>, Proposition D1)</span>.</p>
<section id="why-recenter" class="level3" data-number="19.2.1">
<h3 data-number="19.2.1" class="anchored" data-anchor-id="why-recenter"><span class="header-section-number">19.2.1</span> Why recenter</h3>
<p>Bartik needs one of two assumptions. If the shares are as good as random given the controls <span class="citation" data-cites="goldsmith-pinkham-sorkin-swift-2020">(<a href="references.html#ref-goldsmith-pinkham-sorkin-swift-2020" role="doc-biblioref">Goldsmith-Pinkham, Sorkin, and Swift 2020</a>)</span>, Bartik is valid as it stands and recentering is not needed. If only the shocks are random <span class="citation" data-cites="borusyak-hull-jaravel-2022">(<a href="references.html#ref-borusyak-hull-jaravel-2022" role="doc-biblioref">Borusyak, Hull, and Jaravel 2022</a>)</span>, the shares may be correlated with the error. Writing each shock as the mean shock plus a deviation splits the instrument in two:</p>
<p><span id="eq-ri-bartik-split"><span class="math display">\[
B_\ell = S_\ell\, \bar g_t + \sum_k s_{\ell k}\,(g_k - \bar g_t) .
\tag{19.5}\]</span></span></p>
<p>The first part is the expected instrument of <a href="#eq-ri-ss-mu" class="quarto-xref">Equation&nbsp;<span>19.4</span></a>. It depends only on how much exposure the region has, so with incomplete shares a region with more exposure gets a larger value in every draw, and this part is correlated with the error whenever exposure is. The second part depends on whether the region’s industries received larger or smaller shocks than average. If the shocks are independent of the shares and the errors, the deviations average to zero whatever the shares are, so this part is uncorrelated with the error. Recentering keeps only the second part. When the shares sum to one, the first part is <span class="math inline">\(\bar g_t\)</span> for every region and the period effects absorb it.</p>
<p>This gives the formula instrument four advantages. Its validity rests only on the shocks, such as a policy choice or a foreign supply shock, which are often easier to defend than the shares. The design has to be written down, so the assumption is explicit and can be varied, as the two ADH designs below show. The instrument can use exposure to gain power, because the best predictor tracks the treatment more closely than a shock-only index. And it is not tied to a linear formula or to independent units: it covers eligibility rules, networks and nonlinear indices, with shocks shared by many units.</p>
</section>
</section>
<section id="simulation" class="level2" data-number="19.3">
<h2 data-number="19.3" class="anchored" data-anchor-id="simulation"><span class="header-section-number">19.3</span> Simulation</h2>
<p>The aim is to compare a shock-only instrument with the recentered treatment when we know the true effect. There are 50 states and 10,000 people. Person <span class="math inline">\(i\)</span> lives in state <span class="math inline">\(s(i)\)</span> and has income <span class="math inline">\(\text{inc}_i\)</span>, in multiples of the poverty line, drawn from a log-normal distribution with median 1.4. The shock is the states’ policy: each state <span class="math inline">\(k\)</span> draws an eligibility threshold <span class="math inline">\(T_k\)</span> from <span class="math inline">\(\{0.5, 1, 1.38, 2\}\)</span>, each value with probability 1/4, independently across states. Eligibility and the outcome are</p>
<p><span id="eq-ri-dgp"><span class="math display">\[
x_i = 1[\text{inc}_i &lt; T_{s(i)}], \qquad
y_i = 0.3\, x_i + \varepsilon_i, \qquad
\varepsilon_i = -0.5 \log \text{inc}_i + \alpha_{s(i)} + \nu_i ,
\tag{19.6}\]</span></span></p>
<p>where <span class="math inline">\(\alpha_k \sim N(0, 0.3^2)\)</span> is a state effect and <span class="math inline">\(\nu_i \sim N(0, 1)\)</span>. The true effect is 0.3. In the notation of <a href="#eq-ri-exog" class="quarto-xref">Equation&nbsp;<span>19.2</span></a>, the shocks <span class="math inline">\(g\)</span> are the 50 thresholds and the predetermined variables <span class="math inline">\(w\)</span> are the incomes and states. Poorer people are more often eligible and have higher errors, so eligibility is correlated with the error through income and OLS is biased upward. The thresholds are drawn independently of incomes and errors, so <a href="#eq-ri-exog" class="quarto-xref">Equation&nbsp;<span>19.2</span></a> holds.</p>
<p>Expected eligibility <span class="math inline">\(\mu_i\)</span> is the probability that person <span class="math inline">\(i\)</span> is eligible over the possible thresholds, holding income fixed. It is the share of the four thresholds above their income: 1 below 0.5, 0.75 between 0.5 and 1, 0.5 between 1 and 1.38, 0.25 between 1.38 and 2, and 0 above 2. It depends on income only, because every state draws from the same four values. Given income, the recentered treatment <span class="math inline">\(x_i - \mu_i\)</span> moves only with the draw, which is why it is exogenous. A person with income 1.2 has <span class="math inline">\(\mu_i = 0.5\)</span>. The instrument is 0.5 if their state drew 1.38 or 2 and −0.5 if it drew 0.5 or 1, with equal chance whatever their error. People below 0.5 or above 2 always have zero and carry no identifying variation.</p>
<p>We compare four estimators, all with standard errors clustered by state.</p>
<ol type="1">
<li>OLS of <span class="math inline">\(y_i\)</span> on <span class="math inline">\(x_i\)</span>. This is the same as instrumenting <span class="math inline">\(x_i\)</span> with itself, the best predictor without recentering. It is biased.</li>
<li>The simulated instrument of <span class="citation" data-cites="currie-gruber-1996">Currie and Gruber (<a href="references.html#ref-currie-gruber-1996" role="doc-biblioref">1996</a>)</span>. They apply each state’s rules to one fixed national sample and use the share of that sample who would be eligible as the state’s instrument. The same population is run through every state’s rules, so the instrument measures the generosity of the rules and not the composition of the state’s residents. Here the national sample is all 10,000 people, and everyone in a state gets the same value. It is valid.</li>
<li>The recentered treatment, instrumenting <span class="math inline">\(x_i\)</span> with <span class="math inline">\(x_i - \mu_i\)</span>. It varies within states, among people whose income lies between the lowest and highest thresholds. It is valid.</li>
<li>OLS of <span class="math inline">\(y_i\)</span> on <span class="math inline">\(x_i\)</span> and <span class="math inline">\(\mu_i\)</span>. Instrumenting <span class="math inline">\(x_i\)</span> with <span class="math inline">\(x_i - \mu_i\)</span> while controlling for <span class="math inline">\(\mu_i\)</span> reduces to this regression <span class="citation" data-cites="borusyak-hull-2026">(<a href="references.html#ref-borusyak-hull-2026" role="doc-biblioref">Borusyak and Hull 2026</a>, footnote 8)</span>, so it is the controlled form of 3. It is valid.</li>
</ol>
<p>The Monte Carlo is design-based. We generate the people once: their incomes, states and errors are the same in every replication. In each of 1,000 replications we draw new thresholds for the 50 states, recompute eligibility and outcomes, and fit the four estimators. The only randomness across replications is the policy draw, which is what the identifying assumption treats as random, so the spread of the estimates across replications measures each estimator’s precision under that design. The people and the 1,000 × 50 thresholds are stored as CSVs so the Julia companion computes the same numbers.</p>
<div id="cell-ri-mc" class="cell" data-cache="true" data-execution_count="2">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>people <span class="op">=</span> CSV.<span class="fu">read</span>(<span class="st">"data/recenter_people.csv"</span>, DataFrame)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>draws  <span class="op">=</span> <span class="fu">Matrix</span>(CSV.<span class="fu">read</span>(<span class="st">"data/recenter_policy_draws.csv"</span>, DataFrame)[<span class="op">:</span>, <span class="fl">2</span><span class="op">:</span><span class="kw">end</span>])</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>pool <span class="op">=</span> [<span class="fl">0.5</span>, <span class="fl">1.0</span>, <span class="fl">1.38</span>, <span class="fl">2.0</span>]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>beta_true <span class="op">=</span> <span class="fl">0.3</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>mu    <span class="op">=</span> [<span class="fu">mean</span>(v <span class="op">.&lt;</span> pool) for v <span class="kw">in</span> people.income]   <span class="co"># expected eligibility</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>gener <span class="op">=</span> [<span class="fu">mean</span>(people.income <span class="op">.&lt;</span> t) for t <span class="kw">in</span> pool]    <span class="co"># state generosity</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">coef_x</span>(f)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    i <span class="op">=</span> <span class="fu">findfirst</span>(<span class="op">==</span>(<span class="st">"x"</span>), <span class="fu">coefnames</span>(f))</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="fu">coef</span>(f)[i], <span class="fu">stderror</span>(f)[i]</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="kw">const</span> CL <span class="op">=</span> Vcov.<span class="fu">cluster</span>(<span class="op">:</span>state)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">one_draw</span>(r)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    thr <span class="op">=</span> draws[r, people.state]</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> <span class="fu">copy</span>(people)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    d.x     <span class="op">=</span> <span class="fu">Float64</span>.(d.income <span class="op">.&lt;</span> thr)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    d.y     <span class="op">=</span> beta_true <span class="op">.*</span> d.x <span class="op">.+</span> d.eps</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    d.z_sim <span class="op">=</span> gener[[<span class="fu">findfirst</span>(<span class="op">==</span>(t), pool) for t <span class="kw">in</span> thr]]</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    d.z_rc  <span class="op">=</span> d.x <span class="op">.-</span> mu</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    d.mu    <span class="op">=</span> mu</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    fits <span class="op">=</span> (<span class="fu">feols</span>(d, <span class="pp">@formula</span>(y <span class="op">~</span> x), vcov <span class="op">=</span> CL),</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>            <span class="fu">feiv</span>(d, <span class="pp">@formula</span>(y <span class="op">~</span> <span class="fl">1</span>), endo <span class="op">=</span> <span class="op">:</span>x, inst <span class="op">=</span> <span class="op">:</span>z_sim, vcov_type <span class="op">=</span> CL),</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>            <span class="fu">feiv</span>(d, <span class="pp">@formula</span>(y <span class="op">~</span> <span class="fl">1</span>), endo <span class="op">=</span> <span class="op">:</span>x, inst <span class="op">=</span> <span class="op">:</span>z_rc, vcov_type <span class="op">=</span> CL),</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>            <span class="fu">feols</span>(d, <span class="pp">@formula</span>(y <span class="op">~</span> x <span class="op">+</span> mu), vcov <span class="op">=</span> CL))</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    r2 <span class="op">=</span> [<span class="cn">NaN</span>, <span class="fu">cor</span>(d.x, d.z_sim)<span class="op">^</span><span class="fl">2</span>, <span class="fu">cor</span>(d.x, d.z_rc)<span class="op">^</span><span class="fl">2</span>, <span class="cn">NaN</span>]</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [<span class="fu">collect</span>(<span class="fu">coef_x</span>(f)) for f <span class="kw">in</span> fits], r2</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>R <span class="op">=</span> <span class="fu">size</span>(draws, <span class="fl">1</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>est <span class="op">=</span> <span class="fu">zeros</span>(R, <span class="fl">4</span>); se <span class="op">=</span> <span class="fu">zeros</span>(R, <span class="fl">4</span>); r2 <span class="op">=</span> <span class="fu">zeros</span>(R, <span class="fl">4</span>)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="bu">Threads</span>.<span class="pp">@threads</span> <span class="cf">for</span> r <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span>R               <span class="co"># one slot per draw, race-free</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    cs, r2[r, <span class="op">:</span>] <span class="op">=</span> <span class="fu">one_draw</span>(r)</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fl">4</span>; est[r, j], se[r, j] <span class="op">=</span> cs[j]; <span class="cf">end</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="fu">DataFrame</span>(estimator <span class="op">=</span> [<span class="st">"OLS"</span>, <span class="st">"Simulated instrument"</span>, <span class="st">"Recentered treatment"</span>,</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"OLS controlling for mu"</span>],</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>          mean     <span class="op">=</span> <span class="fu">round</span>.(<span class="fu">vec</span>(<span class="fu">mean</span>(est, dims <span class="op">=</span> <span class="fl">1</span>)), digits <span class="op">=</span> <span class="fl">3</span>),</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>          sd       <span class="op">=</span> <span class="fu">round</span>.(<span class="fu">vec</span>(<span class="fu">std</span>(est, dims <span class="op">=</span> <span class="fl">1</span>)), digits <span class="op">=</span> <span class="fl">3</span>),</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>          coverage <span class="op">=</span> <span class="fu">round</span>.(<span class="fu">vec</span>(<span class="fu">mean</span>(<span class="fu">abs</span>.(est <span class="op">.-</span> beta_true) <span class="op">.&lt;=</span> <span class="fl">1.96</span> <span class="op">.*</span> se, dims <span class="op">=</span> <span class="fl">1</span>)),</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>                            digits <span class="op">=</span> <span class="fl">3</span>),</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>          first_stage_R2 <span class="op">=</span> <span class="fu">round</span>.(<span class="fu">vec</span>(<span class="fu">mean</span>(r2, dims <span class="op">=</span> <span class="fl">1</span>)), digits <span class="op">=</span> <span class="fl">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="ri-mc" class="cell-output cell-output-display" data-execution_count="3">
<div><div style="float: left;"><span>4×5 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame caption-top table table-sm table-striped small">
<thead>
<tr class="columnLabelRow header">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">estimator</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">coverage</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">first_stage_R2</th>
</tr>
<tr class="columnLabelRow even">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="String">String</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
</tr>
</thead>
<tbody>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left;">OLS</td>
<td style="text-align: right;">0.637</td>
<td style="text-align: right;">0.049</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">NaN</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: left;">Simulated instrument</td>
<td style="text-align: right;">0.302</td>
<td style="text-align: right;">0.167</td>
<td style="text-align: right;">0.937</td>
<td style="text-align: right;">0.263</td>
</tr>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: left;">Recentered treatment</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">0.086</td>
<td style="text-align: right;">0.927</td>
<td style="text-align: right;">0.589</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">4</td>
<td style="text-align: left;">OLS controlling for mu</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.935</td>
<td style="text-align: right;">NaN</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The table gives each estimator’s mean and standard deviation over the 1,000 replications, the share of clustered 95% intervals that contain 0.3, and the average first-stage <span class="math inline">\(R^2\)</span>. OLS averages 0.637 against a true 0.3, and its intervals never contain 0.3. The three other estimators are centred on 0.3, with coverage of 92.7% to 93.7%, slightly below 95% with 50 clusters. They differ in precision. The simulated instrument has a standard deviation of 0.167 and a first-stage <span class="math inline">\(R^2\)</span> of 0.26. It gives everyone in a state the same value, so it cannot separate people whose eligibility depends on the threshold from people who are eligible, or ineligible, under every threshold. The recentered treatment has a standard deviation of 0.086, half as large, and an <span class="math inline">\(R^2\)</span> of 0.59, because it uses that variation within states. Its controlled form has 0.080.</p>
</section>
<section id="the-china-shock" class="level2" data-number="19.4">
<h2 data-number="19.4" class="anchored" data-anchor-id="the-china-shock"><span class="header-section-number">19.4</span> The China shock</h2>
<p>In ADH the shocks are at the industry-period level: the growth of Chinese imports into eight other high-income countries, per US worker, in 397 manufacturing industries over 1990–2000 and 2000–2007. ADH argue they are exogenous because the growth came from China’s side, through reform, rising productivity and WTO accession, and because imports into other countries do not respond to US demand. The argument is weaker for demand or technology shocks shared by all rich countries, and the identifying variation is concentrated in a few industries such as computers, toys and audio equipment <span class="citation" data-cites="goldsmith-pinkham-sorkin-swift-2020">(<a href="references.html#ref-goldsmith-pinkham-sorkin-swift-2020" role="doc-biblioref">Goldsmith-Pinkham, Sorkin, and Swift 2020</a>)</span>.</p>
<p>All four regressions below use the same instrument and differ only in what they control for. The treatment, US import exposure per worker, is shares times US import growth, and US imports also reflect US demand. Replacing them with the other-country shocks gives the prediction, which is the Bartik instrument itself, so the formula-instrument approach does not change the instrument. It changes the control. The shares, lagged employment shares in the 722 commuting zones, are incomplete, so the expected instrument <span class="math inline">\(\mu_\ell\)</span> varies across zones, and controlling for it is equivalent to subtracting it. Its form depends on the shock design.</p>
<ul>
<li>Design 1: the 397 shocks are exchangeable within each period. Every industry then has the same expected shock, the period mean <span class="math inline">\(\bar g_t\)</span>, which is 4.8 in the first period and 17.3 in the second, and <a href="#eq-ri-ss-mu" class="quarto-xref">Equation&nbsp;<span>19.4</span></a> gives <span class="math inline">\(\mu_\ell = S_\ell \bar g_t\)</span>. Only a zone’s manufacturing intensity is treated as predictable.</li>
<li>Design 2: the shocks are exchangeable only within each of the 20 two-digit SIC sectors in each period. Each industry’s expected shock is its sector’s mean <span class="math inline">\(\bar g_{mt}\)</span>, and <span class="math inline">\(\mu_\ell = \sum_m S_{\ell m} \bar g_{mt}\)</span>, where <span class="math inline">\(S_{\ell m}\)</span> is the zone’s share in sector <span class="math inline">\(m\)</span>. A zone’s sector mix is also treated as predictable: a zone heavy in electronics is expected to receive a large instrument.</li>
</ul>
<p>ADH control for the start-of-period manufacturing share with one coefficient for both periods, which approximates design 1’s <span class="math inline">\(\mu_\ell\)</span>. The second row drops that control, so nothing recenters the instrument, and it is valid only if the shares are exogenous. All fits use ADH’s other controls, census-division effects, population weights and standard errors clustered by state, with the GPSS replication files.</p>
<div id="cell-ri-adh" class="cell" data-cache="true" data-execution_count="3">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>adh <span class="op">=</span> CSV.<span class="fu">read</span>(<span class="st">"data/adh_master.csv"</span>, DataFrame)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>tr  <span class="op">=</span> CSV.<span class="fu">read</span>(<span class="st">"data/adh_shares_triplets.csv"</span>, DataFrame)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>shk <span class="op">=</span> CSV.<span class="fu">read</span>(<span class="st">"data/adh_shocks.csv"</span>, DataFrame)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">by_row</span>(v)                          <span class="co"># sum over industries, by zone</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    out <span class="op">=</span> <span class="fu">zeros</span>(<span class="fu">nrow</span>(adh))</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (r, x) <span class="kw">in</span> <span class="fu">zip</span>(tr.row, v); out[r] <span class="op">+=</span> x; <span class="cf">end</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> out</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>sector  <span class="op">=</span> <span class="fu">string</span>.(shk.sic87dd <span class="op">.÷</span> <span class="fl">100</span>, <span class="st">" "</span>, shk.year)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>g_bar_m <span class="op">=</span> <span class="fu">Dict</span>(s <span class="op">=&gt;</span> <span class="fu">mean</span>(shk.g[sector <span class="op">.==</span> s]) <span class="cf">for</span> s <span class="kw">in</span> <span class="fu">unique</span>(sector))</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>adh.B    <span class="op">=</span> <span class="fu">by_row</span>(tr.share <span class="op">.*</span> shk.g[tr.col])</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>adh.S    <span class="op">=</span> <span class="fu">by_row</span>(tr.share)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>adh.S_t2 <span class="op">=</span> adh.S <span class="op">.*</span> adh.t2</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>adh.t2n  <span class="op">=</span> <span class="fu">Float64</span>.(adh.t2)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>adh.mu2  <span class="op">=</span> <span class="fu">by_row</span>(tr.share <span class="op">.*</span> [g_bar_m[sector[c]] for c <span class="kw">in</span> tr.col])</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>controls <span class="op">=</span> <span class="fu">term</span>(<span class="op">:</span>l_sh_popedu_c) <span class="op">+</span> <span class="fu">term</span>(<span class="op">:</span>l_sh_popfborn) <span class="op">+</span> <span class="fu">term</span>(<span class="op">:</span>l_sh_empl_f) <span class="op">+</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>           <span class="fu">term</span>(<span class="op">:</span>l_sh_routine33) <span class="op">+</span> <span class="fu">term</span>(<span class="op">:</span>l_task_outsource) <span class="op">+</span> <span class="fu">term</span>(<span class="op">:</span>t2n) <span class="op">+</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>           <span class="fu">fe</span>(<span class="op">:</span>division)</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">iv</span>(extra)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    rhs <span class="op">=</span> <span class="fu">isempty</span>(extra) ? controls <span class="op">:</span> <span class="fu">sum</span>(<span class="fu">term</span>.(extra)) <span class="op">+</span> controls</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">feiv</span>(adh, <span class="fu">term</span>(<span class="op">:</span>d_sh_empl_mfg) <span class="op">~</span> rhs, endo <span class="op">=</span> <span class="op">:</span>shock, inst <span class="op">=</span> <span class="op">:</span>B,</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>         weights <span class="op">=</span> <span class="op">:</span>weights, vcov_type <span class="op">=</span> Vcov.<span class="fu">cluster</span>(<span class="op">:</span>statefip))</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>fits <span class="op">=</span> [<span class="st">"Bartik, ADH controls"</span>               <span class="op">=&gt;</span> <span class="fu">iv</span>([<span class="op">:</span>l_shind_manuf_cbp]),</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Bartik, no manufacturing control"</span>   <span class="op">=&gt;</span> <span class="fu">iv</span>(<span class="dt">Symbol</span>[]),</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Bartik, design 1 mu (S x period)"</span>   <span class="op">=&gt;</span> <span class="fu">iv</span>([<span class="op">:</span>S, <span class="op">:</span>S_t2]),</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Bartik, design 2 mu (sector means)"</span> <span class="op">=&gt;</span> <span class="fu">iv</span>([<span class="op">:</span>mu2])]</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="fu">DataFrame</span>(specification <span class="op">=</span> <span class="fu">first</span>.(fits),</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>          estimate <span class="op">=</span> [<span class="fu">round</span>(<span class="fu">coef</span>(f)[<span class="fl">1</span>], digits <span class="op">=</span> <span class="fl">3</span>) for f <span class="kw">in</span> <span class="fu">last</span>.(fits)],</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>          se       <span class="op">=</span> [<span class="fu">round</span>(<span class="fu">stderror</span>(f)[<span class="fl">1</span>], digits <span class="op">=</span> <span class="fl">3</span>) for f <span class="kw">in</span> <span class="fu">last</span>.(fits)])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="ri-adh" class="cell-output cell-output-display" data-execution_count="4">
<div><div style="float: left;"><span>4×3 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame caption-top table table-sm table-striped small">
<thead>
<tr class="columnLabelRow header">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">specification</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">se</th>
</tr>
<tr class="columnLabelRow even">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="String">String</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
</tr>
</thead>
<tbody>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left;">Bartik, ADH controls</td>
<td style="text-align: right;">-0.596</td>
<td style="text-align: right;">0.1</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: left;">Bartik, no manufacturing control</td>
<td style="text-align: right;">-0.712</td>
<td style="text-align: right;">0.083</td>
</tr>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: left;">Bartik, design 1 mu (S x period)</td>
<td style="text-align: right;">-0.267</td>
<td style="text-align: right;">0.087</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">4</td>
<td style="text-align: left;">Bartik, design 2 mu (sector means)</td>
<td style="text-align: right;">-0.144</td>
<td style="text-align: right;">0.117</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The first row reproduces ADH’s −0.596: an increase in import exposure of $1,000 per worker over a decade lowers the manufacturing employment share by about 0.6 percentage points. Without the manufacturing-share control the estimate is −0.712.</p>
<p>Each of the last two rows removes one source of variation. ADH’s estimate partly compares zones with more and less manufacturing across the two periods: because the mean shock more than triples, a manufacturing-heavy zone gets a much larger instrument in the second period whichever industries China hit. Controlling for design 1’s <span class="math inline">\(\mu_\ell\)</span> removes that comparison, and the estimate falls to −0.267 (0.087). ADH’s control is close to <span class="math inline">\(S_\ell\)</span>, with a correlation of 0.92, but one coefficient cannot absorb a term whose slope more than triples between periods. Design 2 also removes the comparison across sectors, such as electronics and toys against food and paper, and the estimate falls to −0.144 (0.117).</p>
<p>Whether the removed comparisons are confounded is the substantive question. If manufacturing-heavy zones declined faster in the 2000s for other reasons, such as automation, the design 1 control is needed and ADH overstate the effect. But the average shock is itself part of the China shock, since Chinese imports rose across nearly all of manufacturing. Designs 1 and 2 treat that average as predictable and use only the variation in which industries China hit harder than average, so they cannot measure an effect that works through manufacturing as a whole. ADH’s −0.596 does use it, and it is valid if the shares are exogenous given the controls. The data cannot tell us which assumption holds. Every estimate is negative, and recentering shows how much of the size depends on the assumption.</p>
</section>
<section id="the-medicaid-application" class="level2" data-number="19.5">
<h2 data-number="19.5" class="anchored" data-anchor-id="the-medicaid-application"><span class="header-section-number">19.5</span> The Medicaid application</h2>
<p><span class="citation" data-cites="borusyak-hull-2026">Borusyak and Hull (<a href="references.html#ref-borusyak-hull-2026" role="doc-biblioref">2026</a>)</span> instrument Medicaid eligibility in the 2014 ACA expansion with actual minus expected eligibility, treating expansion as random within the governor’s party. The first-stage partial <span class="math inline">\(R^2\)</span> rises from 0.01 to 0.80 over the simulated instrument and the standard error on crowd-out falls by 44%. Most of the gain comes from the 18% of the sample whose eligibility the expansion could change; outside it, the recentered instrument is zero, and in the full sample without an exposure control it is less precise than the simulated one <span class="citation" data-cites="borusyak-hull-2026">(<a href="references.html#ref-borusyak-hull-2026" role="doc-biblioref">Borusyak and Hull 2026</a>, Table A4)</span>. Their 2012–2013 placebo on private insurance is −0.011, half the main estimate of −0.023 (Table A2).</p>
</section>
<section id="summary" class="level2" data-number="19.6">
<h2 data-number="19.6" class="anchored" data-anchor-id="summary"><span class="header-section-number">19.6</span> Summary</h2>
<p>Shift-share is one formula instrument, with the formula and the design fixed by convention. Any formula of shocks and exposure is valid once its expected value over the shock design is subtracted, and the most efficient formula is the recentered best prediction of the treatment. Applied to Bartik, this has two consequences. When the shares do not sum to one, the regression must control for the sum of shares times the period’s mean shock. When the treatment depends on the shocks through more than shares times shocks, a prediction built from the treatment’s own formula is a stronger instrument than Bartik. In the ADH data the first consequence alone moves the estimate from −0.60 to −0.27.</p>
<p>For the shift-share construction, the share and shock views, and inference, see the previous chapter, <a href="./shift-share-iv.html">Shift-Share Instrumental Variables</a>.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-borusyak-hull-2023" class="csl-entry" role="listitem">
Borusyak, Kirill, and Peter Hull. 2023. <span>“Nonrandom Exposure to Exogenous Shocks.”</span> <em>Econometrica</em> 91 (6): 2155–85. <a href="https://doi.org/10.3982/ECTA19367">https://doi.org/10.3982/ECTA19367</a>.
</div>
<div id="ref-borusyak-hull-2026" class="csl-entry" role="listitem">
———. 2026. <span>“Optimal Formula Instruments.”</span>
</div>
<div id="ref-borusyak-hull-jaravel-2022" class="csl-entry" role="listitem">
Borusyak, Kirill, Peter Hull, and Xavier Jaravel. 2022. <span>“Quasi-Experimental Shift-Share Research Designs.”</span> <em>Review of Economic Studies</em> 89 (1): 181–213.
</div>
<div id="ref-currie-gruber-1996" class="csl-entry" role="listitem">
Currie, Janet, and Jonathan Gruber. 1996. <span>“Health Insurance Eligibility, Utilization of Medical Care, and Child Health.”</span> <em>Quarterly Journal of Economics</em> 111 (2): 431–66. <a href="https://doi.org/10.2307/2946684">https://doi.org/10.2307/2946684</a>.
</div>
<div id="ref-goldsmith-pinkham-sorkin-swift-2020" class="csl-entry" role="listitem">
Goldsmith-Pinkham, Paul, Isaac Sorkin, and Henry Swift. 2020. <span>“Bartik Instruments: What, When, Why, and How.”</span> <em>American Economic Review</em> 110 (8): 2586–2624.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/xiangao\.github\.io\/causal_econometrics_julia\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./shift-share-iv.html" class="pagination-link" aria-label="Shift-Share Instrumental Variables">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Shift-Share Instrumental Variables</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./poisson-iv.html" class="pagination-link" aria-label="IV in Poisson with Fixed Effects">
        <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">IV in Poisson with Fixed Effects</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions"><ul><li><a href="https://github.com/xiangao/causal_econometrics_julia/edit/main/recentered-instruments.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/xiangao/causal_econometrics_julia/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>