{
  "hash": "2f58558c256dc85859bdc6f38f9e59be",
  "result": {
    "engine": "jupyter",
    "markdown": "# IV & Regression Discontinuity\n\n\n::: {.cell execution_count=2}\n``` {.julia .cell-code}\nusing CairoMakie\nCairoMakie.activate!(type = \"png\")\nusing GraphMakie, Graphs\nusing Distributions, Random, LinearAlgebra\nusing RDRobust\nusing Panelest\nusing Vcov\nusing DataFrames\nusing StatsModels, DataFramesMeta\nimport StatsAPI: coeftable\nusing Printf\nusing CSV\nusing Statistics\nusing RegressionTables\n```\n:::\n\n\nWith an unobserved confounder, unconfoundedness fails. Even a randomized experiment can face this problem through noncompliance: subjects are randomly assigned but some do not comply, so the actually-treated group is self-selected and that selection may be correlated with the outcome.\n\n## Instrumental Variables\n\n### Uncontrolled Confounder\n\nThe graph below is the problem: $c$ is an unobserved common cause of the\ntreatment $w$ and the outcome $y$. There is no adjustment set, because $c$ is\nnot measured.\n\n::: {.cell message='false' execution_count=3}\n\n::: {.cell-output .cell-output-display execution_count=3}\n![](iv-rdd_files/figure-pdf/cell-4-output-1.png){}\n:::\n:::\n\n\n### Why Does IV Work?\n\nAdding $z$ gives a variable that moves $w$ and reaches $y$ only through $w$.\nThe arrow $z \\to w$ is the relevance condition, and the *absence* of any arrow\nfrom $z$ to $y$ or to $c$ is the exclusion restriction and the exogeneity\ncondition. The missing arrows carry the assumptions.\n\n::: {.cell message='false' execution_count=4}\n\n::: {.cell-output .cell-output-display execution_count=4}\n![](iv-rdd_files/figure-pdf/cell-5-output-1.png){}\n:::\n:::\n\n\n### IV Under Potential Outcomes\n\n-   W has two potential outcomes W(1) and W(0), as a function of Z.\n-   Y has two potential outcomes Y(1) and Y(0), as a function of W.\n\nIntention to Treat (ITT) is the average treatment effect of the treatment assignment Z. It is the difference between the average potential outcome under treatment and the average potential outcome under control. It is the average treatment effect of the treatment assignment Z, regardless of whether the subject complies with the assignment.\n\nThere are four possible groups of subjects in the case of binary treatment and binary instrument. The groups are defined by the *potential* treatment status $(W(0), W(1))$ — how the subject would take treatment under each value of the instrument — not by the observed $(Z, W)$:\n\n-   $W(0)=0, W(1)=0$: never-taker\n-   $W(0)=0, W(1)=1$: complier\n-   $W(0)=1, W(1)=0$: defier\n-   $W(0)=1, W(1)=1$: always-taker\n\n|        | W(1)=0 | W(1)=1 |\n|:-------|:-------|:-------|\n| W(0)=0 | N      | C      |\n| W(0)=1 | D      | A      |\n\n: compliance groups\n\nThese four groups (strata) have different causal mechanisms. The compliers and defiers are the groups whose *treatment status* responds to the assignment $Z$ — compliers in the same direction as the assignment, defiers in the opposite direction. The always-takers and never-takers take the same treatment regardless of $Z$.\n\nUnfortunately we cannot identify the compliance group by looking at the data.\n\n| Z   | W   | G    |\n|:----|:----|:-----|\n| 0   | 0   | C, N |\n| 0   | 1   | A, D |\n| 1   | 0   | N, D |\n| 1   | 1   | C, A |\n\n### Assumptions\n\n-   Exclusion restriction: $Y(w, 1) = Y(w,0)$\n-   Exogeneity of instrument: $Z \\perp [W(0),W(1), Y(0), Y(1)]$\n-   Monotonicity (no defiers): $W(0) \\leq W(1)$\n\n### LATE Identification\n\nSince we excluded defiers, and the other two groups (always-takers and never-takers) are not affected by the treatment assignment Z. The only effect we can identify is the treatment effect on the compliers. This is called the Local Average Treatment Effect (LATE).\n\nBelow we write potential outcomes indexed by the instrument, $Y(Z=z)$, rather than by treatment status, $Y(d)$. The exclusion restriction is exactly what licenses this: since $Y(w,1)=Y(w,0)$, $Y$ depends on $Z$ only through $W$, so $Y(Z=z) = Y(W(z), z) = Y(W(z))$ in the usual treatment-indexed notation. For a complier ($W(1)=1, W(0)=0$), this means $Y(Z=1) = Y(1)$ and $Y(Z=0) = Y(0)$, so $E[Y(Z=1)-Y(Z=0) \\mid G=C]$ below is exactly $E[Y(1)-Y(0) \\mid G=C]$, the LATE in treatment-indexed notation.\n\n$$ \\small\n\\begin{aligned}\n& E[Y(Z=1) - Y(Z=0) | G = C] \\\\\n&= \\frac{E[Y(Z=1) - Y(Z=0)]}{P(W(1)=1, W(0)=0)} \\\\\n&= \\frac{E[Y|Z=1] - E[Y|Z=0]}{1-P(W=0|Z=1)-P(W=1|Z=0)} \\text{ (monotonicity rules out D; the A and N shares subtract) } \\\\\n&= \\frac{E[Y|Z=1] - E[Y|Z=0]}{P(W=1|Z=1)-P(W=1|Z=0)} \\\\\n&= \\frac{E[Y|Z=1] - E[Y|Z=0]}{E[W|Z=1]-E[W|Z=0]}\n\\end{aligned}\n$$ {#eq-iv-rdd-1}\n\n### Parametric Models\n\nWith a binary instrument this is exactly the ratio of two OLS coefficients — no linearity assumption is needed, since a regression on a binary regressor just computes the two group means. This is sometimes called the Wald estimator.\n\n$$\n\\begin{aligned}\n\\tau_{LATE} &= \\frac{E[Y|Z=1] - E[Y|Z=0]}{E[W|Z=1]-E[W|Z=0]} \\\\\n&= \\frac{Cov(Y,Z)}{Cov(W,Z)}\n\\end{aligned}\n$$ {#eq-iv-rdd-2}\n\nWhy do covariates help? It is important to separate two assumptions\nhere. Conditioning on covariates $X$ can make the *as-if-random*\n(conditional independence) assumption more credible: the instrument\nmay be unconfounded only within levels of $X$. But the *exclusion\nrestriction* -- that the instrument has no direct effect on the\noutcome -- is a substantive structural assumption that covariates do\nnot generally repair. Adding $X$ removes a direct $Z \\to Y$ path only\nif that path runs entirely through $X$, or if exclusion is conditional\nby design. So covariates help with conditional independence, not with\nexclusion per se.\n\n### Example\n\nWe simulate $n = 10{,}000$ observations. Three variables $(w, m, z)$ are drawn\njointly normal with mean zero and unit variances, so their covariances are also\ntheir correlations: $\\text{corr}(w,m) = 0.36$, $\\text{corr}(w,z) = 0.64$, and\n$\\text{corr}(m,z) = 0$. A fourth variable $u \\sim N(0,1)$ is independent of\neverything. The outcome is $y = w + m + u$.\n\nSo $m$ is the omitted confounder, correlated with the treatment $w$ but not\nwith the instrument $z$, and the true coefficient on $w$ is 1. Because all\nvariances are 1, we can predict the omitted-variable bias exactly: regressing\n$y$ on $w$ alone gives $1 + \\text{Cov}(m,w) = 1.36$.\n\nWe fit three models: OLS of $y$ on $w$, OLS of $y$ on $w$ and $m$, and 2SLS\nusing $z$ as the instrument for $w$.\n\n::: {.cell message='false' execution_count=5}\n``` {.julia .cell-code}\n## DGP: data.y = data.w + data.m + data.u\nRandom.seed!(66)\nnobs = 10000\n## here we have three variables w, m, z.\n## m is the omitted variable; w and m are correlated; z is the instrument,\n## which is correlated with w, but not m. u is independent of everything else.\n## with unit variances, the covariances below ARE the correlations\ncrwm = 0.36; crmz = 0.0; crwz = 0.64\ncovarMat = [1.0  crwm crwz;\n            crwm 1.0  crmz;\n            crwz crmz 1.0]\nmat  = rand(MvNormal(zeros(3), covarMat), nobs)'\ndata = DataFrame(w = mat[:, 1], m = mat[:, 2], z = mat[:, 3])\ndata.u = rand(Normal(0, 1), nobs)\n# dgp\ndata.y = data.w .+ data.m .+ data.u\nlm_biased  = feols(data, @formula(y ~ w))\nlm_full    = feols(data, @formula(y ~ w + m))\ntsls_model = feiv(data, @formula(y ~ 1); endo = :w, inst = :z);\n```\n:::\n\n\n::: {.cell message='false' execution_count=6}\n``` {.julia .cell-code}\n# lm is biased\ndisplay(coeftable(lm_biased))\n# lm_full is good\ndisplay(coeftable(lm_full))\n# tsls is good.\ndisplay(coeftable(tsls_model))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n|             |   Estimate | Std. Error | z value | Pr(>|z|) |\n|:------------|-----------:|-----------:|--------:|:---------|\n| (Intercept) | -0.0116415 |  0.0136663 |   -0.85 |   0.3943 |\n| w           |  1.35705   |  0.0136527 |   99.40 |   <1e-99 |\n:::\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n|             |    Estimate | Std. Error | z value | Pr(>|z|) |\n|:------------|------------:|-----------:|--------:|:---------|\n| (Intercept) | -0.00914669 | 0.00997142 |   -0.92 |   0.3590 |\n| w           |  0.997584   | 0.0106743  |   93.46 |   <1e-99 |\n| m           |  0.998357   | 0.0106525  |   93.72 |   <1e-99 |\n:::\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n|             |    Estimate | Std. Error | z value | Pr(>|z|) |\n|:------------|------------:|-----------:|--------:|:---------|\n| w           |  0.999871   |  0.0219208 |   45.61 |   <1e-99 |\n| (Intercept) | -0.00577212 |  0.0141291 |   -0.41 |   0.6829 |\n:::\n:::\n\n\nOLS on $w$ alone gives 1.3571, matching the predicted 1.36 to two decimals.\nOLS controlling for $m$ gives 0.9976 on $w$ and 0.9984 on $m$, both close to\nthe true 1, which is what we would do if the confounder were observed. 2SLS\ngives 0.9999 with a standard error of 0.0219, recovering the truth without ever\nusing $m$.\n\nNote the cost of instrumenting: the 2SLS standard error is 0.0219 against\n0.0107 for the OLS that controls for $m$, twice as large. The instrument uses\nonly the part of $w$ that $z$ explains, and here that is 41% of its variance.\n\n### Control Function Approach\n\nTwo-stage least squares can be implemented equivalently via the **control function (CF) approach**. Understanding why makes the extension to nonlinear models (next chapter) transparent.\n\n**Algebraic motivation.** Because `w` is endogenous, decompose the structural error:\n\n$$\\varepsilon = \\rho v + \\eta, \\qquad v \\equiv w - E[w \\mid z], \\qquad E(z\\eta) = 0,\\; E(zv) = 0.$$ {#eq-iv-rdd-3}\n\nIf we *knew* $v$, controlling for it directly would eliminate the confounding channel. We don't know $v$, but the first-stage residual $\\hat v = w - \\hat w$ is a consistent estimate. Substituting into the structural equation:\n\n$$y = \\alpha + \\beta w + \\rho\\,\\hat v + \\text{error}.$$ {#eq-iv-rdd-4}\n\nOLS on this **augmented** second stage gives a consistent $\\hat\\beta$ — identical to 2SLS by the Frisch–Waugh–Lovell (FWL) theorem. The coefficient $\\hat\\rho$ on $\\hat v$ doubles as a **Durbin–Wu–Hausman (DWH) endogeneity test**: under $H_0$ (w is exogenous), $\\rho = 0$.\n\n::: {.cell message='false' execution_count=7}\n``` {.julia .cell-code}\nimport StatsBase: coef, stderror, coefnames\npick(m, v, name) = v[findfirst(==(name), coefnames(m))]\n\n# Manual 2SLS, explicitly\nstage1      = feols(data, @formula(w ~ z))\ndata.w_hat  = data.w .- stage1.residuals\ntsls_manual = feols(data, @formula(y ~ w_hat))\n\n# Control function: first-stage residual v_hat in the augmented regression\ndata.v_hat = stage1.residuals\nlm_cf      = feols(data, @formula(y ~ w + v_hat))\n\n# Compare β̂_w from manual 2SLS and CF — should be identical by FWL\n@printf(\"Manual 2SLS   beta_w = %.8f\\n\", pick(tsls_manual, coef(tsls_manual), \"w_hat\"))\n@printf(\"Control funct beta_w = %.8f\\n\", pick(lm_cf, coef(lm_cf), \"w\"))\n\n# DWH endogeneity test: t-stat on v_hat\nrho, rho_se = pick(lm_cf, coef(lm_cf), \"v_hat\"), pick(lm_cf, stderror(lm_cf), \"v_hat\")\n@printf(\"DWH test on v_hat: coef = %.4f  se = %.4f  t = %.3f  p = %.4g\\n\",\n        rho, rho_se, rho / rho_se, 2 * ccdf(Normal(), abs(rho / rho_se)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nManual 2SLS   beta_w = 0.99987086\nControl funct beta_w = 0.99987086\nDWH test on v_hat: coef = 0.6100  se = 0.0270  t = 22.563  p = 9.987e-113\n```\n:::\n:::\n\n\nBoth routes give $\\hat\\beta_w = 0.99987086$, agreeing to all eight printed\ndigits, which confirms FWL. The coefficient on $\\hat v$ is 0.6100 with a\nstandard error of 0.0270, so $t = 22.6$ and $H_0\\!:\\rho = 0$ is rejected: `w`\nis endogenous. That coefficient also has a value we can derive. With\n$\\varepsilon = m + u$ and $v = w - 0.64z$, we have\n$\\text{Cov}(\\varepsilon, v) = \\text{Cov}(m,w) = 0.36$ and\n$\\text{Var}(v) = 1 - 0.64^2 = 0.5904$, so $\\rho = 0.36/0.5904 = 0.610$. The\nestimate matches it to three decimals. One caveat: the OLS standard errors from the augmented regression are not valid for $\\hat\\beta$ ($\\hat v$ is a generated regressor; the DWH test is fine because under $H_0$ the first-stage estimation error does not matter). Use 2SLS standard errors, or bootstrap the two stages jointly as we do in the Poisson IV chapter.\n\n**Why FWL fails in nonlinear models.** FWL is a property of linear projections; once we replace OLS with Poisson or Probit, the estimator is no longer a linear projection and the partialling-out logic does not apply. In a nonlinear second stage, $\\hat v$ must enter *inside* the link function (e.g. $\\exp(\\mathbf{x}\\boldsymbol\\beta + \\rho \\hat v)$), which requires a structural assumption beyond instrument exogeneity. This is the subject of the next chapter.\n\n## When 2SLS with Covariates Is *Actually* LATE\n\nThe LATE identification above is clean because we have no covariates. The Wald estimator gives us LATE, full stop. But in practice we usually add covariates to defend conditional exogeneity:\n\n$$\nY = \\beta W + \\gamma^\\top X + U, \\qquad W = \\pi Z + \\delta^\\top X + V.\n$$ {#eq-iv-rdd-5}\n\nDoes 2SLS on this still give us a LATE? @angrist-pischke-2009 say it gives a weighted average of covariate-specific LATEs. @blandhol-et-al-2025 show that this is generally not true.\n\n### Why the Linear Specification Hides an Assumption\n\nBy Frisch-Waugh-Lovell, the IV estimand is\n\n$$\n\\beta_{iv} = \\frac{E[Y \\tilde Z]}{E[W \\tilde Z]}, \\qquad \\tilde Z = Z - L[Z \\mid X],\n$$ {#eq-iv-rdd-6}\n\nwhere $L[Z \\mid X]$ is the **linear** projection of $Z$ on $X$. So $\\tilde Z$ is the part of $Z$ that a linear regression on $X$ cannot explain.\n\nWhat if the true $E[Z \\mid X]$ is not linear in $X$? Then $L[Z \\mid X] \\neq E[Z \\mid X]$, and the residual instrument $\\tilde Z$ still picks up some of the conditional mean. The IV estimand then mixes treatment effects across compliance groups. @blandhol-et-al-2025 prove that $\\beta_{iv}$ is a non-negatively weighted average of conditional LATEs only if the rich covariates condition holds:\n\n$$\nL[Z \\mid X] = E[Z \\mid X].\n$$ {#eq-iv-rdd-7}\n\nThis is a parametric assumption about $E[Z \\mid X]$. It is implicit in the linear-in-$X$ specification, and it is rarely defended. When it fails, $\\beta_{iv}$ picks up treatment effects for always-takers as well as compliers, and some always-taker terms enter with negative weight.\n\n\"2SLS with covariates estimates LATE\" is true only if $X$ enters saturated (one dummy per cell), or the true $E[Z \\mid X]$ happens to be linear in $X$.\n\n### A Simulation\n\nWe build a DGP where $E[Z \\mid X]$ is strongly nonlinear in $X$, so the\nlinear-in-$X$ specification has to fail, and then compare four estimators\nagainst the true LATE.\n\nWe draw $n = 8000$ observations with a single covariate $X \\sim U(-1,1)$. The\ninstrument is $Z \\sim \\text{Bernoulli}(p_Z(X))$ with\n$p_Z(X) = \\Lambda(0.3 + X + 2\\sin(2.5\\pi X))$ --- the sine term is what a linear\nprojection cannot reproduce. Potential treatments come from one uniform draw\n$U$ compared against two thresholds, $T_0 = \\mathbb{1}\\{U < \\Lambda(-1.6+X)\\}$\nand $T_1 = \\mathbb{1}\\{U < \\min(\\Lambda(-0.4+X)+0.2,\\, 0.95)\\}$, so\n$T_1 \\ge T_0$ and monotonicity holds by construction. Observed treatment is\n$W = ZT_1 + (1-Z)T_0$. The effect is heterogeneous in $X$, $\\tau(X) = 0.5+1.5X$,\nand the potential outcomes are $Y(0) = 1 + 2X + 0.8X^2 + \\varepsilon$ with\n$\\varepsilon \\sim N(0,1)$ and $Y(1) = Y(0) + \\tau(X)$.\n\nTwo features matter. $X$ enters both the instrument propensity and the\ntreatment thresholds, so $Z$ is exogenous only conditional on $X$. And\n$\\tau$ depends on $X$, so which units the instrument moves determines the\nanswer.\n\n::: {.cell cache='true' message='false' execution_count=8}\n``` {.julia .cell-code}\nusing MLJ\nusing DecisionTree\nusing Random\nusing Statistics\nusing LinearAlgebra\n\nRandom.seed!(13)\nn = 8000\nplogis(z) = 1 / (1 + exp(-z))\n\n# Single covariate on [-1, 1]\nX = 2 .* rand(n) .- 1\n\n# True conditional mean of Z is wildly nonlinear in X.\n# A linear projection L[Z|X] cannot reproduce this.\npZ_true = plogis.(0.3 .+ 1.0 .* X .+ 2.0 .* sin.(2.5 .* π .* X))\nZ       = Int.(rand(n) .< pZ_true)\n\n# Potential treatment states with monotonicity (T1 >= T0).\n# X enters the propensity, so X confounds W <-> Y.\nU  = rand(n)\np0 = plogis.(-1.6 .+ 1.0 .* X)\np1 = min.(plogis.(-0.4 .+ 1.0 .* X) .+ 0.2, 0.95)\nT0 = Int.(U .< p0)\nT1 = Int.(U .< p1)\nW  = ifelse.(Z .== 1, T1, T0)\n\nG  = [t1 == 1 && t0 == 1 ? :AT :\n      t1 == 0 && t0 == 0 ? :NT : :CP\n      for (t1, t0) in zip(T1, T0)]\n\n# Heterogeneous treatment effect — varies with X\nτ  = 0.5 .+ 1.5 .* X\nY0 = 1.0 .+ 2.0 .* X .+ 0.8 .* X .^ 2 .+ randn(n)\nY1 = Y0 .+ τ\nY  = ifelse.(W .== 1, Y1, Y0)\n\ntrue_LATE = mean(τ[G .== :CP])\n@printf(\"Compliance shares  AT=%.3f  CP=%.3f  NT=%.3f\\n\",\n        mean(G .== :AT), mean(G .== :CP), mean(G .== :NT))\n@printf(\"True unconditional LATE = %.3f\\n\", true_LATE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCompliance shares  AT=0.188  CP=0.425  NT=0.388\nTrue unconditional LATE = 0.617\n```\n:::\n:::\n\n\nThe compliance shares are 18.8% always-takers, 42.5% compliers and 38.8%\nnever-takers, and the true LATE, the mean of $\\tau$ over compliers, is 0.617.\n\nWe now compare four estimators against it: the unconditional Wald ratio, 2SLS\nwith $X$ entered linearly, 2SLS with a degree-7 polynomial in $X$, and DDML\nPLIV with random-forest nuisance learners. Julia has no counterpart of R's\n`DoubleML` package, so we write the PLIV cross-fitting out.\n\n::: {.cell cache='true' message='false' execution_count=9}\n``` {.julia .cell-code}\n# Helper: TSLS via the matrix expression (Xmat is the exogenous matrix incl.\n# constant). Returns the coefficient on W and its conventional standard error.\nfunction tsls_matrix(Y, W, Z, Xmat)\n    Wmat = hcat(W, Xmat)\n    Zmat = hcat(Z, Xmat)\n    What = Zmat * ((Zmat' * Zmat) \\ (Zmat' * Wmat))\n    β    = (What' * Wmat) \\ (What' * Y)\n    e    = Y .- Wmat * β\n    σ2   = sum(abs2, e) / (length(Y) - size(Wmat, 2))\n    return β[1], sqrt(σ2 * inv(What' * What)[1, 1])\nend\n\n# (a) Wald — biased: Z is not unconditionally exogenous because X confounds.\nwald = (mean(Y[Z .== 1]) - mean(Y[Z .== 0])) /\n       (mean(W[Z .== 1]) - mean(W[Z .== 0]))\n\n# (b) TSLS with X entered linearly — the textbook spec.\nb_lin, se_lin = tsls_matrix(Float64.(Y), Float64.(W), Float64.(Z), hcat(ones(n), X))\n\n# (c) TSLS with a rich basis (polynomial up to degree 7) — closer to saturation.\nb_poly, se_poly = tsls_matrix(Float64.(Y), Float64.(W), Float64.(Z),\n                              hcat([X .^ k for k in 0:7]...))\n\n# (d) DDML PLIV with random-forest nuisance learners and 5-fold cross-fitting.\nRandomForestRegressor = @load RandomForestRegressor pkg=DecisionTree verbosity=0\nlearner = RandomForestRegressor(n_trees = 500, max_depth = 5)\n\nnsplits = 5\ns       = shuffle(1:n)\nfolds   = [s[1 + floor(Int, (k-1)*n/nsplits) : floor(Int, k*n/nsplits)]\n           for k in 1:nsplits]\n\nmY = zeros(n); mW = zeros(n); mZ = zeros(n)\nXtab = DataFrame(X = X)\nfor fold_idx in 1:nsplits\n    test  = folds[fold_idx]\n    train = setdiff(1:n, test)\n    for (out, dest) in ((Y, mY), (W, mW), (Z, mZ))\n        mach = machine(learner, Xtab[train, :], Float64.(out[train]))\n        MLJ.fit!(mach, verbosity = 0)\n        dest[test] = MLJ.predict(mach, Xtab[test, :])\n    end\nend\n\nrY = Y .- mY; rW = W .- mW; rZ = Z .- mZ\nb_pliv  = sum(rZ .* rY) / sum(rZ .* rW)\nψ       = (rY .- b_pliv .* rW) .* rZ              # PLIV score\nse_pliv = sqrt(mean(ψ .^ 2) / mean(rW .* rZ)^2 / n)\n\nresults = DataFrame(\n    Estimator = [\"True LATE\",\n                 \"Wald (no covariates)\",\n                 \"TSLS, X linear\",\n                 \"TSLS, poly(X, 7)\",\n                 \"DDML PLIV (cross-fit, random forest)\"],\n    Estimate  = round.([true_LATE, wald, b_lin, b_poly, b_pliv], digits = 3),\n    SE        = [missing, missing, round(se_lin, digits = 3), round(se_poly, digits = 3),\n                 round(se_pliv, digits = 3)]\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```{=tex}\n\\begin{tabular}{r|ccc}\n\t& Estimator & Estimate & SE\\\\\n\t\\hline\n\t& String & Float64 & Float64?\\\\\n\t\\hline\n\t1 & True LATE & 0.617 & \\emph{missing} \\\\\n\t2 & Wald (no covariates) & 1.91 & \\emph{missing} \\\\\n\t3 & TSLS, X linear & 0.552 & 0.059 \\\\\n\t4 & TSLS, poly(X, 7) & 0.585 & 0.067 \\\\\n\t5 & DDML PLIV (cross-fit, random forest) & 0.582 & 0.07 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\nThe linear-in-$X$ 2SLS does not recover the true LATE — and neither do the more flexible versions. Two things are going on, and the standard errors in the table help separate them. First, the estimands differ: for this DGP the linear-projection 2SLS converges to 0.55, and the polynomial 2SLS and DDML PLIV converge to approximately $\\beta_{rich} = 0.58$ (computable by integrating the weight formula below), all below the LATE of 0.617 — a real but modest gap that persists at any sample size. Second, sampling noise: the SEs are 0.06 to 0.07, and in this draw each estimate lands within 0.01 of its own estimand, at 0.552, 0.585 and 0.582, so here the whole gap to the LATE is the difference in estimands. The Wald estimator is far off for a different reason entirely, at 1.910 against a truth of 0.617: $Z$ is not unconditionally exogenous, and Wald has no way to use $X$.\n\nWhat are the polynomial 2SLS and DDML PLIV estimating, if not LATE? PLIV targets $\\beta_{rich}$, a weighted average of conditional LATEs with weights proportional to $\\text{Var}(Z \\mid X) \\cdot P(\\text{complier} \\mid X)$; the polynomial 2SLS targets nearly the same quantity (a degree-7 polynomial cannot fully reproduce this $E[Z \\mid X]$, so its estimand is a misspecified-projection variant sitting just below $\\beta_{rich}$). These are non-negatively weighted, so weakly causal. But they are not the unconditional LATE we usually want.\n\n### Diagnostic: RESET on Z ~ X\n\nRich covariates says $E[Z \\mid X]$ is linear in $X$. That is exactly the null of Ramsey's RESET test [@ramsey-1969]. We can apply it to a regression of $Z$ on $X$ and see whether higher-order terms of $X$ are jointly significant.\n\n::: {.cell cache='true' message='false' execution_count=10}\n``` {.julia .cell-code}\nusing GLM\n# RESET with type = \"regressor\", power = 2:3: F-test of X^2 and X^3 added to Z ~ X\ndf_reset       = DataFrame(Z = Float64.(Z), X = X, X2 = X .^ 2, X3 = X .^ 3)\nm_restricted   = lm(@formula(Z ~ X), df_reset)\nm_unrestricted = lm(@formula(Z ~ X + X2 + X3), df_reset)\nrss_r, rss_u   = sum(abs2, residuals(m_restricted)), sum(abs2, residuals(m_unrestricted))\nq, k_u         = 2, 4\nF_stat         = ((rss_r - rss_u) / q) / (rss_u / (n - k_u))\n@printf(\"RESET = %.2f, df1 = %d, df2 = %d, p-value = %.3g\\n\",\n        F_stat, q, n - k_u, ccdf(FDist(q, n - k_u), F_stat))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRESET = 131.57, df1 = 2, df2 = 7996, p-value = 6.03e-57\n```\n:::\n:::\n\n\nIt rejects strongly here, $\\text{RESET} = 131.6$ on 2 and 7,996 degrees of\nfreedom with $p < 10^{-56}$, which is the right answer given that we\nput a sine wave in $E[Z \\mid X]$. The same test on real data is cheap, and it\ntells us whether the LATE interpretation is defensible before we report a 2SLS\ncoefficient.\n\n### What to Do Instead\n\n@blandhol-et-al-2025 give four steps for empirical work.\n\n1. **Reconsider the covariates.** If $Z$ is unconditionally exogenous, drop them. A kitchen-sink set of controls makes rich covariates *less* likely.\n2. **Run RESET on `Z ~ X`.** If it does not reject, the linear-IV-as-LATE interpretation is defensible.\n3. **If RESET rejects, report DDML PLIV alongside 2SLS.** That is what the cross-fitting chunk above does. DDML PLIV targets $\\beta_{rich}$, a non-negatively weighted average of conditional LATEs.\n4. **For a binary instrument, also estimate the unconditional LATE.** With instrument propensity score weighting [@sloczynski-2024],\n\n   $$\n   \\hat\\beta_{late} = \\frac{\\sum_i Y_i [Z_i/\\hat p(X_i) - (1-Z_i)/(1-\\hat p(X_i))]}{\\sum_i W_i [Z_i/\\hat p(X_i) - (1-Z_i)/(1-\\hat p(X_i))]},\n   $$ {#eq-iv-rdd-8}\n\n   where $\\hat p(X) = P(Z = 1 \\mid X)$ is estimated nonparametrically. Stata has `kappalate` (Słoczyński, Uysal and Wooldridge), which implements this and related weighting estimators of the LATE. In Julia it is straightforward to build once $\\hat p(X)$ is in hand.\n\n### A Note on the FRDD Example\n\nThe fuzzy-RDD example at the end of this chapter is 2SLS with race, state of birth, and quarter-of-birth fixed effects entered as covariates. That section traces the gap between the 2SLS and the local `rdrobust` estimates to the first stage, which is close to zero near the cutoff. Rich covariates is a separate question about the 2SLS estimate itself, and the RESET test on the above-cutoff instrument against those covariates is the right first thing to run.\n\n### Bottom Line\n\n\"2SLS with covariates estimates LATE\" needs the rich covariates condition. That condition is a parametric assumption on $E[Z \\mid X]$ that researchers rarely defend, and a simple RESET test often rejects it. The honest alternatives are DDML PLIV for $\\beta_{rich}$ and IPSW (or DDML) for the unconditional LATE. Even when rich covariates holds, $\\beta_{rich}$ can be quite different from the unconditional LATE we usually care about.\n\n## Regression Discontinuity Design\n\nRDD (regression discontinuity design) is a quasi-experimental design that is used to estimate causal effects of interventions when assignment to the intervention is determined by whether a subject's value on an observed covariate exceeds a threshold. The idea is that the assignment is as good as random, so we can estimate the causal effect of the intervention by comparing the outcomes of subjects who are just above and just below the threshold.\n\n### Sharp RDD\n\nWe have a continuous variable $X$, called the running variable, which determines the binary treatment $W$. The treatment is assigned according to a threshold $c$. The outcome variable $Y$ is a function of $X$ and $W$.\n\n$$ W=\\mathbb{1}(X>c)$$ {#eq-iv-rdd-9}\n\nLee (2008) studies the effect of incumbency advantage in elections. His identification strategy is based on the discontinuity generated by the rule that the party with a majority vote share wins. The forcing variable $X_i$ is the difference in vote share between the Democratic and Republican parties in one election, with the threshold $c = 0$. The outcome variable $Y_i$ is vote share at the second election.\n\n`rdplot` bins the running variable and returns bin means and a polynomial fit on\neach side of the cutoff, which we plot. A visible jump at zero is the design working.\n\n::: {.cell message='false' execution_count=11}\n``` {.julia .cell-code}\nsenate = CSV.read(\"data/rdrobust_senate.csv\", DataFrame)\n\n# Calculate RD plot data\nplot_data = rdplot(senate.vote, senate.margin, c=0.0)\n\nfig = Figure()\nax = Axis(fig[1, 1], xlabel=\"Margin\", ylabel=\"Vote\")\nscatter!(ax, plot_data.vars_bins.rdplot_mean_x, plot_data.vars_bins.rdplot_mean_y, \n         color=:gray, markersize=6)\n\n# Plot polynomial fit for left side\npoly_l = filter(r -> r.rdplot_x < 0.0, plot_data.vars_poly)\nlines!(ax, poly_l.rdplot_x, poly_l.rdplot_y, color=:blue, linewidth=2)\n\n# Plot polynomial fit for right side\npoly_r = filter(r -> r.rdplot_x >= 0.0, plot_data.vars_poly)\nlines!(ax, poly_r.rdplot_x, poly_r.rdplot_y, color=:blue, linewidth=2)\n\nvlines!(ax, [0.0], color=:black, linestyle=:dash)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n![](iv-rdd_files/figure-pdf/cell-12-output-1.png){fig-pos='H'}\n:::\n:::\n\n\nThe `rdrobust_RDsenate` data are 1,297 US Senate races. The running variable\n`margin` is the Democratic margin of victory in an election and `vote` is the\nDemocratic vote share in the next election for the same seat. The bin means\nstep up discontinuously at a margin of zero.\n\n### Identification of SRDD\n\n$$ \\tau_{RD} = \\lim_{x \\to c^+} E[Y|X=x] - \\lim_{x \\to c^-} E[Y|X=x] $$ {#eq-iv-rdd-10}\n\nIn words, the treatment effect is the difference in the outcome from the right side and from the left side. This is the same as the difference in the outcome at the threshold, as if the treatment is assigned randomly.\n\n### Estimation of SRDD\n\nBefore the real data, a simulation where we know the answer. We draw $n = 1000$\nstudents with $\\text{GPA} \\sim U(0,4)$ and outcome\n$Y = 10 + 1.5\\,\\text{GPA} + 2 \\cdot \\mathbb{1}\\{\\text{GPA} > 3\\} + \\varepsilon$\nwith $\\varepsilon \\sim N(0,1)$. The cutoff is 3 and the true jump is 2. The\nrunning variable also has a direct effect on the outcome, with slope 1.5, which\nis what the local regression on each side has to absorb.\n\n::: {.cell message='false' execution_count=12}\n``` {.julia .cell-code}\nRandom.seed!(2024)\nGPA = rand(Uniform(0, 4), 1000)\n# Treatment is W = 1(GPA > 3), so the +2 jump must sit on the right\n# (above-cutoff) side to match the right-minus-left estimand above.\nfuture_success = 10 .+ 1.5 .* GPA .+ 2 .* (GPA .> 3) .+ rand(Normal(0, 1), 1000)\n\nplot_data_gpa = rdplot(future_success, GPA, c = 3.0)\n\nfig2 = Figure()\nax2 = Axis(fig2[1, 1], xlabel = \"GPA\", ylabel = \"Future Success\")\nscatter!(ax2, plot_data_gpa.vars_bins.rdplot_mean_x, plot_data_gpa.vars_bins.rdplot_mean_y,\n         color = :gray, markersize = 6)\npoly_gpa_l = filter(r -> r.rdplot_x < 3.0, plot_data_gpa.vars_poly)\nlines!(ax2, poly_gpa_l.rdplot_x, poly_gpa_l.rdplot_y, color = :blue, linewidth = 2)\npoly_gpa_r = filter(r -> r.rdplot_x >= 3.0, plot_data_gpa.vars_poly)\nlines!(ax2, poly_gpa_r.rdplot_x, poly_gpa_r.rdplot_y, color = :blue, linewidth = 2)\nvlines!(ax2, [3.0], color = :black, linestyle = :dash)\nfig2\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n![](iv-rdd_files/figure-pdf/cell-13-output-1.png){fig-pos='H'}\n:::\n:::\n\n\n::: {.cell message='false' execution_count=13}\n``` {.julia .cell-code}\n# a compact summary, like R's summary() of an rdrobust fit\nfunction rd_summary(r)\n    @printf(\"Bandwidth h = %.3f, b = %.3f; N = %d left, %d right; effective N = %d left, %d right\\n\",\n            r.bws.h_left[1], r.bws.b_left[1], r.N[1], r.N[2], r.N_h[1], r.N_h[2])\n    DataFrame(Method = r.coef.Method, Coef = round.(r.coef.Coeff, digits = 4),\n              SE = round.(r.se.StdErr, digits = 4), p = round.(r.pv.PValue, sigdigits = 3),\n              CI_low = round.(r.ci.CILower, digits = 3), CI_high = round.(r.ci.CIUpper, digits = 3))\nend\n\n# estimate the sharp RDD model\nrdd_gpa = rdrobust(future_success, GPA, c = 3.0)\nrd_summary(rdd_gpa)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBandwidth h = 0.373, b = 0.536; N = 736 left, 264 right; effective N = 94 left, 98 right\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=13}\n```{=tex}\n\\begin{tabular}{r|cccccc}\n\t& Method & Coef & SE & p & CI\\_low & CI\\_high\\\\\n\t\\hline\n\t& String & Float64 & Float64 & Float64 & Float64 & Float64\\\\\n\t\\hline\n\t1 & Conventional & 2.0776 & 0.3272 & 2.17e-10 & 1.436 & 2.719 \\\\\n\t2 & Bias-Corrected & 2.0456 & 0.3272 & 4.08e-10 & 1.404 & 2.687 \\\\\n\t3 & Robust & 2.0456 & 0.3925 & 1.88e-7 & 1.276 & 2.815 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\nThe estimated jump is 2.078 with a robust 95% interval of $[1.276, 2.815]$,\ncovering the true 2. Note how little data the estimate uses: the MSE-optimal\nbandwidth is 0.373, so of the 1,000 observations only 94 on the left and 98 on\nthe right are effective. A local estimator pays for its weak assumptions with\na small effective sample, which is why the interval is 1.5 wide for a jump of 2.\n\n### Nonparametric Estimation\n\nNow the same estimator on the Senate data, with the cutoff at a margin of zero.\n\n::: {.cell message='false' execution_count=14}\n``` {.julia .cell-code}\nrdd_house = rdrobust(senate.vote, senate.margin, c = 0.0)\nrd_summary(rdd_house)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBandwidth h = 17.754, b = 28.028; N = 595 left, 702 right; effective N = 360 left, 323 right\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=14}\n```{=tex}\n\\begin{tabular}{r|cccccc}\n\t& Method & Coef & SE & p & CI\\_low & CI\\_high\\\\\n\t\\hline\n\t& String & Float64 & Float64 & Float64 & Float64 & Float64\\\\\n\t\\hline\n\t1 & Conventional & 7.4141 & 1.4587 & 3.72e-7 & 4.555 & 10.273 \\\\\n\t2 & Bias-Corrected & 7.5065 & 1.4587 & 2.66e-7 & 4.647 & 10.366 \\\\\n\t3 & Robust & 7.5065 & 1.7413 & 1.63e-5 & 4.094 & 10.919 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\nThe incumbency effect is 7.414 percentage points with a robust 95% interval of\n$[4.094, 10.919]$. Barely winning a Senate seat raises the party's vote share\nin the next election for that seat by about 7 points. The bandwidth is 17.75\nmargin points, leaving 360 observations on the left and 323 on the right out of\n1,297.\n\n### Fuzzy RDD\n\nIn fuzzy RDD, the treatment is assigned according to a threshold $c$, but there exist non-compliance. This is similar to IV case.\n\n$$ \\tau_{FRD} = \\frac{\\lim_{x \\to c^+} E[Y|X=x] - \\lim_{x \\to c^-} E[Y|X=x]}{\\lim_{x \\to c^+} E[W|X=x] - \\lim_{x \\to c^-} E[W|X=x]} $$ {#eq-iv-rdd-11}\n\nFor example, if food stamp eligibility is given to all households below a certain income, but not all households receive the food stamps. In other words, income does not solely determine the assignment. Cutoff point increases the probability of treatment but doesn't completely determine treatment.\n\nFRDD is IV.\n\n### FRDD Example\n\nFetter (2013)'s main question of interest is how much of the increase in the home ownership rate in the midcentury US was due to mortgage subsidies given out by the government.\n\nWe're using the running variable quarter of birth (qob), which has been centered on the quarter of birth you'd need to be to be eligible for a mortgage subsidy for fighting in the Korean War (qob_minus_kw). This determines whether you were a veteran of either the Korean War or World War II (vet_wwko).\n\n::: {.cell cache='true' message='false' execution_count=15}\n``` {.julia .cell-code}\nvet = CSV.read(\"data/mortgages.csv\", DataFrame)   # causaldata::mortgages\n# Create an \"above-cutoff\" variable as the instrument\nvet.above = Float64.(vet.qob_minus_kw .> 0)\n# Impose a bandwidth of 12 quarters on either side\nvet = vet[abs.(vet.qob_minus_kw) .< 12, :]\n# The running variable qob_minus_kw is exogenous, so it goes with the controls.\n# The endogenous regressors are veteran status and its interaction with the\n# running variable, instrumented by being above the cutoff and that interaction.\nvet.vet_inter   = vet.qob_minus_kw .* vet.vet_wwko\nvet.above_inter = vet.qob_minus_kw .* vet.above\nm = feiv(vet, @formula(home_ownership ~ nonwhite + qob_minus_kw + fe(bpl) + fe(qob));\n         endo = [:vet_wwko, :vet_inter], inst = [:above, :above_inter],\n         vcov_type = Vcov.robust())   # heteroskedasticity-robust SEs\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    Demean Variables: [=====>                           ]  1/7\r    Demean Variables: [==========>                      ]  2/7\r    Demean Variables: [==============>                  ]  3/7\r    Demean Variables: [===================>             ]  4/7\r    Demean Variables: [=======================>         ]  5/7\r    Demean Variables: [============================>    ]  6/7\r    Demean Variables: [================================>]  7/7\r\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=15}\n```\nPanelest IV/2SLS Model\nNumber of obs: 56901\nEndogenous:    vet_wwko, vet_inter\nInstruments:   above, above_inter\n\n────────────────────────────────────────────────────────\n                 Estimate  Std. Error  z value  Pr(>|z|)\n────────────────────────────────────────────────────────\nvet_wwko       0.170172    0.0459329      3.70    0.0002\nvet_inter     -0.00285263  0.00263744    -1.08    0.2794\nnonwhite      -0.190434    0.00689193   -27.63    <1e-99\nqob_minus_kw  -0.00715077  0.00177347    -4.03    <1e-04\n────────────────────────────────────────────────────────\n\n--- Diagnostics ---\nFirst-stage F (vet_wwko): 315.7\nFirst-stage F (vet_inter): 1861.18\nWu-Hausman:   F(2, 56840) = 6.7536  [p = 0.0012]\n```\n:::\n:::\n\n\nThe 2SLS estimate is 0.1702 with a heteroskedasticity-robust standard error of\n0.0459: veteran status raises home ownership by 17 percentage points. The\nsample is 56,901 people within 12 quarters of the cutoff, with birthplace and\nquarter-of-birth fixed effects. The first-stage $F$ statistics are 316 and\n1,861, so the instruments are strong, and the Wu-Hausman test rejects\nexogeneity of veteran status at $p = 0.001$. The interaction of veteran status\nwith the running variable is not significant, so there is little evidence that\nthe slope differs across the cutoff.\n\nNow the same design estimated locally with `rdrobust`. We pass race and state\nof birth as covariates, but not quarter of birth. Quarter of birth is a\nfunction of the running variable, and the local window holds only three\nquarters on each side of the cutoff. There the quarter-of-birth dummies\nduplicate the local linear fits, and the jump is not identified with them in.\n`rdrobust` still returns a number, but the number is arbitrary: with the\ndummies included, R's `rdrobust` gives 0.096 or 0.838, depending only on\nwhether the covariate matrix carries an intercept column. `RDRobust.jl` gives a\nthird value and warns that the estimate is not identified.\n\n::: {.cell cache='true' message='false' execution_count=16}\n``` {.julia .cell-code}\n# race and state of birth; quarter of birth is left out (see text)\nstates    = sort(unique(vet.bpl))\nconmatrix = hcat(Float64.(vet.nonwhite), [Float64.(vet.bpl .== s) for s in states[2:end]]...)\nm_rdd = rdrobust(vet.home_ownership,\n                 vet.qob_minus_kw,\n                 fuzzy = vet.vet_wwko,\n                 c = 0.0,\n                 covs = conmatrix)\nrd_summary(m_rdd)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBandwidth h = 2.612, b = 5.371; N = 28776 left, 28125 right; effective N = 6911 left, 6756 right\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=16}\n```{=tex}\n\\begin{tabular}{r|cccccc}\n\t& Method & Coef & SE & p & CI\\_low & CI\\_high\\\\\n\t\\hline\n\t& String & Float64 & Float64 & Float64 & Float64 & Float64\\\\\n\t\\hline\n\t1 & Conventional & 2.3684 & 4.9681 & 0.634 & -7.369 & 12.106 \\\\\n\t2 & Bias-Corrected & 6.5115 & 4.9681 & 0.19 & -3.226 & 16.249 \\\\\n\t3 & Robust & 6.5115 & 5.7613 & 0.258 & -4.78 & 17.803 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n`rdrobust` returns a conventional estimate of 2.37 with a standard error of\n4.97, and a bias-corrected estimate of 6.51 with a robust standard error of\n5.76. The robust 95% interval runs from $-4.78$ to 17.80. For an effect on a\nprobability, that says nothing.\n\nThe reason is the first stage. A fuzzy RD divides the jump in the outcome by\nthe jump in treatment at the cutoff. Here we estimate the second jump directly,\nwith the same covariates and bandwidth.\n\n::: {.cell cache='true' message='false' execution_count=17}\n``` {.julia .cell-code}\n# first stage: the jump in veteran status at the cutoff\nfs = rdrobust(Float64.(vet.vet_wwko), vet.qob_minus_kw, c = 0.0,\n              covs = conmatrix, h = m_rdd.bws.h_left[1])\ndisplay(rd_summary(fs))\n# veteran share by quarter near the cutoff\ncombine(groupby(filter(:qob_minus_kw => q -> abs(q) < 4, vet), :qob_minus_kw, sort = true),\n        :vet_wwko => mean => :vet_share)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBandwidth h = 2.612, b = 2.612; N = 28776 left, 28125 right; effective N = 6911 left, 6756 right\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=tex}\n\\begin{tabular}{r|cccccc}\n\t& Method & Coef & SE & p & CI\\_low & CI\\_high\\\\\n\t\\hline\n\t& String & Float64 & Float64 & Float64 & Float64 & Float64\\\\\n\t\\hline\n\t1 & Conventional & -0.0102 & 0.0205 & 0.618 & -0.05 & 0.03 \\\\\n\t2 & Bias-Corrected & -0.0025 & 0.0205 & 0.904 & -0.043 & 0.038 \\\\\n\t3 & Robust & -0.0025 & 0.0332 & 0.941 & -0.067 & 0.063 \\\\\n\\end{tabular}\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=17}\n```{=tex}\n\\begin{tabular}{r|cc}\n\t& qob\\_minus\\_kw & vet\\_share\\\\\n\t\\hline\n\t& Float64 & Float64\\\\\n\t\\hline\n\t1 & -3.5 & 0.561224 \\\\\n\t2 & -2.5 & 0.558109 \\\\\n\t3 & -1.5 & 0.524569 \\\\\n\t4 & -0.5 & 0.480088 \\\\\n\t5 & 0.5 & 0.417344 \\\\\n\t6 & 1.5 & 0.352348 \\\\\n\t7 & 2.5 & 0.2943 \\\\\n\t8 & 3.5 & 0.276429 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\nWithin 2.6 quarters of the cutoff, veteran status does not jump: the estimate\nis $-0.010$ with a standard error of 0.021. The veteran share falls from 0.56\ntwo and a half quarters before the cutoff to 0.29 two and a half quarters after,\nbut it falls steadily across those quarters, with no break at zero. The fuzzy\nestimate divides a noisy jump in home ownership by a jump in treatment that is\nindistinguishable from zero.\n\n2SLS finds a strong first stage because it fits one line on each side over 12\nquarters and reads the jump off where the two lines meet. The steep decline near\nthe cutoff then registers as a large jump. Its 0.17 rests on that linear\nspecification. The local estimator drops the assumption, and the data near the\ncutoff then have nothing to say. The two estimates do not contradict each other.\nThe local one is uninformative here.\n\n## Summary\n\nAn instrument recovers an effect when the confounder is unobserved. It must move the treatment (relevance), reach the outcome only through the treatment (exclusion) and be as good as random. With heterogeneous effects and no defiers, the Wald ratio identifies the LATE, the effect on compliers. Adding covariates linearly keeps that interpretation only under the rich-covariates condition, that the instrument's conditional mean is linear in the covariates. A RESET test on the instrument checks it. Regression discontinuity replaces the instrument with a cutoff in a running variable and assumes continuity at the cutoff. Fuzzy RDD is IV at the cutoff.\n\nIn the simulation, OLS gives 1.3571, and 2SLS gives 0.9999 against a true 1. With a nonlinear instrument propensity, the true LATE is 0.617 and the linear 2SLS converges to 0.55. The Senate incumbency effect is 7.4 percentage points. In the Korean War example, 2SLS gives 0.1702 (0.0459). The local `rdrobust` estimate, 2.37 (4.97), is uninformative, because veteran status does not jump at the cutoff within the local window. The 2SLS first stage comes from linear fits over 12 quarters.\n\n",
    "supporting": [
      "iv-rdd_files/figure-pdf"
    ],
    "filters": []
  }
}