{
  "hash": "9afc57850b1d1036b132bd366fdbe57f",
  "result": {
    "engine": "jupyter",
    "markdown": "# Sensitivity Analysis\n\n\n::: {.cell execution_count=2}\n``` {.julia .cell-code}\nusing DataFrames\nusing GLM\nusing Statistics\nusing Random\nusing LinearAlgebra\nusing Printf\nusing CairoMakie\nCairoMakie.activate!(type = \"png\")\n```\n:::\n\n\nThe previous chapters often treat identification as yes or no. Applied work\nis usually less clean. We may believe the adjustment set is good, but still\nworry about some remaining confounding. Sensitivity analysis asks a practical\nquestion: how strong would unmeasured confounding have to be to change the\nconclusion?\n\n> **Related reading**: An extended R-based treatment of the\n> Cinelli-Hazlett robustness value with `sensemakr` and benchmark\n> interpretations appears in the\n> [companion blog chapter on sensitivity analysis](https://xiangao.github.io/blog_book/sensitivity-analysis.html)\n> of *Topics on Econometrics and Causal Inference*.\n\nHere I use three tools:\n\n1. **Cinelli-Hazlett (2020) omitted-variable bias bounds** — robustness\n   values and benchmark comparisons for OLS regression estimates.\n2. **E-values (VanderWeele-Ding 2017)** — for risk-ratio estimates, the\n   minimum strength an unmeasured confounder would need.\n3. **Rosenbaum bounds** — the critical odds ratio of hidden bias that\n   would render a matched-sample test insignificant.\n\nThere is no standard Julia package for these, but the formulas are short.\n\n## A simulated example\n\nUse a simulation so the truth is known:\n\n::: {#dgp .cell cache='true' execution_count=3}\n``` {.julia .cell-code}\nRandom.seed!(2026)\nn   = 2000\nX1  = randn(n)\nX2  = randn(n)\nU   = randn(n)             # unmeasured confounder\nD   = @. Float64(rand() < 1 / (1 + exp(-(0.5 * X1 + 0.5 * X2 + 0.6 * U))))\nY   = @. 1.0 * D + 1.5 * X1 + 1.5 * X2 + 1.0 * U + 0.5 * randn()\n\ndf  = DataFrame(Y = Y, D = D, X1 = X1, X2 = X2, U = U)\n\n# Pull the coefficient out BY NAME. Indexing positionally (`[end]`, `[2]`) is a\n# standing invitation to report the wrong number: `[end]` on `Y ~ D + X1 + X2`\n# is the coefficient on X2, not on D, and in this DGP X2's true coefficient\n# (1.5) is close enough to the confounded D estimate that the mistake does not\n# look like one.\ncoef_of(m, name) = coef(m)[findfirst(==(name), coefnames(m))]\n\n@printf(\"True treatment effect: 1.000\\n\")\n@printf(\"Naive (D only):        %.3f\\n\",\n        coef_of(lm(@formula(Y ~ D), df), \"D\"))\n@printf(\"Adjusted (D, X1, X2):  %.3f  (biased because U is unobserved)\\n\",\n        coef_of(lm(@formula(Y ~ D + X1 + X2), df), \"D\"))\n@printf(\"Oracle (D, X1, X2, U): %.3f\\n\",\n        coef_of(lm(@formula(Y ~ D + X1 + X2 + U), df), \"D\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTrue treatment effect: 1.000\nNaive (D only):        2.787\nAdjusted (D, X1, X2):  1.497  (biased because U is unobserved)\nOracle (D, X1, X2, U): 0.966\n```\n:::\n:::\n\n\nThe adjusted regression is still biased because $U$ is unobserved.\n\n## Cinelli-Hazlett robustness value\n\nThe robustness value is the minimum partial $R^2$ an unobserved confounder\nwould need with both treatment and outcome to bring the estimate to zero.\n\nThe closed-form expression depends only on the t-statistic of the\ntreatment coefficient and the regression's degrees of freedom:\n\n$$\nRV_q = \\tfrac{1}{2}\\left[\\sqrt{f_q^4 + 4 f_q^2} - f_q^2\\right], \\qquad\nf_q = q\\, \\frac{|t|}{\\sqrt{df}},\n$$ {#eq-sensitivity-analysis-1}\n\nwhere $|t|$ is the absolute t-stat of the treatment coefficient, $df$ is\nthe residual degrees of freedom, and $q$ is the fraction of the estimate\nwe want explained away ($q = 1$ for full explanation).\n\n::: {#rv .cell cache='true' execution_count=4}\n``` {.julia .cell-code}\n\"\"\"\n    robustness_value(t_stat, df; q=1.0)\nMinimum partial R² with both treatment and outcome that an unmeasured\nconfounder would need to fully explain away a fraction `q` of the estimate.\nCinelli & Hazlett (2020).\n\"\"\"\nfunction robustness_value(t_stat::Real, df::Real; q::Real=1.0)\n    fq = q * abs(t_stat) / sqrt(df)\n    return 0.5 * (sqrt(fq^4 + 4 * fq^2) - fq^2)\nend\n\n# Fit the adjusted regression and extract t-stat + dof\nfit_adj   = lm(@formula(Y ~ D + X1 + X2), df)\nt_adj     = coef(fit_adj)[2] / stderror(fit_adj)[2]\ndf_resid  = dof_residual(fit_adj)\n\nrv  = robustness_value(t_adj, df_resid; q=1.0)\nrv5 = robustness_value(t_adj, df_resid; q=1.0 - 1.96/abs(t_adj))   # q to reach significance\n\n@printf(\"t-statistic on D:                %.2f\\n\", t_adj)\n@printf(\"Residual df:                     %.0f\\n\", df_resid)\n@printf(\"Robustness value (q=1):          %.4f  (= %.2f%% partial R²)\\n\",\n        rv, 100rv)\n@printf(\"RV to reach insignificance:      %.4f  (= %.2f%% partial R²)\\n\",\n        rv5, 100rv5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nt-statistic on D:                29.24\nResidual df:                     1996\nRobustness value (q=1):          0.4745  (= 47.45% partial R²)\nRV to reach insignificance:      0.4521  (= 45.21% partial R²)\n```\n:::\n:::\n\n\nThe useful interpretation is comparative: compare the RV to the partial\n$R^2$ values of observed covariates.\n\n### Benchmarking against observed covariates\n\nHow strong are the observed covariates as a reference? Compute their\npartial $R^2$ contributions:\n\n::: {#benchmark .cell cache='true' execution_count=5}\n``` {.julia .cell-code}\n# Partial R² of a covariate: variance explained over a model that omits it\nfunction partial_r2(full_fit, reduced_fit)\n    ss_full     = sum(abs2.(residuals(full_fit)))\n    ss_reduced  = sum(abs2.(residuals(reduced_fit)))\n    1 - ss_full / ss_reduced\nend\n\n# Partial R² of X1 with the outcome (omit X1)\nfit_noX1_Y = lm(@formula(Y ~ D + X2), df)\npR2_X1_Y   = partial_r2(fit_adj, fit_noX1_Y)\n\n# Partial R² of X1 with the treatment (a separate regression)\nfit_D_full = lm(@formula(D ~ X1 + X2), df)\nfit_D_noX1 = lm(@formula(D ~ X2), df)\npR2_X1_D   = partial_r2(fit_D_full, fit_D_noX1)\n\n@printf(\"Benchmark — X1:\\n\")\n@printf(\"  Partial R² with Y: %.4f\\n\", pR2_X1_Y)\n@printf(\"  Partial R² with D: %.4f\\n\", pR2_X1_D)\n@printf(\"\\nRobustness value:    %.4f\\n\", rv)\n@printf(\"\\nIf an unobserved confounder is as strong as X1 with BOTH Y and D,\\n\")\n@printf(\"would it explain the estimate? %s\\n\",\n        min(pR2_X1_Y, pR2_X1_D) > rv ? \"YES — fragile result\" : \"NO — robust to this benchmark\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBenchmark — X1:\n  Partial R² with Y: 0.6209\n  Partial R² with D: 0.0489\n\nRobustness value:    0.4745\n\nIf an unobserved confounder is as strong as X1 with BOTH Y and D,\nwould it explain the estimate? NO — robust to this benchmark\n```\n:::\n:::\n\n\nThe benchmark comparison turns the RV into a sentence: an unmeasured\nconfounder as strong as $X_1$ would or would not overturn the result.\n\nBecause this is a simulation we can check the machinery against the confounder\nthat actually exists. $U$'s partial $R^2$ is 0.787 with the outcome and 0.064\nwith the treatment. The second number is far below the robustness value, so the\nverdict \"not explained away\" is correct --- and it is correct even though the\nadjusted estimate is badly biased. Those are different questions, and the\ndistinction is the main thing to take from this section: a robustness value asks\nwhether a confounder could drive the estimate to *zero*, not whether the estimate\nis *right*. Here it cannot, and the estimate is still 50% too large.\n\nFeeding $U$'s true strengths into the Cinelli-Hazlett bias formula gives a bound\nof 0.531, so the bias-corrected estimate is $1.497 - 0.531 = 0.966$ against a\ntrue effect of 1.000. The bound is doing its job: it is not a point correction\none would apply in practice, since in real data the confounder's strengths are\nexactly what we do not know, but it confirms that the formula is calibrated\nrather than merely suggestive.\n\n### A sensitivity contour plot\n\nThe contour plot below shows, for each $(R^2_{D \\sim U}, R^2_{Y \\sim U})$\npair, the implied estimate of the treatment effect under that strength\nof unobserved confounding:\n\n::: {.cell cache='true' execution_count=6}\n``` {.julia .cell-code}\n# Bias formula (Cinelli-Hazlett 2020, eqn 4):\n# bias = se(τ̂) * sqrt(df) * sqrt( R²_Y * R²_D / (1 - R²_D) )\n# adjusted_estimate = τ̂ - bias (or + bias, the worst case is the larger absolute)\ntau_hat = coef(fit_adj)[2]\nse_hat  = stderror(fit_adj)[2]\n\ngrid = 0.0:0.01:0.5\nbias_matrix = [se_hat * sqrt(df_resid) * sqrt(r2y * r2d / max(1 - r2d, 1e-8))\n               for r2y in grid, r2d in grid]\nadjusted    = tau_hat .- bias_matrix    # worst-case (downward) bias\n\nfig = Figure(size = (700, 500))\nax  = Axis(fig[1, 1],\n           xlabel = \"Partial R² with treatment (R²_D ~ U)\",\n           ylabel = \"Partial R² with outcome (R²_Y ~ U)\",\n           title  = \"Sensitivity contour: adjusted estimate of τ\\n\" *\n                    \"(0 contour = estimate reduced to 0)\")\ncontour!(ax, grid, grid, adjusted, levels = [0.0, 0.25, 0.5, 0.75, 1.0],\n         labels = true, color = :black)\n# Mark the X1 benchmark\nscatter!(ax, [pR2_X1_D], [pR2_X1_Y], color = :steelblue, markersize = 18,\n         label = \"X1 benchmark\")\naxislegend(ax, position = :rb, framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n![](sensitivity-analysis_files/figure-pdf/contour-output-1.png){#contour fig-pos='H'}\n:::\n:::\n\n\nA confounder above and to the right of the zero contour would reduce the\nestimate to zero. The benchmark dot shows the strength of an observed\ncovariate for comparison.\n\n## E-values\n\nFor risk-ratio estimates, VanderWeele and Ding (2017) propose a\nsimpler-to-interpret sensitivity statistic. For an observed risk ratio\n$RR > 1$, the **E-value** is the minimum strength of association (on the\nrisk-ratio scale) that an unobserved confounder would need to have with\nboth treatment and outcome to fully explain the observed association:\n\n$$\n\\text{E-value} = RR + \\sqrt{RR\\,(RR - 1)}.\n$$ {#eq-sensitivity-analysis-2}\n\nFor $RR < 1$, use $1/RR$ first and apply the formula.\n\n::: {#evalue .cell cache='true' execution_count=7}\n``` {.julia .cell-code}\n\"\"\"\n    evalue(rr; lo=missing, hi=missing)\nCompute the E-value for a risk ratio and (optionally) its 95% confidence\ninterval. Returns (E_point, E_ci) where E_ci is the E-value needed to\nshift the lower CI bound past 1 (or upper past 1 if rr < 1).\n\"\"\"\nfunction evalue(rr::Real; lo=missing, hi=missing)\n    e_point = rr >= 1 ? rr + sqrt(rr * (rr - 1)) : begin\n        rr_inv = 1 / rr\n        rr_inv + sqrt(rr_inv * (rr_inv - 1))\n    end\n    e_ci = missing\n    if !ismissing(lo) && !ismissing(hi)\n        if rr >= 1 && lo > 1\n            e_ci = lo + sqrt(lo * (lo - 1))\n        elseif rr < 1 && hi < 1\n            hi_inv = 1 / hi\n            e_ci = hi_inv + sqrt(hi_inv * (hi_inv - 1))\n        else\n            e_ci = 1.0   # CI crosses 1, no E-value needed\n        end\n    end\n    return (e_point = e_point, e_ci = e_ci)\nend\n\n# Example: a study reports RR = 1.40 [1.20, 1.62]\nev = evalue(1.40; lo = 1.20, hi = 1.62)\n@printf(\"RR = 1.40 [1.20, 1.62]\\n\")\n@printf(\"E-value (point): %.2f\\n\", ev.e_point)\n@printf(\"E-value (CI):    %.2f\\n\", ev.e_ci)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRR = 1.40 [1.20, 1.62]\nE-value (point): 2.15\nE-value (CI):    1.69\n```\n:::\n:::\n\n\nThe interpretation is on the risk-ratio scale: a hidden confounder would\nneed associations of this size with both treatment and outcome to explain\naway the result.\n\n## Rosenbaum bounds for matched studies\n\nFor matched estimators (propensity score matching, full matching,\noptimal matching), **Rosenbaum bounds** (Rosenbaum 2002) parametrise\nhidden bias as $\\Gamma$, the maximum ratio of treatment odds between the\ntwo units of a matched pair due to unobservables. $\\Gamma = 1$ corresponds\nto within-pair randomisation; $\\Gamma = 2$ means one unit's odds of\nreceiving treatment can be up to twice the other's.\n\nFor each value of $\\Gamma$, the upper-bound $p$-value of the Wilcoxon\nsigned-rank test on matched-pair outcome differences is:\n\n::: {#rosenbaum .cell cache='true' execution_count=8}\n``` {.julia .cell-code}\n# Simulate matched-pair differences from a known DGP\nRandom.seed!(7)\nn_pairs = 500\ntrue_effect = 0.5\ndiffs = true_effect .+ 0.8 .* randn(n_pairs)\n\nusing Distributions: Normal, cdf\n\n\"\"\"\n    rosenbaum_pvalue(diffs, gamma)\nUpper-bound one-sided p-value of the Wilcoxon signed-rank test on matched\npair differences, allowing for hidden bias of magnitude `gamma` ≥ 1.\n\"\"\"\nfunction rosenbaum_pvalue(diffs, gamma)\n    abs_d = abs.(diffs)\n    sgn   = sign.(diffs)\n    rks   = sortperm(sortperm(abs_d))   # ranks of |d|\n    # Under Γ, prob of positive sign is bounded by Γ/(1+Γ)\n    p_pos = gamma / (1 + gamma)\n    T_obs = sum(rks[sgn .> 0])\n    mu    = p_pos * sum(rks)\n    v     = p_pos * (1 - p_pos) * sum(rks .^ 2)\n    z     = (T_obs - mu) / sqrt(v)\n    return 1 - cdf(Normal(), z)\nend\n\ngammas = 1.0:0.25:5.0\npvals  = [rosenbaum_pvalue(diffs, g) for g in gammas]\nresult = DataFrame(Gamma = gammas, p_upper = pvals)\n\n# Critical Γ: smallest Γ where p exceeds 0.05\ncritical_idx = findfirst(p -> p > 0.05, pvals)\ncritical_gamma = critical_idx === nothing ? Inf : gammas[critical_idx]\n\n@printf(\"Critical Γ (p > 0.05): %.2f\\n\", critical_gamma)\n@printf(\"\\n%-10s %s\\n\", \"Γ\", \"p (upper bound)\")\nfor (g, p) in zip(gammas, pvals)\n    @printf(\"%-10.2f %.4f\\n\", g, p)\nend\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCritical Γ (p > 0.05): 3.00\n\nΓ          p (upper bound)\n1.00       0.0000\n1.25       0.0000\n1.50       0.0000\n1.75       0.0000\n2.00       0.0000\n2.25       0.0001\n2.50       0.0013\n2.75       0.0121\n3.00       0.0599\n3.25       0.1799\n3.50       0.3725\n3.75       0.5887\n4.00       0.7698\n4.25       0.8891\n4.50       0.9534\n4.75       0.9827\n5.00       0.9942\n```\n:::\n:::\n\n\nIf the critical $\\Gamma$ is close to 1, small hidden bias could overturn the\nmatched-pair result. (The reported value is the first point *on the 0.25\ngrid* at which significance is lost; the actual crossing lies between it and\nthe preceding grid point.)\n\n## Reporting practice\n\nMost observational causal estimates should have some sensitivity analysis.\nA minimum report is:\n\n| Estimator family | What to report |\n|---|---|\n| Linear regression | Cinelli-Hazlett RV + benchmark comparison |\n| Risk-ratio analysis | E-value (point + CI) |\n| Matched / pair-based test | Critical $\\Gamma$ from Rosenbaum bounds |\n\nWhen the result is fragile, the next step is either to improve measurement\nand adjustment or to report partial-identification bounds.\n\n## Summary\n\n- Sensitivity analysis asks how strong hidden confounding must be to change\n  the result.\n- Robustness values are useful for regression estimates.\n- E-values are useful for risk ratios.\n- Rosenbaum bounds are useful for matched pairs.\n- The basic formulas are easy to implement directly in Julia.\n\n",
    "supporting": [
      "sensitivity-analysis_files/figure-pdf"
    ],
    "filters": []
  }
}