{
  "hash": "e4078fd79792b15309349abf4487328a",
  "result": {
    "engine": "jupyter",
    "markdown": "# IV in Poisson with Fixed Effects\n\n\n::: {.cell execution_count=2}\n``` {.julia .cell-code}\nusing Panelest\nusing Distributions\nusing DataFrames, DataFramesMeta\nusing StatsModels\nimport StatsAPI: coeftable\nusing Random, StatsBase, LinearAlgebra\nusing Printf\n```\n:::\n\n\nPoisson regression specifies the conditional mean as an exponential function.\nAs a quasi-MLE, it needs the mean to be correct, not the full count\ndistribution. If a regressor is endogenous, the IV strategy has to respect\nthat nonlinear mean. I consider two cases: a continuous endogenous variable\nand a binary endogenous variable.\n\n\n## The Control Function Framework\n\n### Linear second stage — CF equals 2SLS\n\nIn the previous chapter we saw that adding the first-stage residual $\\hat{v}_2$ to an OLS\nsecond stage recovers the same coefficient as 2SLS.  The algebra is:\n\n1. **First stage**: $y_2 = \\mathbf{z}\\boldsymbol{\\pi} + v_2$, estimated by OLS.\n   Residual $\\hat{v}_2 = y_2 - \\hat{y}_2$ satisfies $E(\\mathbf{z}'\\hat{v}_2) = 0$.\n\n2. **Structural error decomposition**: write $\\varepsilon_1 = \\rho v_2 + \\eta_1$,\n   where $E(\\mathbf{z}'\\eta_1) = 0$ and $E(v_2\\,\\eta_1) = 0$ by construction.\n\n3. **Augmented second stage**: substitute to get\n   $y_1 = \\mathbf{z}_1\\boldsymbol{\\delta}_1 + \\alpha_1 y_2 + \\rho\\,\\hat{v}_2 + \\eta_1.$\n\nOLS on this equation is the **control function estimator**.  The\nFrisch–Waugh–Lovell (FWL) theorem guarantees it is numerically identical to 2SLS —\nno extra assumption beyond $E(\\mathbf{z}'\\varepsilon_1) = 0$ is required.\n\n### Nonlinear second stage — CF diverges from 2SLS\n\nWhen the conditional mean is $\\exp(\\mathbf{x}\\boldsymbol{\\beta})$ (Poisson), a direct IV/GMM\napproach solves moment conditions in $\\mathbf{z}$ without modifying the exponential mean.\nTwo moment forms exist, and the choice matters:\n\n- **Additive moments** $E[\\mathbf{z}'(y_1 - \\exp(\\mathbf{x}\\boldsymbol{\\beta}))] = 0$ assume an\n  *additive* error orthogonal to $\\mathbf{z}$.\n- **Multiplicative moments** $E[\\mathbf{z}'(y_1 e^{-\\mathbf{x}\\boldsymbol{\\beta}} - 1)] = 0$\n  [@mullahy-1997] assume a *multiplicative* error with mean independent of $\\mathbf{z}$.\n\nWhen the unobservable enters **inside** the exponential — $y_1$ has mean\n$\\exp(\\mathbf{x}\\boldsymbol{\\beta} + \\rho v)$, as in both DGPs of this chapter — the error is\nmultiplicative, the additive moments are misspecified, and additive-moment IV is\ninconsistent.  The multiplicative form is the robust default.\nThe **control function approach** instead imposes the\nstronger *conditional mean assumption* [@wooldridge-2010-crosssection, sec. 18.5; @wooldridge-2014-qmle]:\n\n$$E[y_1 \\mid \\mathbf{z}_1,\\, y_2,\\, v_2] = \\exp\\!\\bigl(\\mathbf{z}_1\\boldsymbol{\\delta}_1\n+ \\alpha_1 y_2 + \\rho v_2\\bigr).$$ {#eq-poisson-iv-1}\n\nThis says the unobservable enters the conditional mean **linearly inside** $\\exp(\\cdot)$.\nUnder this assumption, substituting $\\hat{v}_2$ for $v_2$ and running Poisson QMLE\ngives a consistent estimate of $\\alpha_1$.\n\nThree practical consequences:\n\n| Property | Linear (OLS/2SLS) | Nonlinear (Poisson CF) |\n|:---|:---|:---|\n| Extra assumption beyond IV exogeneity | None — FWL applies | CF mean assumption required |\n| CF vs. 2SLS/GMM numerically | **Identical** | **Different** — FWL fails |\n| SE from second stage alone | Correct | **Understated** — bootstrap needed |\n| Test of endogeneity | $t$-stat on $\\hat{v}_2$ (DWH) | Same — $t$-stat on $\\hat{v}_2$ |\n\n::: {.callout-note}\n**Intuition for the CF assumption.**\nThe decomposition $\\varepsilon_1 = \\rho v_2 + \\eta_1$ is exactly the same as in the linear case.\nWhat changes is where the decomposition gets applied: in the linear model it enters additively\noutside any transformation; in Poisson it must enter inside $\\exp(\\cdot)$ to be absorbed by\nthe quasi-MLE score.  If the true $\\rho \\neq 0$, omitting $\\hat{v}_2$ from the exponential\nmean leaves a multiplicative endogeneity term $e^{\\rho v_2}$ correlated with $y_2$,\nbiasing $\\hat\\alpha_1$ upward or downward depending on the sign of $\\rho$.\n:::\n\n## Part 1 — Continuous endogenous variable\n\n### Data generating process\n\nWe simulate a panel where `time` (continuous, e.g. minutes on site) is endogenous: it is correlated with an unobserved factor `e` that also affects `visits`.  The excluded instrument is `phone` (binary, e.g. phone-access indicator).  Fixed effects are `ad` (20 groups) and `female`.\n\n::: {.cell execution_count=3}\n``` {.julia .cell-code}\nRandom.seed!(42)\nn_ad = 20; obs_per = 250; n = n_ad * obs_per\n\nfe_ad  = randn(n_ad) .* 0.5\nfe_grp = repeat(1:n_ad, inner = obs_per)\nfemale = Int.(rand(n) .< 0.5)\nphone  = Int.(rand(n) .< 0.4)\nfrfam  = rand(n)\n\n# Common error drives endogeneity\ne = randn(n)\n\n# Continuous endogenous variable (linear first stage holds exactly)\ntime = 1.5 .* phone .+ 0.5 .* frfam .+ fe_ad[fe_grp] .+ e\n\n# Poisson outcome — true coefficient on time = 0.8\ntrue_α = 0.8\nλ = exp.(0.5 .+ true_α .* time .+ 0.4 .* frfam .+\n         fe_ad[fe_grp] .+ 0.3 .* female .+ 0.5 .* e)\nvisits = [rand(Poisson(λi)) for λi in λ]\n\ndf1 = DataFrame(visits=visits, time=time, phone=phone,\n                frfam=frfam, female=female, ad=fe_grp)\n\nprintln(\"n = $n   groups = $n_ad   visits mean = $(round(mean(visits),digits=2))\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nn = 5000   groups = 20   visits mean = 15.93\n```\n:::\n:::\n\n\n### Naive Poisson — endogeneity bias\n\nIgnoring the endogeneity of `time` gives a biased estimate of `α₁`:\n\n::: {.cell execution_count=4}\n``` {.julia .cell-code}\nnaive1 = fepois(df1, @formula(visits ~ time + frfam + fe(ad) + fe(female)))\nprintln(\"Naive (biased):\")\nshow_regression_html(naive1; title=\"Naive Poisson — time is endogenous\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNaive (biased):\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<p><strong>Naive Poisson — time is endogenous</strong></p><table style=\"border-collapse: collapse; font-family: monospace; font-size: 13px; margin: 0.5em 0;\"><thead><tr><th style=\"text-align: left; padding: 4px 10px 4px 0; border-bottom: 1px solid black;\"></th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Estimate</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Std. Error</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">t value</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Pr(>|t|)</th></tr></thead><tbody><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">time</td><td style=\"text-align: right; padding: 3px 8px;\">1.150</td><td style=\"text-align: right; padding: 3px 8px;\">0.003</td><td style=\"text-align: right; padding: 3px 8px;\">392.827</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">frfam</td><td style=\"text-align: right; padding: 3px 8px;\">0.291</td><td style=\"text-align: right; padding: 3px 8px;\">0.013</td><td style=\"text-align: right; padding: 3px 8px;\">22.698</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 6px 0 0 0; border-top: 1px solid black;\" colspan=\"5\">---<br/>Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</td></tr></tbody></table>\n```\n:::\n:::\n\n\n### Control function approach\n\nApplying the framework above, the two-step CF procedure is:\n\n1. **First stage** — linear projection of `time` on `phone`, `frfam`, and fixed effects via `feols`.\n   The residual $\\hat{v}_2 = \\text{time} - \\hat{\\text{time}}$ satisfies $E(\\mathbf{z}'\\hat{v}_2)=0$ by construction.\n   A linear first stage is appropriate here because `time` is continuous. **This does not carry\n   over when $y_2$ is binary** — see the derivation in Part 2, where Wooldridge is explicit that\n   the linear reduced-form/independent-error setup cannot be assumed once $y_2$ is discrete\n   [@wooldridge-2010-crosssection, sec. 18.5; @imbens-wooldridge-2007-cf].\n\n2. **Second stage** — Poisson QMLE with $\\hat{v}_2$ added as a regressor inside the exponential mean.\n   The CF assumption $E[y_1 \\mid \\mathbf{z}_1, y_2, v_2] = \\exp(\\mathbf{z}_1\\boldsymbol{\\delta}_1 + \\alpha_1 y_2 + \\rho v_2)$\n   holds exactly here because the DGP specifies $0.5\\,e$ (linear in the unobservable) inside $\\exp(\\cdot)$.\n\nNote that unlike 2SLS in a linear model, $\\hat{v}_2$ does *not* replace $y_2$ — both enter together.\nThis is what makes the CF estimator different from IV/GMM Poisson (confirmed numerically in Part 2).\n\n::: {.cell execution_count=5}\n``` {.julia .cell-code}\n# Step 1: linear projection\nfs1 = feols(df1, @formula(time ~ phone + frfam + fe(ad) + fe(female)))\ndf1.v2hat = fs1.residuals\n\n# Step 2: Poisson CF\nm1_cf = fepois(df1, @formula(visits ~ time + v2hat + frfam + fe(ad) + fe(female)))\nprintln(\"CF estimate (should recover α₁ = $(true_α)):\")\nshow_regression_html(m1_cf; title=\"CF: linear projection first stage\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCF estimate (should recover α₁ = 0.8):\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<p><strong>CF: linear projection first stage</strong></p><table style=\"border-collapse: collapse; font-family: monospace; font-size: 13px; margin: 0.5em 0;\"><thead><tr><th style=\"text-align: left; padding: 4px 10px 4px 0; border-bottom: 1px solid black;\"></th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Estimate</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Std. Error</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">t value</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Pr(>|t|)</th></tr></thead><tbody><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">time</td><td style=\"text-align: right; padding: 3px 8px;\">0.810</td><td style=\"text-align: right; padding: 3px 8px;\">0.005</td><td style=\"text-align: right; padding: 3px 8px;\">158.862</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">v2hat</td><td style=\"text-align: right; padding: 3px 8px;\">0.489</td><td style=\"text-align: right; padding: 3px 8px;\">0.006</td><td style=\"text-align: right; padding: 3px 8px;\">76.972</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">frfam</td><td style=\"text-align: right; padding: 3px 8px;\">0.405</td><td style=\"text-align: right; padding: 3px 8px;\">0.013</td><td style=\"text-align: right; padding: 3px 8px;\">31.664</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 6px 0 0 0; border-top: 1px solid black;\" colspan=\"5\">---<br/>Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</td></tr></tbody></table>\n```\n:::\n:::\n\n\nThe coefficient on `time` recovers the true $\\alpha_1 = 0.8$.  The `v2hat` coefficient tests exogeneity — its t-statistic is the Hausman-type test.\n\n### Bootstrap standard errors\n\nThe second-stage standard errors are incorrect because the first-stage estimation error propagates.  Julia's `Threads.@threads` parallelises the cluster bootstrap across all CPU cores:\n\n::: {.cell execution_count=6}\n``` {.julia .cell-code}\nfunction bootstrap_resample(df::DataFrame, B::Int; seed::Int=42)\n    Random.seed!(seed)\n    clusters = unique(df.ad)\n    K = length(clusters)\n    draws = [sample(clusters, K, replace=true) for _ in 1:B]\n    return draws\nend\n\nfunction build_boot_df(df::DataFrame, drawn_clusters::Vector)\n    frames = DataFrame[]\n    for (id, c) in enumerate(drawn_clusters)\n        sub = copy(df[df.ad .== c, :])\n        sub.ad_boot = fill(id, nrow(sub))\n        push!(frames, sub)\n    end\n    return vcat(frames...)\nend\n\n# Part 1 bootstrap: continuous time\nfunction bootstrap_cf_continuous(df::DataFrame, B::Int=500; seed::Int=42)\n    draws   = bootstrap_resample(df, B; seed=seed)\n    results = zeros(B)\n    Threads.@threads for b in 1:B\n        df_b = build_boot_df(df, draws[b])\n        fs   = feols(df_b,  @formula(time ~ phone + frfam + fe(ad_boot) + fe(female)))\n        df_b.v2hat = fs.residuals\n        ss   = fepois(df_b, @formula(visits ~ time + v2hat + frfam + fe(ad_boot) + fe(female)))\n        idx  = findfirst(==(\"time\"), coefnames(ss))\n        results[b] = coef(ss)[idx]\n    end\n    return results\nend\n\nboot1 = bootstrap_cf_continuous(df1, 500)\nnaive_se1 = stderror(m1_cf)[findfirst(==(\"time\"), coefnames(m1_cf))]\ncoef1     = coef(m1_cf)[findfirst(==(\"time\"), coefnames(m1_cf))]\n\n@printf(\"time coefficient:  %.4f  (true %.1f)\\n\", coef1, true_α)\n@printf(\"Naive 2nd-stage SE: %.4f\\n\", naive_se1)\n@printf(\"Bootstrap SE:       %.4f\\n\", std(boot1))\n@printf(\"Bootstrap 95%% CI: [%.4f, %.4f]\\n\",\n        quantile(boot1, 0.025), quantile(boot1, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntime coefficient:  0.8103  (true 0.8)\nNaive 2nd-stage SE: 0.0051\nBootstrap SE:       0.0112\nBootstrap 95% CI: [0.7868, 0.8312]\n```\n:::\n:::\n\n\nThe bootstrapped SE is larger than the naive second-stage SE, confirming that ignoring the first-stage uncertainty understates uncertainty.\n\n\n---\n\n## Part 2 — Binary endogenous variable\n\nWhen $y_2 \\in \\{0,1\\}$, the linear-projection first stage from Part 1 loses its\njustification, and two probit-based alternatives become the theoretically\ngrounded routes instead.\n\n### Data generating process\n\nWe use a clean probit DGP for the binary endogenous variable with a fresh structural error `e2` independent of Part 1.  The endogeneity coefficient `ρ = 0.2` is kept small so the CF assumption holds approximately well and estimates are close to the true value.\n\n::: {.cell execution_count=7}\n``` {.julia .cell-code}\nRandom.seed!(123)\n\n# Fresh structural error for Part 2 (independent of Part 1's e)\ne2 = randn(n)\n\n# Binary endogenous variable: clean probit latent index\n# phone is the excluded instrument; no FE in latent index for clarity\ntime_hi = Int.(1.5 .* phone .+ 0.4 .* frfam .+ e2 .>= 0)\n\n# Poisson outcome — true coefficient 0.8, endogeneity via ρ*e2 (ρ=0.2)\n# Small ρ ensures the approximate CF assumption holds closely\nρ2 = 0.2\nλ2 = exp.(0.5 .+ true_α .* time_hi .+ 0.4 .* frfam .+\n          fe_ad[fe_grp] .+ 0.3 .* female .+ ρ2 .* e2)\nvisits2 = [rand(Poisson(λ2i)) for λ2i in λ2]\n\ndf2 = DataFrame(visits=visits2, time_hi=time_hi, phone=phone,\n                frfam=frfam, female=female, ad=fe_grp, e2=e2)\n\nprintln(\"time_hi mean:      $(round(mean(time_hi), digits=3))\")\nprintln(\"Cor(time_hi, e2):  $(round(cor(time_hi, e2), digits=3))  (endogeneity)\")\nprintln(\"visits mean:       $(round(mean(visits2), digits=2))\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntime_hi mean:      0.727\nCor(time_hi, e2):  0.613  (endogeneity)\nvisits mean:       4.78\n```\n:::\n:::\n\n\n### Why Approach A's assumption breaks down for binary $y_2$\n\nPart 1's control function rests on writing $y_2 = \\mathbf{z}\\boldsymbol{\\pi} + v_2$\nwith $v_2$ *independent* of $\\mathbf{z}$ (Assumption (3.25) in\n@imbens-wooldridge-2007-cf; eq. 18.39 in @wooldridge-2010-crosssection, sec. 18.5).\nThat is an assumption about the reduced form, not a consequence of OLS: the\npopulation linear projection always exists and its residual is always\n*uncorrelated* with $\\mathbf{z}$, but independence is much stronger, and\nindependence is what the Poisson control-function argument needs.\n\nFor a binary $y_2$ it fails by construction. Conditional on $\\mathbf{z}$,\n$v_2 = y_2 - \\mathbf{z}\\boldsymbol{\\pi}$ takes only the two values\n$1-\\mathbf{z}\\boldsymbol{\\pi}$ and $-\\mathbf{z}\\boldsymbol{\\pi}$, and\n$\\mathrm{Var}(v_2\\mid\\mathbf{z}) = p(\\mathbf{z})[1-p(\\mathbf{z})]$ is itself a\nfunction of $\\mathbf{z}$. Wooldridge says as much for exactly this case: \"it\nwould be very unusual for a discrete variable to be expressible as a linear\nequation with additive error independent of $\\mathbf{z}$\"\n[@wooldridge-2010-crosssection, sec. 18.5]. For a Poisson outcome with a binary\nendogenous variable he replaces the linear reduced form with the threshold model\n$y_2 = 1[\\mathbf{z}\\boldsymbol{\\pi}_2 + v_2 \\ge 0]$ and *keeps* the independence\nassumption, now about the latent $v_2$ [@imbens-wooldridge-2007-cf, sec. 3.3].\n\nThat is the distinction to hold on to, because Approach B's generalized residual\nis two-valued given $\\mathbf{z}$ as well. Discreteness of the derived residual is\nnot the issue; which object independence is asserted about is. Approach A asserts\nit of the observed $v_2$, where both the two values and the probabilities of\nlanding on them move with $\\mathbf{z}$. Terza's setup asserts it of the\ncontinuous latent probit error, $v_2 \\mid \\mathbf{z} \\sim N(0,1)$ --- the\nassumption every probit already makes.\n\nSo for a binary $y_2$, Approach A is not a weaker-but-valid alternative to\nApproach B; its own first-stage assumption cannot hold. What survives is the\nlocal approximation derived next, plus its validity as a Hausman-type exogeneity\ntest, since under $H_0:\\rho=0$ there is no endogeneity left to approximate.\n\n### The exact correction (Terza 1998) and Approach B as its local approximation\n\n@terza-1998, exposited in @wooldridge-2010-crosssection (sec. 18.5) and\n@imbens-wooldridge-2007-cf (sec. 3.3, eqs. 3.32–3.36), derives the *exact*\ncontrol function when $y_2$ follows a probit, $y_2 = 1[\\mathbf{z}\\boldsymbol{\\pi}_2 + v_2 \\geq 0]$,\nand $(c_1, v_2)$ — the Poisson heterogeneity and the probit error — are\njointly normal. Here $\\rho$ is the *coefficient* in the linear projection of\n$c_1$ on $v_2$, i.e. $E(\\exp(c_1) \\mid v_2) = \\exp(\\rho v_2)$ — **not** the\ncorrelation between them. With $v_2$ standard normal the two differ by a factor\nof $\\sigma_{c_1}$, since $\\rho = \\mathrm{Corr}(c_1,v_2)\\,\\sigma_{c_1}$, and the\ndistinction is not cosmetic: this chapter's DGP sets $c_1 = 0.2\\,e_2$ with\n$v_2 = e_2$, so the *correlation* is exactly $1$ while the $\\rho$ that governs\nthe approximation below is $0.2$. Reading $\\rho$ as a correlation is also what\n$h(\\cdot)$ forbids — it is $\\rho$ in the coefficient sense that makes\n$\\exp(\\rho^2/2)$ the lognormal correction and puts $\\rho$ on the same scale as\nthe probit index. It is **not** \"add the\ngeneralized residual linearly inside $\\exp(\\cdot)$\" (that is Approach B as\ncoded below). The exact result is multiplicative:\n\n$$E(y_1 \\mid \\mathbf{z}, y_2) = \\exp(\\mathbf{z}_1\\boldsymbol{\\delta}_1 + \\alpha_1 y_2)\\cdot h(y_2, \\mathbf{z}\\boldsymbol{\\pi}_2, \\rho)$$ {#eq-poisson-iv-2}\n$$h(y_2, \\mathbf{z}\\boldsymbol{\\pi}_2, \\rho) = \\exp(\\rho^2/2)\\left\\{y_2\\,\\frac{\\Phi(\\rho + \\mathbf{z}\\boldsymbol{\\pi}_2)}{\\Phi(\\mathbf{z}\\boldsymbol{\\pi}_2)} + (1-y_2)\\,\\frac{1-\\Phi(\\rho + \\mathbf{z}\\boldsymbol{\\pi}_2)}{1-\\Phi(\\mathbf{z}\\boldsymbol{\\pi}_2)}\\right\\}$$ {#eq-poisson-iv-3}\n\nestimated by plugging in the first-stage probit's $\\hat{\\boldsymbol{\\pi}}_2$\nand then jointly QMLE-fitting $(\\boldsymbol\\delta_1,\\alpha_1,\\rho)$ against this\nmean function — a genuinely nonlinear second stage, not a linear regressor\naddition.\n\n**Why Approach B (linear addition of the generalized residual) is a good\napproximation, and exactly how good.** Taylor-expand $h$ in $\\rho$ around\n$\\rho=0$. Since $\\tfrac{d}{d\\rho}\\exp(\\rho^2/2)\\big|_{\\rho=0}=0$, only the\n$\\Phi$-ratio terms contribute to first order:\n$$\\left.\\frac{\\partial}{\\partial\\rho}\\frac{\\Phi(\\rho+\\mathbf{z}\\boldsymbol\\pi_2)}{\\Phi(\\mathbf{z}\\boldsymbol\\pi_2)}\\right|_{\\rho=0} = \\frac{\\phi(\\mathbf{z}\\boldsymbol\\pi_2)}{\\Phi(\\mathbf{z}\\boldsymbol\\pi_2)} = \\lambda(\\mathbf{z}\\boldsymbol\\pi_2), \\qquad\n\\left.\\frac{\\partial}{\\partial\\rho}\\frac{1-\\Phi(\\rho+\\mathbf{z}\\boldsymbol\\pi_2)}{1-\\Phi(\\mathbf{z}\\boldsymbol\\pi_2)}\\right|_{\\rho=0} = -\\lambda(-\\mathbf{z}\\boldsymbol\\pi_2)$$ {#eq-poisson-iv-4}\nwhere $\\lambda(\\cdot)=\\phi(\\cdot)/\\Phi(\\cdot)$ is the inverse Mills ratio (this\nis exactly the `gr2` computed via `pdf(nd, η) / cdf(nd, η)` below). Since\n$h(y_2,\\mathbf{z}\\boldsymbol\\pi_2,0)=1$,\n$$h(y_2,\\mathbf{z}\\boldsymbol\\pi_2,\\rho) \\approx 1 + \\rho\\cdot\\underbrace{\\bigl[y_2\\lambda(\\mathbf{z}\\boldsymbol\\pi_2) - (1-y_2)\\lambda(-\\mathbf{z}\\boldsymbol\\pi_2)\\bigr]}_{=\\ \\hat r_2,\\ \\text{the generalized residual}}$$ {#eq-poisson-iv-5}\nand $\\exp(x_1\\beta_1)\\cdot h(\\cdot) \\approx \\exp(x_1\\beta_1)\\cdot(1+\\rho\\, \\hat r_2) \\approx \\exp(x_1\\beta_1 + \\rho\\,\\hat r_2)$\nfor small $\\rho\\,\\hat r_2$ — recovering exactly Approach B's construction\n(adding $\\hat r_2$ linearly inside $\\exp(\\cdot)$). So **Approach B is the\nfirst-order-in-$\\rho$ local approximation to Terza's exact correction**, not\nthe exact correction itself; the approximation error is $O(\\rho^2)$. This is\nconsistent with the DGP above (small $\\rho=0.2$, kept deliberately small so\nthis approximation stays tight) and with a direct large-$n$ check of both A\nand B run against the R companion chapter's version of this DGP: the\nprobability limits are $\\hat\\alpha_1^A \\to 0.839$ and $\\hat\\alpha_1^B \\to\n0.822$ against the true $0.8$ — both biased, B roughly half of A's bias,\nmatching the theoretical ranking (B is a valid local approximation to the\nexact correction; A has no such derivation behind it at all for binary\n$y_2$) but neither exact.\n\n### Why use Approach B instead of the exact correction?\n\nIf Terza's $h(\\cdot)$ is exact and Approach B only approximates it, why does\nanyone use the approximation? Because $h(\\cdot)$ does not reduce to\n$\\exp(\\text{linear index})$: the $\\Phi$-ratios and the $\\exp(\\rho^2/2)$ term make\nthe second stage genuinely nonlinear in $\\rho$, so it needs custom optimisation\ncode, and combining that with the within-group demeaning that makes FE-Poisson\ntractable is not straightforward. The cost scales badly exactly where FE-Poisson\nis most needed, with many high-dimensional fixed effects. Approach B's second\nstage instead has the same functional form as ordinary Poisson with one extra\nregressor in the index, so it drops into standard Poisson machinery unmodified.\nJoint nonlinear estimation would be more efficient, but Wooldridge notes for the\nclosely analogous binary-$y_1$ case that the iterations can be hard to converge,\nwith $\\hat\\rho_1$ drifting toward $\\pm 1$ [@wooldridge-2010-crosssection, sec.\n15.7.3]. At $\\rho = 0.2$ the approximation error is small next to sampling noise\nanyway, and the coefficient on $\\hat r_2$ doubles as a Hausman-type $t$-test for\nexogeneity sitting next to the coefficient of interest. This is the usual\ncontrol-function tradeoff: give up some efficiency for a second stage that is\nnumerically simple, compatible with existing FE software, and easy to read.\n\n### Three approaches: practical recap\n\n| | First stage | What enters 2nd stage | Status for binary $y_2$ |\n|---|---|---|---|\n| **A** | `feols` (OLS) | Residuals $\\hat{v}_2$ | **No valid first-stage assumption** — $v_2$ independent of $\\mathbf{z}$ fails by construction; usable only as an approximation, and as a Hausman-type exogeneity test |\n| **B** | `feprobit` | Gen. residuals $\\hat{r}_2$ | First-order-in-$\\rho$ local approximation to Terza's exact correction; requires probit correctly specified |\n| **C** | Any model | Fitted values $\\hat{p}_2$ | Distribution-free (@mullahy-1997) with the multiplicative moments — robust to misspecification of the model for $\\Pr(y_2=1\\mid\\mathbf{z})$ |\n\nA and B additionally require the second-stage Poisson conditional mean to be\ncorrectly specified. C's validity does not depend on how well the first-stage\nmodel for $y_2$ fits.\n\n### Approach A — Linear projection CF\n\n::: {.cell execution_count=8}\n``` {.julia .cell-code}\n# Step 1: linear projection of binary time_hi\nfs_a = feols(df2, @formula(time_hi ~ phone + frfam + fe(ad) + fe(female)))\ndf2.v2hat = fs_a.residuals\n\n# Step 2: Poisson CF\nm_a = fepois(df2, @formula(visits ~ time_hi + v2hat + frfam + fe(ad) + fe(female)))\nprintln(\"Approach A — Linear projection CF:\")\nshow_regression_html(m_a; title=\"Approach A: OLS residual as control function\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nApproach A — Linear projection CF:\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<p><strong>Approach A: OLS residual as control function</strong></p><table style=\"border-collapse: collapse; font-family: monospace; font-size: 13px; margin: 0.5em 0;\"><thead><tr><th style=\"text-align: left; padding: 4px 10px 4px 0; border-bottom: 1px solid black;\"></th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Estimate</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Std. Error</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">t value</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Pr(>|t|)</th></tr></thead><tbody><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">time_hi</td><td style=\"text-align: right; padding: 3px 8px;\">0.813</td><td style=\"text-align: right; padding: 3px 8px;\">0.036</td><td style=\"text-align: right; padding: 3px 8px;\">22.719</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">v2hat</td><td style=\"text-align: right; padding: 3px 8px;\">0.330</td><td style=\"text-align: right; padding: 3px 8px;\">0.035</td><td style=\"text-align: right; padding: 3px 8px;\">9.396</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">frfam</td><td style=\"text-align: right; padding: 3px 8px;\">0.413</td><td style=\"text-align: right; padding: 3px 8px;\">0.023</td><td style=\"text-align: right; padding: 3px 8px;\">17.921</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 6px 0 0 0; border-top: 1px solid black;\" colspan=\"5\">---<br/>Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</td></tr></tbody></table>\n```\n:::\n:::\n\n\n### Approach B — Probit generalized residuals\n\n::: {.cell execution_count=9}\n``` {.julia .cell-code}\n# Step 1: probit first stage\nfs_b = feprobit(df2, @formula(time_hi ~ phone + frfam + fe(ad) + fe(female)))\n\n# Generalized residual (Gourieroux et al.): φ(η)/Φ(η) if y=1 (inverse Mills ratio),\n# -φ(η)/(1-Φ(η)) if y=0 (the reverse Mills ratio).\nη  = fs_b.eta\nnd = Normal()\ndf2.gr2 = @. ifelse(df2.time_hi == 1,\n    pdf(nd, η) / cdf(nd, η),\n    -pdf(nd, η) / (1.0 - cdf(nd, η)))\n\n# Step 2: Poisson CF with generalized residual\nm_b = fepois(df2, @formula(visits ~ time_hi + gr2 + frfam + fe(ad) + fe(female)))\nprintln(\"Approach B — Probit generalized residual CF:\")\nshow_regression_html(m_b; title=\"Approach B: probit generalized residual\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nApproach B — Probit generalized residual CF:\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<p><strong>Approach B: probit generalized residual</strong></p><table style=\"border-collapse: collapse; font-family: monospace; font-size: 13px; margin: 0.5em 0;\"><thead><tr><th style=\"text-align: left; padding: 4px 10px 4px 0; border-bottom: 1px solid black;\"></th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Estimate</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Std. Error</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">t value</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Pr(>|t|)</th></tr></thead><tbody><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">time_hi</td><td style=\"text-align: right; padding: 3px 8px;\">0.764</td><td style=\"text-align: right; padding: 3px 8px;\">0.039</td><td style=\"text-align: right; padding: 3px 8px;\">19.549</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">gr2</td><td style=\"text-align: right; padding: 3px 8px;\">0.230</td><td style=\"text-align: right; padding: 3px 8px;\">0.024</td><td style=\"text-align: right; padding: 3px 8px;\">9.721</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">frfam</td><td style=\"text-align: right; padding: 3px 8px;\">0.415</td><td style=\"text-align: right; padding: 3px 8px;\">0.023</td><td style=\"text-align: right; padding: 3px 8px;\">17.969</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 6px 0 0 0; border-top: 1px solid black;\" colspan=\"5\">---<br/>Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</td></tr></tbody></table>\n```\n:::\n:::\n\n\n### Does the first stage have to be probit? Logit works too — with a caveat\n\nNothing about the local-approximation argument above is specific to the\nnormal distribution. The generalized residual is defined for *any*\ncorrectly-specified binary-response GLM\n[@gourieroux-monfort-renault-trognon-1987], and for a **logit** first stage\nit collapses to something particularly simple. With $\\Lambda(\\cdot)$ the\nlogistic CDF and $\\lambda(\\eta)=\\Lambda(\\eta)[1-\\Lambda(\\eta)]$ its density,\n\n$$\\hat r_2 = y_2\\cdot\\frac{\\lambda(\\hat\\eta)}{\\Lambda(\\hat\\eta)} - (1-y_2)\\cdot\\frac{\\lambda(\\hat\\eta)}{1-\\Lambda(\\hat\\eta)}\n= y_2\\bigl[1-\\Lambda(\\hat\\eta)\\bigr] - (1-y_2)\\Lambda(\\hat\\eta) = y_2 - \\Lambda(\\hat\\eta) = y_2 - \\hat p_2,$$ {#eq-poisson-iv-6}\n\ni.e. **the logit generalized residual is just the plain response residual**\n$y_2-\\hat p_2$ — no Mills-ratio machinery needed: `logit` first stage, then\n`y2 .- predict(fit)`, is the right generalized residual, not a shortcut.\n\n::: {.cell execution_count=10}\n``` {.julia .cell-code}\nfs_b_logit = felogit(df2, @formula(time_hi ~ phone + frfam + fe(ad) + fe(female)))\nphat_logit = fs_b_logit.mu\ndf2.gr2_logit = df2.time_hi .- phat_logit    # algebraically = generalized residual\n\nm_b_logit = fepois(df2, @formula(visits ~ time_hi + gr2_logit + frfam + fe(ad) + fe(female)))\nprintln(\"Approach B with a logit first stage:\")\nshow_regression_html(m_b_logit; title=\"Approach B: logit generalized residual\")\n\ncoef_b_probit = coef(m_b)[findfirst(==(\"time_hi\"), coefnames(m_b))]\ncoef_b_logit  = coef(m_b_logit)[findfirst(==(\"time_hi\"), coefnames(m_b_logit))]\n@printf(\"Probit-based Approach B: alpha1 = %.4f\\n\", coef_b_probit)\n@printf(\"Logit-based  Approach B: alpha1 = %.4f\\n\", coef_b_logit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nApproach B with a logit first stage:\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<p><strong>Approach B: logit generalized residual</strong></p><table style=\"border-collapse: collapse; font-family: monospace; font-size: 13px; margin: 0.5em 0;\"><thead><tr><th style=\"text-align: left; padding: 4px 10px 4px 0; border-bottom: 1px solid black;\"></th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Estimate</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Std. Error</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">t value</th><th style=\"text-align: right; padding: 4px 8px; border-bottom: 1px solid black;\">Pr(>|t|)</th></tr></thead><tbody><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">time_hi</td><td style=\"text-align: right; padding: 3px 8px;\">0.800</td><td style=\"text-align: right; padding: 3px 8px;\">0.036</td><td style=\"text-align: right; padding: 3px 8px;\">22.145</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">gr2_logit</td><td style=\"text-align: right; padding: 3px 8px;\">0.346</td><td style=\"text-align: right; padding: 3px 8px;\">0.036</td><td style=\"text-align: right; padding: 3px 8px;\">9.698</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 3px 10px 3px 0;\">frfam</td><td style=\"text-align: right; padding: 3px 8px;\">0.413</td><td style=\"text-align: right; padding: 3px 8px;\">0.023</td><td style=\"text-align: right; padding: 3px 8px;\">17.878</td><td style=\"text-align: right; padding: 3px 8px; white-space: nowrap;\">&lt; 2e-16 ***</td></tr><tr><td style=\"text-align: left; padding: 6px 0 0 0; border-top: 1px solid black;\" colspan=\"5\">---<br/>Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</td></tr></tbody></table>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nProbit-based Approach B: alpha1 = 0.7636\nLogit-based  Approach B: alpha1 = 0.8000\n```\n:::\n:::\n\n\nTwo limits are worth noting. Terza's *exact* correction is probit-specific: the\nclosed form $h(\\cdot)$ comes from the truncated moments of the bivariate normal,\nand no analogue for a logistic $v_2$ appears in @terza-1998,\n@wooldridge-2010-crosssection or @imbens-wooldridge-2007-cf. Logit gives Approach\nB with the same $O(\\rho^2)$ error as probit, but no logit version of the exact\ncorrection. Second, the link-robustness that Approach C enjoys --- the fitted\nprobability is a valid instrument even if the link is wrong, since any function\nof $\\mathbf z$ is a valid instrument [@imbens-wooldridge-2007-cf] --- belongs to\nusing the fitted value as an *instrument*, not as a *residual*. It does not carry\nover to A or B, where the second-stage conditional mean still has to be right.\n\n### Approach C — Fitted values as instrument (IV/GMM Poisson)\n\nAny function of the exogenous $\\mathbf{z}$ is a valid instrument.  Probit, logit, and linear probability fitted values are all equally valid from a consistency standpoint — the choice affects efficiency (instrument strength).  We implement IV/GMM Poisson directly, keeping `time_hi` as the regressor and using probit fitted probabilities as the instrument.  We code **both moment forms**: the additive moments are what \"IV Poisson\" often means in practice (e.g. Stata's `ivpoisson gmm` default additive option), but because this chapter's DGP puts the unobservable inside $\\exp(\\cdot)$, only the multiplicative (Mullahy) moments are consistent here:\n\n::: {.cell execution_count=11}\n``` {.julia .cell-code}\n\"\"\"\n    ivpois(y, X, Z) -> (β, se)\n\nIV/GMM Poisson (just-identified). X = [endog, exog], Z = [instrument, exog].\nDamped IRLS: intercept initialised from log(mean(y)), half-steps for stability.\n\"\"\"\nfunction ivpois(y::Vector{Float64}, X::Matrix{Float64}, Z::Matrix{Float64};\n                maxiter=500, tol=1e-8, step=0.5)\n    p  = size(X, 2)\n    β  = zeros(p)\n    β[p] = log(mean(y))    # intercept from marginal mean — prevents divergence\n\n    for _ in 1:maxiter\n        μ = exp.(clamp.(X * β, -30.0, 30.0))\n        H = Z' * (μ .* X)\n        g = Z' * (y .- μ)\n        Δ = try H \\ g catch; pinv(H) * g end\n        β .+= step .* Δ\n        maximum(abs.(step .* Δ)) < tol && break\n    end\n\n    μ = exp.(clamp.(X * β, -30.0, 30.0))\n    H = Z' * (μ .* X)\n    B = Z' * ((y .- μ).^2 .* Z)       # robust sandwich meat\n    V = try inv(H) * B * inv(H)' catch; pinv(H) * B * pinv(H)' end\n    return β, sqrt.(max.(0.0, diag(V)))\nend\n\n\"\"\"\n    ivpois_mult(y, X, Z) -> β\n\nIV/GMM Poisson with MULTIPLICATIVE (Mullahy 1997) moments\nZ'(y .* exp(-Xβ) .- 1) = 0 — consistent when the unobservable enters\ninside the exponential mean (multiplicative error).\n\"\"\"\nfunction ivpois_mult(y::Vector{Float64}, X::Matrix{Float64}, Z::Matrix{Float64};\n                     maxiter=1000, tol=1e-10, step=0.5)\n    p  = size(X, 2)\n    β  = zeros(p)\n    β[p] = log(mean(y))\n    for _ in 1:maxiter\n        w = y .* exp.(clamp.(-X * β, -30.0, 30.0))\n        g = Z' * (w .- 1)\n        H = Z' * (w .* X)\n        Δ = try H \\ g catch; pinv(H) * g end\n        β .+= step .* Δ\n        maximum(abs.(step .* Δ)) < tol && break\n    end\n    return β\nend\n\n# Probit (without FE, to avoid collinearity with instrument matrix)\nfs_c  = feprobit(df2, @formula(time_hi ~ phone + frfam))\nphat  = fs_c.mu\n\n# Regressor matrix X: [time_hi, frfam, intercept]\n# Instrument matrix Z: [phat,    frfam, intercept]  ← phat replaces time_hi\nX_c = hcat(Float64.(df2.time_hi), Float64.(df2.frfam), ones(n))\nZ_c = hcat(Float64.(phat),        Float64.(df2.frfam), ones(n))\n\nβ_c, se_c = ivpois(Float64.(df2.visits), X_c, Z_c)\nβ_cm      = ivpois_mult(Float64.(df2.visits), X_c, Z_c)\n@printf(\"\\nApproach C — IV/GMM Poisson (no FE, for illustration)\\n\")\n@printf(\"  additive moments:       time_hi = %7.4f   SE = %7.4f\\n\",\n        β_c[1], se_c[1])\n@printf(\"  multiplicative moments: time_hi = %7.4f   (true %.1f)\\n\",\n        β_cm[1], true_α)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nApproach C — IV/GMM Poisson (no FE, for illustration)\n  additive moments:       time_hi =  0.5273   SE =  0.0706\n  multiplicative moments: time_hi =  0.7260   (true 0.8)\n```\n:::\n:::\n\n\nThe additive-moment estimate is visibly biased — the DGP's unobservable\n$\\rho\\,e_2$ sits inside $\\exp(\\cdot)$, so the additive moments are\nmisspecified (a 30-replication check gives an additive-moment mean of\nabout $0.61$ against a multiplicative-moment mean of about $0.79$, with\ntrue value $0.8$). The multiplicative moments repair it.\n\n::: {.callout-note}\n**Approach C with FE** requires demeaning the regressor and instrument matrices via within-group centering before solving the IV Poisson moment conditions.  Because Poisson is nonlinear this is not straightforward, and `ivpoisson` in Stata similarly drops `absorb()`.  Approaches A and B both run unmodified in `feols`/`feglm` + `fepois`, so either is practical when many fixed effects are present; of the two, prefer B (see the takeaway below).\n:::\n\n### A vs C — not equivalent in Poisson\n\nIn a linear model, using $\\hat{y}_2$ as an instrument (2SLS) is numerically identical to adding $\\hat{v}_2 = y_2 - \\hat{y}_2$ as a regressor — the Frisch-Waugh-Lovell theorem.  **In Poisson this equivalence breaks**, because Approach A puts $\\hat{v}_2$ inside $\\exp(\\cdot)$ while Approach C uses $\\hat{y}_2$ in the moment conditions without modifying the exponential mean.\n\n::: {.cell execution_count=12}\n``` {.julia .cell-code}\n# Use linear fitted values as instruments (Approach C with linear first stage)\nŷ2  = Float64.(df2.time_hi) .- Float64.(fs_a.residuals)\nX_l = hcat(Float64.(df2.time_hi), Float64.(df2.frfam), ones(n))\nZ_l = hcat(ŷ2,                    Float64.(df2.frfam), ones(n))\n\nβ_l, _ = ivpois(Float64.(df2.visits), X_l, Z_l)\n\ncoef_a = coef(m_a)[findfirst(==(\"time_hi\"), coefnames(m_a))]\n@printf(\"Approach A  (CF, residual as regressor, with FE):     α̂₁ = %.4f\\n\", coef_a)\n@printf(\"C-additive  (IV, linear fitted values, no FE):        α̂₁ = %.4f\\n\", β_l[1])\n@printf(\"C-additive  (IV, probit fitted values, no FE):        α̂₁ = %.4f\\n\", β_c[1])\n@printf(\"C-Mullahy   (IV, multiplicative moments, no FE):      α̂₁ = %.4f\\n\", β_cm[1])\n@printf(\"True α₁ = %.1f\\n\", true_α)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nApproach A  (CF, residual as regressor, with FE):     α̂₁ = 0.8128\nC-additive  (IV, linear fitted values, no FE):        α̂₁ = 0.6194\nC-additive  (IV, probit fitted values, no FE):        α̂₁ = 0.5273\nC-Mullahy   (IV, multiplicative moments, no FE):      α̂₁ = 0.7260\nTrue α₁ = 0.8\n```\n:::\n:::\n\n\nThe estimates differ despite using the same first-stage linear projection, confirming that 2SLS ≠ CF for Poisson — and, within Approach C, that the moment form matters as much as the instrument.\n\n### Bootstrap for Approach A (binary EEV)\n\n::: {.cell execution_count=13}\n``` {.julia .cell-code}\n# Part 2 bootstrap: binary time_hi\nfunction bootstrap_cf_binary(df::DataFrame, B::Int=500; seed::Int=42)\n    draws   = bootstrap_resample(df, B; seed=seed)\n    results = zeros(B)\n    Threads.@threads for b in 1:B\n        df_b = build_boot_df(df, draws[b])\n        fs   = feols(df_b,  @formula(time_hi ~ phone + frfam + fe(ad_boot) + fe(female)))\n        df_b.v2hat = fs.residuals\n        ss   = fepois(df_b, @formula(visits ~ time_hi + v2hat + frfam + fe(ad_boot) + fe(female)))\n        idx  = findfirst(==(\"time_hi\"), coefnames(ss))\n        results[b] = coef(ss)[idx]\n    end\n    return results\nend\n\nboot2 = bootstrap_cf_binary(df2, 500)\nnaive_se2 = stderror(m_a)[findfirst(==(\"time_hi\"), coefnames(m_a))]\n\n@printf(\"Approach A bootstrap (binary EEV, 500 reps, cluster by ad)\\n\")\n@printf(\"  Point estimate:     %.4f  (true %.1f)\\n\", coef_a, true_α)\n@printf(\"  Naive 2nd-stage SE: %.4f\\n\", naive_se2)\n@printf(\"  Bootstrap SE:       %.4f\\n\", std(boot2))\n@printf(\"  Bootstrap 95%% CI:  [%.4f, %.4f]\\n\",\n        quantile(boot2, 0.025), quantile(boot2, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nApproach A bootstrap (binary EEV, 500 reps, cluster by ad)\n  Point estimate:     0.8128  (true 0.8)\n  Naive 2nd-stage SE: 0.0358\n  Bootstrap SE:       0.0343\n  Bootstrap 95% CI:  [0.7380, 0.8766]\n```\n:::\n:::\n\n\n### Comparison across all methods\n\n::: {.cell execution_count=14}\n``` {.julia .cell-code}\ncoef_naive2 = coef(\n    fepois(df2, @formula(visits ~ time_hi + frfam + fe(ad) + fe(female)))\n)[findfirst(==(\"time_hi\"),\n    coefnames(fepois(df2, @formula(visits ~ time_hi + frfam + fe(ad) + fe(female)))))]\ncoef_b = coef(m_b)[findfirst(==(\"time_hi\"), coefnames(m_b))]\n\nmethods = [\"True value\", \"Naive Poisson (binary y₂)\",\n           \"A: Linear CF (with FE)\", \"B: Probit GR CF (with FE)\",\n           \"C: IV Poisson, additive moments (no FE)\",\n           \"C: IV Poisson, Mullahy moments (no FE)\"]\nests    = [true_α, coef_naive2, coef_a, coef_b, β_c[1], β_cm[1]]\n\nprintln(\"\\n── Binary EEV: coefficient on time_hi ─────────────────────\")\nfor (m, e) in zip(methods, ests)\n    @printf(\"  %-42s  α̂₁ = %6.4f\\n\", m, e)\nend\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n── Binary EEV: coefficient on time_hi ─────────────────────\n  True value                                  α̂₁ = 0.8000\n  Naive Poisson (binary y₂)                   α̂₁ = 1.0852\n  A: Linear CF (with FE)                      α̂₁ = 0.8128\n  B: Probit GR CF (with FE)                   α̂₁ = 0.7636\n  C: IV Poisson, additive moments (no FE)     α̂₁ = 0.5273\n  C: IV Poisson, Mullahy moments (no FE)      α̂₁ = 0.7260\n```\n:::\n:::\n\n\nThe CF approaches (A, B) recover the truth closely — with small $\\rho=0.2$\nthe approximate CF mean assumption is mild (A has no valid first-stage\nassumption for binary $y_2$; B is correct only to first order in $\\rho$, per\nthe derivation above). Additive-moment IV Poisson does not: the unobservable\nenters inside $\\exp(\\cdot)$, so its moments are misspecified (Mullahy 1997).\nThe multiplicative-moment version repairs it, and in one specific sense does more\nthan repair it: the `ad` and `female` effects it omits are independent\nmultiplicative heterogeneity, absorbed by the intercept under the multiplicative\nmoments ($\\beta_0 \\to \\beta_0 + \\log E[e^{c}]$), so dropping the fixed effects\ncosts no slope *bias* at all. Mullahy's moments are *consistent* for this DGP,\nwhere A and B are only approximately unbiased — $0.8015$ at $n=10^6$ (sd\n$0.0013$), against plims of $0.839$ and $0.822$.\n\nWhat consistency does not buy is precision, and that is why the table above can\nlook as though it says the opposite. Without the fixed effects the\nmultiplicative-moment estimator is roughly three times as noisy as A or B (sd\n$0.068$ against $0.024$ and $0.026$, over 10 seeds at this chapter's $n=5000$),\nso a single draw can leave the only consistent estimator of the three further\nfrom $0.8$ than either CF estimator. At this sample size its RMSE is in fact the\nworst of the three ($0.065$, against A's $0.039$ and B's $0.031$); the ranking\nreverses as $n$ grows. Read the comparison as one draw from that tradeoff, not\nas a verdict.\n\n### Takeaway for the binary case\n\n- **Use Approach B when you need fixed effects.** Among the estimators that\n  drop into FE-Poisson unmodified it is the theoretically motivated choice, and\n  its error is *derived*, not assumed: $O(\\rho^2)$, shrinking as the endogeneity\n  shrinks.\n- **Approach C trades bias for variance — decide which one binds.** Mullahy's\n  multiplicative moments are *consistent* here, not merely accurate to first\n  order, whenever the multiplicative heterogeneity is independent of\n  $\\mathbf z$. But consistency is not accuracy at a given sample size. Over 10\n  seeds at this chapter's $n=5000$, C is nearly unbiased (mean $0.7985$) and yet\n  almost three times as noisy as B (sd $0.068$ against $0.026$), so its RMSE is\n  the *worst* of the three: $0.065$, against A's $0.039$ and B's $0.031$. B's\n  small derived bias buys a great deal of precision. Prefer C once $n$ is large\n  enough that its variance is not the binding constraint — and note that it does\n  not accommodate high-dimensional fixed effects either way.\n- **Approach A is a fallback, not a first choice.** It lands close to the truth\n  at $\\rho=0.2$ here, but it has no theoretical justification for binary $y_2$.\n  Do not lean on it when $\\rho$ is not known to be small.\n- **Probit or logit both work for Approach B.** Only Terza's exact correction\n  needs normality.\n\n## Why Julia is faster\n\nThe parallel bootstrap above uses `Threads.@threads` which runs each of the 500 replications simultaneously across all CPU cores.  A single replication calls `feols` + `fepois`, both implemented with the fast within-demeaning algorithm from `Panelest.jl`.  On a machine with 8 cores this is roughly 6–8× faster than Stata's serial `bootstrap` command, and the speed advantage grows with replication count and sample size.\n\n",
    "supporting": [
      "poisson-iv_files/figure-pdf"
    ],
    "filters": []
  }
}